<div class="connection-random-users">
   <a href="<?php echo vipub_link("@".$connect_people["username"]); ?>">
        <img src="<?php echo vipub_link($connect_people["avatar"]); ?>">
        <span><?php echo $connect_people["username"]; ?>
        <?php if($connect_people["verified"]=="1"): ?>
            <?php echo vipub_userBlue(); ?>
        <?php endif; ?>
        <h5><?php echo $connect_people["fullname"]; ?>
        <small>
        <?php if($connect_people["user_bio"]==NULL): ?>
            <?php echo $connect_people["followers"]; ?> 
            <?php echo vipub_translate("connect_people_for_following_info_small"); ?>
        <?php else: ?>
            <?php echo vipub_croptxt($connect_people["user_bio"], 0, 55); ?>  · 
            <?php echo $connect_people["followers"]; ?> <?php echo vipub_translate("connect_people_for_following_info_small"); ?>
        <?php endif; ?>
        </small>
        </h5> 
        </span>
    </a>

    
    <form class="vipubUser-follow" data-user-id="<?php echo $connect_people["id"]; ?>">
        <input type="hidden" name="user_id" value="<?php echo $connect_people["id"]; ?>">
        <button class="follow-value"><?php echo vipub_translate("follow"); ?></button>
    </form>
</div>
<script>
    $(document).ready(function() {
        // Takip butonuna tıklama işlemi
        $('.vipubUser-follow').on('click', '.follow-value', function(e) {
            e.preventDefault();

            var form = $(this).closest('.vipubUser-follow'); // Butona ait formu seç
            var user_id = form.find('input[name="user_id"]').val(); // Kullanıcının ID'sini al
            var button = form.find('.follow-value'); // Butonu seç

            // Takip butonuna tıklama durumu
            if (button.data('clicked')) {
                return; // Butona ardışık tıklamaları engelle
            }

            button.data('clicked', true); // Butona tıklama durumunu işaretle

            var follow_status = button.text();

            $.ajax({
                url: '/apps/ajax/profile/user-follow.phtml',
                method: 'POST',
                data: {
                    user_id: user_id,
                    follow_status: follow_status
                },
                success: function(data) {
                    if (follow_status == '<?php echo vipub_translate("follow"); ?>') {
                        button.text('<?php echo vipub_translate("unfollow"); ?>');
                    } else {
                        button.text('<?php echo vipub_translate("follow"); ?>');
                        new Noty({
                            type: 'error',
                            text: "<?php echo vipub_translate("unfollow_user"); ?>",
                            timeout: 2000
                        }).show();
                    }
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    console.log("Hata: " + textStatus + " - " + errorThrown);
                },
                complete: function() {
                    button.data('clicked', false);
                }
            });
        });
        checkFollowStatus();
    });
    function checkFollowStatus() {
        $('.vipubUser-follow').each(function() {
            var form = $(this);
            var user_id = form.find('input[name="user_id"]').val();

            $.ajax({
                url: '/apps/ajax/profile/check-follow.phtml',
                method: 'POST',
                data: {
                    user_id: user_id
                },
                success: function(data) {
                    if (follow_status == '<?php echo vipub_translate("follow"); ?>') {
                        button.text('<?php echo vipub_translate("unfollow"); ?>');
                    } else {
                        button.text('<?php echo vipub_translate("follow"); ?>');
                        new Noty({
                            type: 'error',
                            text: "<?php echo vipub_translate("unfollow_user"); ?>",
                            timeout: 2000
                        }).show();
                    }
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    console.log("Error: " + textStatus + " - " + errorThrown);
                }
            });
        });
    }
</script>