<?php if(isset($_SESSION["user_id"])): $settings = vipub_site_settings(); ?>
    <?php $app = isset($_GET['app']) ? $_GET['app'] : 'home';?>
    <?php $vipub["account"] = vipub_my_user_info(); ?>
    <!--Burası sol kenar çubuğu-->
<div class="col-md-3">
    <div class="main-left-sidebar">
        <div class="main-site-logo">
            <a href="<?php echo vipub_link("home"); ?>">
                <?php if($vipub["account"]["theme_color"]=="master.white.theme"): ?>
                    <img src="<?php echo vipub_link($settings["site_white_logo"]); ?>">
                <?php elseif($vipub["account"]["theme_color"]=="master.dark.theme"): ?>
                    <img src="<?php echo vipub_link($settings["site_dark_logo"]); ?>">
                <?php endif; ?>
            </a>
            </div>
            
            <div class="main-sidebar-menu">
                <a class="<?php echo ($app == 'home') ? 'page-active' : ''; ?>" href="<?php echo vipub_link("home"); ?>">
                    <i class="bi bi-house-door"></i>
                    <?php echo vipub_translate("homepage"); ?>
                </a>

                <a class="<?php echo ($app == 'search') ? 'page-active' : ''; ?>" href="<?php echo vipub_link("search"); ?>">
                    <i class="bi bi-search"></i>
                    <?php echo vipub_translate("search"); ?>
                </a>

                <a class="<?php echo ($app == 'notifications') ? 'page-active' : ''; ?>" href="<?php echo vipub_link("notifications"); ?>">
                    <span id="check-notifs"></span>
                    <i class="bi bi-bell"></i>
                    <?php echo vipub_translate("notifications"); ?>
                </a>

                <a class="<?php echo ($app == 'messages') ? 'page-active' : ''; ?>" href="<?php echo vipub_link("messages"); ?>">
                    <span id="check-message"></span>
                    <i class="bi bi-envelope"></i>
                    <?php echo vipub_translate("messages"); ?>
                </a>

                <a class="<?php echo ($app == 'bookmarks') ? 'page-active' : ''; ?>" href="<?php echo vipub_link("bookmarks"); ?>">
                    <i class="bi bi-bookmark"></i>
                    <?php echo vipub_translate("bookmarks"); ?>
                </a>

                <a href="#top" id="openedCreatePost">
                    <i class="bi bi-pencil-square"></i>
                    <?php echo vipub_translate("create"); ?>
                </a>

                <?php if($vipub["account"]["admin_status"]=="1"): ?>
                <a href="<?php echo vipub_link("admin_panel"); ?>">
                    <i class="bi bi-sliders"></i>
                    Admin panel
                </a>
                <?php endif; ?>

                <a class="<?php echo ($app == 'profile' || $app == 'media' || $app == 'likes') ? 'page-active' : ''; ?>" href="<?php echo vipub_link("/@".$vipub["account"]["username"]); ?>">
                    <img src="<?php echo vipub_link($vipub["account"]["avatar"]); ?>">
                    <?php echo vipub_translate("profile"); ?>
                </a>
            </div>

            <div class="main-sidebar-menu-fixed-bottom">
                <a href="#" id="sidebarMore">
                    <i class="bi bi-list"></i>
                    <?php echo vipub_translate("more"); ?>
                </a>
            </div>

            <div id="sidebarMoreMenu" class="sidebar-more-menu" style="display: none;">
                <a href="<?php echo vipub_link("bookmarks"); ?>">
                    <i class="bi bi-bookmark"></i>
                    <?php echo vipub_translate("bookmarks"); ?>
                </a>
                <?php if($settings["premium_verified"]=="1"): ?>
                    <a href="<?php echo vipub_link("settings/send_verified"); ?>">
                        <i class="bi bi-patch-check"></i>
                        <?php echo vipub_translate("left_sidebar_premium_account"); ?>
                    </a>
                <?php endif; ?>

                <a href="<?php echo vipub_link("business"); ?>">
                    <i class="bi bi-badge-ad"></i>
                    <?php echo vipub_translate("left_sidebar_business_page"); ?>
                </a>

                <a href="<?php echo vipub_link("business/balance"); ?>">
                    <i class="bi bi-wallet2"></i>
                    <?php echo vipub_translate("left_sidebar_business_page_wallet"); ?>  
                    <span><?php echo vipub_wallet_balance($vipub["account"]["user_wallet"]); ?> $</span>
                </a>

                <hr id="sidebar-border-bottom"/>

                <a href="<?php echo vipub_link("settings"); ?>">
                    <i class="bi bi-gear"></i>
                    <?php echo vipub_translate("mobile_menu_left_sidebar_1"); ?>
                </a>

                <a href="<?php echo vipub_link("pages/help-center"); ?>">
                    <i class="bi bi-patch-question"></i>
                    <?php echo vipub_translate("mobile_menu_left_sidebar_2"); ?>
                </a>

                <a href="<?php echo vipub_link("settings/display"); ?>">
                    <i class="bi bi-pencil-square"></i>
                    <?php echo vipub_translate("mobile_menu_left_sidebar_3"); ?>
                </a>

                <a href="#" id="new-report-a-problem">
                    <i class="bi bi-info-circle"></i>
                    <?php echo vipub_translate("report_a_problem"); ?>
                </a>

                <hr id="sidebar-border-bottom"/>

                <a href="<?php echo vipub_link("logout"); ?>">
                    <i class="bi bi-eye-slash"></i>
                    <?php echo vipub_translate("logout"); ?>
                </a>
            </div>
    </div>
</div>
        

    <div id="report-a-problem">
        <div class="report-title-and-close">
            <h5>
                <?php echo vipub_translate("report_a_problem"); ?>
                <i id="close-dropdown" class="bi bi-x-circle-fill"></i>
            </h5>
        </div>
        <form id="reportProblemForm" method="post">
            <div class="report-a-content-form">
                <textarea name="report_content" id="report_content" placeholder="<?php echo vipub_translate("please_give_as_much_information_as_possible"); ?>"></textarea>
            </div>

            <div class="report-form-buttons">
                <button type="submit" name="submitProblem">
                    <?php echo vipub_translate("submit_a_complaint"); ?>
                </button>

                <span id="add_image">
                    <input type="file" name="add_image" id="add_image" style="display:none;">
                    <?php echo vipub_translate("add_file"); ?>
                </span>
            </div>

            <div class="report-a-reviwed-form-info-text">
                <span><?php echo vipub_translate("report_a_problem_bottom_info_text"); ?></span>
            </div>
        </form>
    </div>

    <script>
        const openDropdownLink = document.getElementById('new-report-a-problem');
        const dropdownContent = document.getElementById('report-a-problem');
        const closeDropdownLink = document.getElementById('close-dropdown');
        openDropdownLink.addEventListener('click', function (event) {
            event.preventDefault();
            dropdownContent.classList.add('active');
            document.body.style.overflow = 'hidden';
        });
        closeDropdownLink.addEventListener('click', function (event) {
            event.preventDefault();
            dropdownContent.classList.remove('active');
            document.body.style.overflow = 'auto';
        });
    </script>
    
    <script>
        $(document).on('click', '[data-vipub-url]', function() {
            var url = $(this).data('vipub-url');
            window.location.href = url;
        });
    </script>
    
    <script>
        $(document).ready(function() {
            function updateNotifications() {
                $.ajax({
                type: "POST",
                url: "/apps/ajax/notifications/notifs-control.phtml",
                dataType: "json",
                success: function(data) {
                    if(data.count > 0) {
                    $("#check-notifs").html(data.count).show();
                    } else {
                    $("#check-notifs").hide();
                    }
                },
                error: function() {
                    $("#check-notifs").hide();
                }
                });
            }
            updateNotifications();
            setInterval(function() {
                updateNotifications();
            }, 2000);
        });
    </script>
    
    <script>
        $(document).ready(function() {
            function updateNotifications() {
                $.ajax({
                type: "POST",
                url: "/apps/ajax/messages/notifs-messages.phtml",
                dataType: "json",
                success: function(data) {
                    if(data.count > 0) {
                    $("#check-message").html(data.count).show();
                    } else {
                    $("#check-message").hide();
                    }
                },
                error: function() {
                    $("#check-message").hide();
                }
                });
            }
            updateNotifications();
            setInterval(function() {
                updateNotifications();
            }, 2000);
        });
    </script>

<script>
    function moreDropdown(event) {
        var moreSidebarContent = document.getElementById("moreSidebarContent");
        if (moreSidebarContent.style.display === "none") {
            moreSidebarContent.style.display = "block";
            document.addEventListener("click", closeMoreDropdown);
        } else {
            moreSidebarContent.style.display = "none";
            document.removeEventListener("click", closeMoreDropdown);
        }
        event.stopPropagation();
        }
        function closeMoreDropdown(event) {
        var moreSidebarContent = document.getElementById("moreSidebarContent");
        if (!moreSidebarContent.contains(event.target)) {
            moreSidebarContent.style.display = "none";
            document.removeEventListener("click", closeMoreDropdown);
        }
    }
</script>
    
    <?php else: ?>
        <?php vipub_template("main/sidebar/left-guest"); ?>
<?php endif; ?>
<script>
    $(document).ready(function() {
        var sidebarMoreLink = $("#sidebarMore");
        var sidebarMoreMenu = $("#sidebarMoreMenu");

        sidebarMoreLink.on("click", function(event) {
            event.preventDefault();
            
            sidebarMoreMenu.toggle();
        });

        $(document).on("click", function(event) {
            var target = $(event.target);

            // Eğer tıklanan element sidebarMoreLink veya sidebarMoreMenu içinde ise kapatma işlemini yapma
            if (!target.is(sidebarMoreLink) && !target.is(sidebarMoreMenu) && sidebarMoreMenu.is(":visible")) {
            sidebarMoreMenu.hide();
            }
        });
    });
</script>

<script>
    document.getElementById("openedCreatePost").addEventListener("click", function(event) {
        event.preventDefault();

        var createFormContainer = document.getElementById("createFormContainer");

        if (createFormContainer.style.display === "none") {
            createFormContainer.style.display = "block";
        } else {
            createFormContainer.style.display = "none";
        }
    });
</script>