<?php if(isset($_SESSION["user_id"])): ?>
<div class="col-md-3">
    <div class="right-sidebar">
        <div class="search-container">
            <i class="bi bi-search"></i>
            <input type="text" placeholder="<?php echo xclone_translate("search_xclone"); ?>">
            <div class="search-results"></div>
        </div>
        <div class="main-right-sidebar-fluid">
            <div class="sidebar-card-boxing">
                <div class="right-sidebar-title-content">
                    <h5><?php echo xclone_translate("trending_hot_title"); ?></h5>
                </div>
                <div id="rsbr-htag-algoritmic"></div>
            </div>

            <div class="sidebar-card-boxing">
                <div class="right-sidebar-title-content">
                    <h5>
                        <?php echo xclone_translate("who_to_follow_title"); ?>
                        <span data-xclone-url="<?php echo xclone_link("connect_people"); ?>">
                            <?php echo xclone_translate("right_sidebar_title_flex_right_span"); ?>
                        </span>
                    </h5>
                    
                </div>
                <div id="rsbr-tofollow-algoritmic"></div>
            </div>

            <div class="sidebar-footer-content">
                <?php xclone_rightsidebar_footer(); ?>
            </div>
        </div>
    </div>
</div>
<?php else: ?>
    <?php xclone_template("main/sidebar/right-guest"); ?>
<?php endif; ?>