<?php $settings = vipub_site_settings(); vipub_template("main/sidebar/messages/left-sidebar");?>
<div class="col-md-6">
    <div class="main-vipub-screenline container-absolute-message-page">
        
        <div class="vipub-user-message-container">
            <div id="chat-container">
                <div id="message-container"></div>
            </div>
        </div>

        <div id="image_preview" style="display:none;">
          <span class="remove_selection_image" onclick="removeMessagePicture()">
            <i class="bi bi-x-circle"></i>
          </span>
          <img id="preview_image" src="#">
        </div>

        <div class="chat-container-new-message">
            <form id="message-form" enctype="multipart/form-data">
              <small class="select-emoji-chat-btn"><i class="bi bi-emoji-smile"></i></small>
              <div contenteditable="true" id="message-input" class="textarea-like"></div>
              
              <div class="chat-form-right-zero-btn">
                <span id="add_image" onclick="openInput()">
                  <i class="bi bi-card-image"></i>
                  <input type="file" name="content_image" id="view_image" style="display:none;"  onchange="handleFileSelect(event)" accept=".jpg, .jpeg, .png, .gif">
                </span>
                <button type="submit">
                  <i class="bi bi-arrow-right-circle-fill"></i>
                </button>
              </div>
            </form>
        </div>
        <?php vipub_template("timeline/script/vipub-emojies"); ?>
    </div>
</div>


<script>
  var lastSubmitTime = 0;

  function sendMessage(message, receiver_id) {
    var submitBtn = $('button[type="submit"]');
    submitBtn.prop('disabled', true);

    if (!message.trim()) {
      var vipubSM_msgIcon = '<i class="bi bi-x-circle-fill"></i>';
      var vipubSM_msgText = '<?php echo vipub_translate("trim_no_message_1"); ?>';
      var vipubSM_alertTimeout = 5000;
      vipubSM.showAlert(vipubSM_msgIcon, vipubSM_msgText, vipubSM_alertTimeout);
      submitBtn.prop('disabled', false);
      return;
    }

    var now = new Date().getTime();
    var elapsedTime = now - lastSubmitTime;
    if (elapsedTime < 300) {
      new Noty({
        type: 'error',
        text: 'Please wait a moment before submitting again.',
        timeout: 1500
      }).show();
      submitBtn.prop('disabled', false);
      return;
    }

    lastSubmitTime = now;

    var formData = new FormData();
    formData.append('message', message);
    formData.append('receiver_id', receiver_id);
    formData.append('content_image', $('#view_image')[0].files[0]);

    $.ajax({
      url: '/apps/ajax/messages/send-message.phtml',
      type: 'POST',
      data: formData, 
      contentType: false,
      processData: false,
      success: function(response) {
        $('#message-input').empty();
        var imageUrl = response.image_url;
        if (imageUrl) {
          $('#image_preview').attr('src', imageUrl);
          $('#image_preview').show();
        } else {
          $('#image_preview').hide();
        }

        submitBtn.prop('disabled', false);
      },
      error: function() {
        alert('<?php echo vipub_translate("trim_no_message_3"); ?>');
        submitBtn.prop('disabled', false);
      }
    });
  }

  function checkMessages(receiver_id) {
    $.ajax({
      url: '/apps/ajax/messages/check-messages.phtml?row=<?php echo $_GET['row']; ?>',
      type: 'GET',
      data: { receiver_id: receiver_id },
      dataType: 'html',
      success: function(response) {
        var container = $('.vipub-user-message-container');
        var scrollHeightBefore = container.prop('scrollHeight');
        container.html(response);

        var scrollHeightAfter = container.prop('scrollHeight');
        var isScrolledToBottom = container.scrollTop() + container.outerHeight() >= scrollHeightBefore - 20;

        if (isScrolledToBottom) {
          container.scrollTop(scrollHeightAfter);
        }
      },
      error: function() {
        alert('Your messages list has not been loaded yet.');
      }
    });
  }

  $(document).ready(function() {
    var receiver_id = <?php echo $_GET['row']; ?>;

    if (receiver_id == <?php echo $_SESSION['user_id']; ?>) {
    } else {
      checkMessages(receiver_id);
      setInterval(function() {
        checkMessages(receiver_id);
      }, <?php echo $settings["chat_time_interval"]; ?>);
    }
  });

  // Enter tuşuyla mesaj gönderme
  $('#message-input').keypress(function(event) {
    if (event.which === 13 && !event.shiftKey) {
      event.preventDefault();
      var message = $('#message-input').text().trim();
      var receiver_id = <?php echo $_GET['row']; ?>;

      if (message === '') {
        var vipubSM_msgIcon = '<i class="bi bi-x-circle-fill"></i>';
        var vipubSM_msgText = '<?php echo vipub_translate("trim_no_message_3"); ?>';
        var vipubSM_alertTimeout = 5000;
        vipubSM.showAlert(vipubSM_msgIcon, vipubSM_msgText, vipubSM_alertTimeout);
        return;
      }

      if (receiver_id == <?php echo $_SESSION['user_id']; ?>) {
        window.location.href = '<?php echo vipub_link("messages"); ?>';
      } else {
        sendMessage(message, receiver_id);
      }
    }
  });

  $('#message-form').submit(function(event) {
    event.preventDefault();
    var message = $('#message-input').text().trim();
    var receiver_id = <?php echo $_GET['row']; ?>;

    if (message === '') {
      var vipubSM_msgIcon = '<i class="bi bi-x-circle-fill"></i>';
      var vipubSM_msgText = '<?php echo vipub_translate("trim_no_message_3"); ?>';
      var vipubSM_alertTimeout = 5000;
      vipubSM.showAlert(vipubSM_msgIcon, vipubSM_msgText, vipubSM_alertTimeout);

      submitBtn.prop('disabled', false);
      return;
    }

    if (receiver_id == <?php echo $_SESSION['user_id']; ?>) {
      window.location.href = '<?php echo vipub_link("messages"); ?>';
    } else {
      sendMessage(message, receiver_id);
    }
  });
  
</script>

<script>
  function openInput() {
    const inputElement = document.getElementById("view_image");
    inputElement.click();
  }

  function handleFileSelect(event) {
    const file = event.target.files[0];
    if (!file) {
      const imagePreview = document.getElementById("image_preview");
      imagePreview.style.display = "none";

      const inputElement = document.getElementById("view_image");
      inputElement.style.display = "none";
      return;
    }
    const reader = new FileReader();

    reader.onload = function(event) {
      const previewImage = document.getElementById("preview_image");
      previewImage.src = event.target.result;
    };
    reader.readAsDataURL(file);
    const imagePreview = document.getElementById("image_preview");
    imagePreview.style.display = "block";
  }
</script>

<script>
  function removeMessagePicture() {
    document.getElementById('preview_image').src = "#";
    document.getElementById('view_image').value = "";
    document.getElementById('image_preview').style.display = 'none';
  }
</script>


<script>
  document.querySelector('.select-emoji-chat-btn').addEventListener('click', function() {
    const emojiPicker = document.getElementById('emoji-picker');
    emojiPicker.style.display = emojiPicker.style.display === 'none' ? 'block' : 'none';
  });

  document.querySelectorAll('.emoji').forEach(function(emojiButton) {
    emojiButton.addEventListener('click', function() {
      const emoji = this.textContent;
      const messageInput = document.getElementById('message-input');
      messageInput.innerHTML += emoji;
    });
  });

  document.getElementById('message-form').addEventListener('submit', function(e) {
    e.preventDefault();
  });

  function hideEmojiPicker() {
    document.getElementById('emoji-picker').style.display = 'none';
  }
</script>

<?php vipub_template("main/sidebar/right-sidebar"); ?>
<style>body{overflow:hidden;}</style>