<?php $conn = vipubConnectDatabase(); $token = $_GET["token"]; $sql = "SELECT * FROM vipub_users WHERE reset_token='$token'"; $result = mysqli_query($conn, $sql); if (mysqli_num_rows($result) == 1) { $row = mysqli_fetch_assoc($result); ?>
<div class="welcome-page-container">
    <div class="left-section">
        <div class="site-welcome-logo">
            <img src="<?php echo vipub_template_master("images/logo_white.png"); ?>">
        </div>
    </div>

    <div class="right-section">
        <div class="user-form-value-content">
            <div class="title">
                <a href="<?php echo vipub_link("welcome/login"); ?>">
                    <img src="<?php echo vipub_template_master("images/logo.png"); ?>">
                </a>
                <h5><?php echo vipub_translate("user_new_password_page_1"); ?></h5>
                <span><?php echo vipub_translate("user_new_password_page_2"); ?></span>
            </div>
            
            <div class="user-form-container">
                <form id="user-new-password-save">
                    <div class="form-floating mb-4">
                        <input type="text" class="form-control" id="password" name="password" placeholder="<?php echo vipub_translate("welcome_page_text_4"); ?>" required>
                        <label for="password"><?php echo vipub_translate("welcome_page_text_4"); ?></label>
                    </div>

                    <div class="forget-your-password">
                        <a href="<?php echo vipub_link("welcome/login"); ?>"><?php echo vipub_translate("user_new_password_page_3"); ?></a>
                    </div>

                    <div class="form-submit-content">
                        <button type="submit" id="save-password-btn"><?php echo vipub_translate("account_settings_menu_27"); ?></button>
                    </div>
                </form>

                <div class="user-form-tho-select">
                    <span><?php echo vipub_translate("welcome_page_text_7"); ?></span>
                </div>


                <div class="user-form-footer">
                    <a href="<?php echo vipub_link("pages/about"); ?>"><?php echo vipub_translate("welcome_footer_1"); ?></a>
                    <a href="<?php echo vipub_link("pages/privacy-policy"); ?>"><?php echo vipub_translate("welcome_footer_2"); ?></a>
                    <a href="<?php echo vipub_link("pages/terms-policy"); ?>"><?php echo vipub_translate("welcome_footer_3"); ?></a>
                    <a href="<?php echo vipub_link("pages/help-center"); ?>"><?php echo vipub_translate("welcome_footer_4"); ?></a>

                    <a href="#" class="site-language-select dropdown-toggle"><?php echo vipub_translate("language_name"); ?></a>
                    <ul class="welcome-dropdown-menu">
                        <li><a href="<?php echo vipub_link("language/turkish"); ?>"><?php echo vipub_translate("language_name_1"); ?></a></li>
                        <li><a href="<?php echo vipub_link("language/english"); ?>"><?php echo vipub_translate("language_name_2"); ?></a></li>
                        <li><a href="<?php echo vipub_link("language/espanol"); ?>"><?php echo vipub_translate("language_name_3"); ?></a></li>
                        <li><a href="<?php echo vipub_link("language/german"); ?>"><?php echo vipub_translate("language_name_4"); ?></a></li>
                        <li><a href="<?php echo vipub_link("language/russian"); ?>"><?php echo vipub_translate("language_name_5"); ?></a></li>
                    </ul>
                </div>


            </div>
            
        </div>
    </div>
</div>


<script>
  $(document).ready(function() {
    $('#password').on('input', function() {
      if ($(this).val().length > 0) {
        $('#save-password-btn').prop('disabled', false);
      } else {
        $('#save-password-btn').prop('disabled', true);
      }
    });

    // formu submit işlemi yapar
    $('#user-new-password-save').on('submit', function(e) {
      e.preventDefault();
      $('#save-password-btn').html('<?php echo vipub_translate("welcome_page_login_6"); ?>').prop('disabled', true);

      var password = $('#password').val();

      $.ajax({
        url: '/apps/ajax/auth/new_password.phtml?user=<?php echo $row["id"]; ?>',
        type: 'post',
        data: {
          password: password
        },
        success: function(response) {
          toastr.success('<?php echo vipub_translate("settings_page_save_value_desc_16"); ?>');
          setTimeout(function() {
            window.location.href = '/welcome/login';
          }, 1500);
        },
        error: function(xhr, status, error) {
          toastr.error('Bir hata oluştu!');
          $('#save-password-btn').html('<?php echo vipub_translate("account_settings_menu_27"); ?>').prop('disabled', false);
        }
      });
    });
  });
</script>
<?php } else { header("Location: /404"); exit(); }