<div class="welcome-page-container">
    <div class="left-section">
        <div class="site-welcome-logo">
            <img src="<?php echo vipub_template_master("images/logo_white.png"); ?>">
        </div>
    </div>

    <div class="right-section">
        <div class="user-form-value-content">
            <div class="title">
                <a href="<?php echo vipub_link("welcome/login"); ?>">
                    <img src="<?php echo vipub_template_master("images/logo.png"); ?>">
                </a>
                <h5><?php echo vipub_translate("yes_password_refresh_not_page_to_login_page_1"); ?></h5>
                <span><?php echo vipub_translate("yes_password_refresh_not_page_to_login_page_2"); ?></span>
            </div>
            
            <div class="user-form-container">
                <form id="account-refresh-password">
                    <div class="form-floating mb-4">
                        <input type="text" class="form-control" id="email" name="email" placeholder="<?php echo vipub_translate("welcome_page_text_12"); ?>">
                        <label for="email"><?php echo vipub_translate("welcome_page_text_12"); ?></label>
                    </div>

                    <div class="forget-your-password">
                        <a href="<?php echo vipub_link("welcome/login"); ?>"><?php echo vipub_translate("yes_password_refresh_not_page_to_login_page"); ?></a>
                    </div>

                    <div class="form-submit-content">
                        <button type="submit" id="refresh-password-btn"><?php echo vipub_translate("yes_password_refresh_not_page_to_login_page_3"); ?></button>
                    </div>
                </form>

                <div class="user-form-tho-select">
                    <span><?php echo vipub_translate("welcome_page_text_7"); ?></span>
                </div>


                <div class="user-form-footer">
                    <a href="<?php echo vipub_link("pages/about"); ?>"><?php echo vipub_translate("welcome_footer_1"); ?></a>
                    <a href="<?php echo vipub_link("pages/privacy-policy"); ?>"><?php echo vipub_translate("welcome_footer_2"); ?></a>
                    <a href="<?php echo vipub_link("pages/terms-policy"); ?>"><?php echo vipub_translate("welcome_footer_3"); ?></a>
                    <a href="<?php echo vipub_link("pages/help-center"); ?>"><?php echo vipub_translate("welcome_footer_4"); ?></a>

                    <a href="#" class="site-language-select dropdown-toggle"><?php echo vipub_translate("language_name"); ?></a>
                    <ul class="welcome-dropdown-menu">
                        <li><a href="<?php echo vipub_link("language/turkish"); ?>"><?php echo vipub_translate("language_name_1"); ?></a></li>
                        <li><a href="<?php echo vipub_link("language/english"); ?>"><?php echo vipub_translate("language_name_2"); ?></a></li>
                        <li><a href="<?php echo vipub_link("language/espanol"); ?>"><?php echo vipub_translate("language_name_3"); ?></a></li>
                        <li><a href="<?php echo vipub_link("language/german"); ?>"><?php echo vipub_translate("language_name_4"); ?></a></li>
                        <li><a href="<?php echo vipub_link("language/russian"); ?>"><?php echo vipub_translate("language_name_5"); ?></a></li>
                    </ul>
                </div>


            </div>
            
        </div>


    </div>
</div>


<script>
    $(document).ready(function() {
        $('#refresh-password-btn').attr('disabled', true);

        $('#email').on('input', function() {
            var email = $('#email').val().trim();
            if (email !== '') {
                $('#refresh-password-btn').attr('disabled', false);
            } else {
                $('#refresh-password-btn').attr('disabled', true);
            }
        });

        $('#account-refresh-password').submit(function(event) {
            event.preventDefault();
            var email = $('#email').val().trim();
            if (email !== '') {
                $('#refresh-password-btn').html('<?php echo vipub_translate("yes_password_refresh_not_page_to_login_page_4"); ?>').attr('disabled', true);

                $.ajax({
                    url: '/apps/ajax/auth/reset_password.phtml',
                    method: 'POST',
                    data: {
                        email: email
                    },
                    success: function(data) {
                        console.log(data);
                        if (data === 'success') {
                            $('#refresh-password-btn').html('<?php echo vipub_translate("yes_password_refresh_not_page_to_login_page_5"); ?>').attr('disabled', true);
                            toastr.success('<?php echo vipub_translate("yes_password_refresh_not_page_to_login_page_6"); ?>');
                        } else if (data === 'not_found') {
                            $('#refresh-password-btn').html('<?php echo vipub_translate("yes_password_refresh_not_page_to_login_page_3"); ?>').attr('disabled', false);
                            toastr.error('<?php echo vipub_translate("yes_password_refresh_not_page_to_login_page_7"); ?>');
                        } else {
                            $('#refresh-password-btn').html('<?php echo vipub_translate("yes_password_refresh_not_page_to_login_page_3"); ?>').attr('disabled', false);
                            toastr.error('<?php echo vipub_translate("welcome_page_login_5"); ?>');
                        }
                    },
                    error: function(jqXHR, textStatus, errorThrown){
                        $('#refresh-password-btn').html('<?php echo vipub_translate("yes_password_refresh_not_page_to_login_page_3"); ?>').attr('disabled', false);
                        toastr.error('<?php echo vipub_translate("welcome_page_login_5"); ?>');
                        console.log(textStatus + ': ' + errorThrown);
                    }
                });
            } else {
                toastr.warning('Kullanıcı adı veya e-posta adresi gerekli.');
            }
        });
    });
</script>

<?php vipub_template("auth/script/vipub.master.script"); ?>