<?php $settings = xclone_site_settings(); ?>
<div class="welcome-page-container">
    <div class="left-section">
        <div class="site-welcome-logo">
            <img src="<?php echo xclone_template_master("images/logo_white.png"); ?>">
        </div>
    </div>
    <div class="right-section">
        <div class="user-form-value-content">
            <div class="title" id="title-mb">
                <a href="<?php echo xclone_link("welcome/login"); ?>">
                    <img src="<?php echo xclone_template_master("images/logo.png"); ?>">
                </a>
                <h5><?php echo xclone_translate("welcome_page_text_8"); ?></h5>
                <span id="nonedp"><?php echo xclone_translate("welcome_page_text_9"); ?></span>
            </div>
            
            <div class="user-form-container">
                <?php if($settings["site_register_status"]=="0"): ?>
                <form id="register-form">
                     <div class="form-floating mb-4">
                        <input type="text" class="form-control" id="fullname" name="fullname" placeholder="<?php echo xclone_translate("welcome_page_text_10"); ?>">
                        <label for="fullname"><?php echo xclone_translate("welcome_page_text_10"); ?></label>
                    </div>

                    <div class="form-floating mb-4">
                        <input type="text" class="form-control" id="username" name="username" placeholder="<?php echo xclone_translate("welcome_page_text_11"); ?>">
                        <label for="username"><?php echo xclone_translate("welcome_page_text_11"); ?></label>
                    </div>

                    <div class="form-floating mb-4">
                        <input type="email" class="form-control" id="email" name="email" placeholder="<?php echo xclone_translate("welcome_page_text_12"); ?>">
                        <label for="email"><?php echo xclone_translate("welcome_page_text_12"); ?></label>
                    </div>

                    <div class="form-floating mb-4">
                        <input type="password" class="form-control" id="password" name="password" placeholder="<?php echo xclone_translate("welcome_page_text_13"); ?>">
                        <label for="password"><?php echo xclone_translate("welcome_page_text_13"); ?></label>
                    </div>
                    
                    <div class="forget-your-password">
                        <span><?php echo xclone_translate("welcome_page_text_14"); ?></span>
                    </div>

                    <div class="form-submit-content">
                        <button type="submit"><?php echo xclone_translate("welcome_page_text_15"); ?></button>
                    </div>
                </form>
                <?php else: ?>
                    <?php xclone_template("auth/include/not-register"); ?>
                <?php endif; ?>

                <div class="user-form-tho-select">
                    <span><?php echo xclone_translate("welcome_page_text_16"); ?></span>
                </div>

                <div class="user-form-footer">
                    <a href="<?php echo xclone_link("pages/about"); ?>"><?php echo xclone_translate("welcome_footer_1"); ?></a>
                    <a href="<?php echo xclone_link("pages/privacy-policy"); ?>"><?php echo xclone_translate("welcome_footer_2"); ?></a>
                    <a href="<?php echo xclone_link("pages/terms-policy"); ?>"><?php echo xclone_translate("welcome_footer_3"); ?></a>
                    <a href="<?php echo xclone_link("pages/help-center"); ?>"><?php echo xclone_translate("welcome_footer_4"); ?></a>

                    <a href="#" class="site-language-select dropdown-toggle"><?php echo xclone_translate("language_name"); ?></a>
                    <ul class="welcome-dropdown-menu">
                        <li><a href="<?php echo xclone_link("language/turkish"); ?>"><?php echo xclone_translate("language_name_1"); ?></a></li>
                        <li><a href="<?php echo xclone_link("language/english"); ?>"><?php echo xclone_translate("language_name_2"); ?></a></li>
                        <li><a href="<?php echo xclone_link("language/espanol"); ?>"><?php echo xclone_translate("language_name_3"); ?></a></li>
                        <li><a href="<?php echo xclone_link("language/german"); ?>"><?php echo xclone_translate("language_name_4"); ?></a></li>
                        <li><a href="<?php echo xclone_link("language/russian"); ?>"><?php echo xclone_translate("language_name_5"); ?></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<?php xclone_template("auth/script/xclone.master.script"); ?>