<link href="<?php echo xclone_template_master("style/welcome/welcome.css"); ?>?csy=<?php echo rand(5435, 12312345235); ?>" rel="stylesheet">
<?php $settings = xclone_site_settings(); $xclone_oauth = xclone_oauth_settings(); ?>

<div class="welcome-to-website-container">
    <div class="welcome-page-form-container">
    
        <div class="container-welcome-form-content">
            <div class="genel-page-title" data-xclone-user-url="<?php echo xclone_link("welcome/login"); ?>">
                <img src="<?php echo xclone_template_master("images/logo.png"); ?>" alt="">
            </div>

            <form id="login-form">
                <div class="form-content-for-user">
                    <input type="text" name="username" id="username" placeholder="<?php echo xclone_translate("welcome_page_text_3"); ?>">
                </div>

                <div class="form-content-for-user">
                    <input type="password" name="password" id="password" placeholder="<?php echo xclone_translate("welcome_page_text_4"); ?>">
                </div>

                <div class="form-content-for-user">
                    <a href="<?php echo xclone_link("welcome/refresh_password"); ?>">
                        <?php echo xclone_translate("welcome_page_text_5"); ?>
                    </a>
                </div>

                <div class="form-content-for-user border-color-class">
                    <button type="submit" id="login-button" class="btn">
                        <?php echo xclone_translate("welcome_page_text_6"); ?>
                    </button>
                </div>

                <div class="form-content-for-user">
                    <?php if($xclone_oauth["twitter_login_status"]=="0"): ?>
                    <h5>
                        <a href="<?php echo xclone_link("oauth/twitter"); ?>">
                            <svg viewBox="0 0 24 24" aria-hidden="true"><g><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"></path></g></svg>
                            <?php echo xclone_translate("xclone_twitter_for_oauth_login"); ?>
                        </a>
                    </h5>
                    <?php endif; ?>
                </div>

                <div class="form-content-for-user-bottom-border">
                    <small><?php echo xclone_translate("welcome_page_text_7"); ?></small>
                </div>

                <select class="welcome-dropdown-menu">
                    <option select><?php echo xclone_translate("language_name"); ?></option>
                    <option value="turkish"><?php echo xclone_translate("language_name_1"); ?></option>
                    <option value="english"><?php echo xclone_translate("language_name_2"); ?></option>
                    <option value="espanol"><?php echo xclone_translate("language_name_3"); ?></option>
                    <option value="german"><?php echo xclone_translate("language_name_4"); ?></option>
                    <option value="russian"><?php echo xclone_translate("language_name_5"); ?></option>
                    <option value="portuguese"><?php echo xclone_translate("language_name_6"); ?></option>
                    <option value="french"><?php echo xclone_translate("language_name_7"); ?></option>
                    <option value="chinese"><?php echo xclone_translate("language_name_8"); ?></option>
                    <option value="hindi"><?php echo xclone_translate("language_name_9"); ?></option>
                    <option value="japanese"><?php echo xclone_translate("language_name_10"); ?></option>
                    <option value="bengali"><?php echo xclone_translate("language_name_11"); ?></option>
                </select>
            </form>
        </div>
    </div>
</div>

<div class="welcome-page-footer-bottom">
    <div class="page-footer-bottom">
        <a href="<?php echo xclone_link("pages/about"); ?>"><?php echo xclone_translate("welcome_footer_1"); ?></a>
        <a href="<?php echo xclone_link("pages/privacy-policy"); ?>"><?php echo xclone_translate("welcome_footer_2"); ?></a>
        <a href="<?php echo xclone_link("pages/terms-policy"); ?>"><?php echo xclone_translate("welcome_footer_3"); ?></a>
        <a href="<?php echo xclone_link("pages/cookies-policy"); ?>"><?php echo xclone_translate("welcome_footer_5"); ?></a>
        <a href="<?php echo xclone_link("pages/help-center"); ?>"><?php echo xclone_translate("welcome_footer_4"); ?></a>
        
        <a href="#" class="site-language-select dropdown-toggle"><?php echo xclone_translate("language_name"); ?></a>
        <a style="cursor: default; user-select:none; text-decoration: none !important;" href="#">© <strong><?php echo $settings["site_name"]; ?> · <?php echo date("Y"); ?></strong></a>
    </div>
</div>

<?php xclone_template("auth/script/xclone.master.script"); ?>
<script>
    $(document).on('click', '[data-xclone-user-url]', function() {
        var url = $(this).data('xclone-user-url');
        window.location.href = url;
    });
</script>