<link href="<?php echo vipub_template_master("style/welcome/welcome.css"); ?>?csy=<?php echo rand(5435, 12312345235); ?>" rel="stylesheet">
<?php $settings = vipub_site_settings();?>

<div class="welcome-to-website-container">
    <div class="welcome-page-form-container">
        <div class="container-welcome-form-content">
            <div class="genel-page-title" data-vipub-user-url="<?php echo vipub_link("welcome/login"); ?>">
                <img src="<?php echo vipub_template_master("images/logo.png"); ?>" alt="">
            </div>
            <form id="register-form">
                <?php if($settings["site_register_status"]=="1"): ?>
                    <div class="form-content-for-user">
                        <input type="text" name="fullname" id="fullname" placeholder="<?php echo vipub_translate("welcome_page_text_10"); ?>">
                    </div>

                    <div class="form-content-for-user">
                        <input type="text" name="username" id="username" placeholder="<?php echo vipub_translate("welcome_page_text_11"); ?>">
                    </div>

                    <div class="form-content-for-user">
                        <input required type="email" name="email" id="email" placeholder="<?php echo vipub_translate("welcome_page_text_12"); ?>">
                    </div>

                    <div class="form-content-for-user">
                        <input type="password" name="password" id="password" placeholder="<?php echo vipub_translate("welcome_page_text_4"); ?>">
                    </div>

                    <div class="form-content-for-user border-color-class">
                        <button type="submit" id="register-button" class="btn">
                            <?php echo vipub_translate("welcome_page_text_15"); ?>
                        </button>
                    </div>

                    <div class="form-content-for-user-bottom-border">
                        <small><?php echo vipub_translate("welcome_page_text_16"); ?></small>
                    </div>

                <?php else: ?>
                    <?php vipub_template("auth/include/not-register"); ?>
                <?php endif; ?>

                <select class="welcome-dropdown-menu">
                    <option select><?php echo vipub_translate("language_name"); ?></option>
                    <option value="turkish"><?php echo vipub_translate("language_name_1"); ?></option>
                    <option value="english"><?php echo vipub_translate("language_name_2"); ?></option>
                    <option value="espanol"><?php echo vipub_translate("language_name_3"); ?></option>
                    <option value="german"><?php echo vipub_translate("language_name_4"); ?></option>
                    <option value="russian"><?php echo vipub_translate("language_name_5"); ?></option>
                    <option value="portuguese"><?php echo vipub_translate("language_name_6"); ?></option>
                    <option value="french"><?php echo vipub_translate("language_name_7"); ?></option>
                    <option value="chinese"><?php echo vipub_translate("language_name_8"); ?></option>
                    <option value="hindi"><?php echo vipub_translate("language_name_9"); ?></option>
                    <option value="japanese"><?php echo vipub_translate("language_name_10"); ?></option>
                    <option value="bengali"><?php echo vipub_translate("language_name_11"); ?></option>
                </select>
            </form>
        </div>
    </div>
</div>

<div class="welcome-page-footer-bottom">
    <div class="page-footer-bottom">
        <a href="<?php echo vipub_link("pages/about"); ?>"><?php echo vipub_translate("welcome_footer_1"); ?></a>
        <a href="<?php echo vipub_link("pages/privacy-policy"); ?>"><?php echo vipub_translate("welcome_footer_2"); ?></a>
        <a href="<?php echo vipub_link("pages/terms-policy"); ?>"><?php echo vipub_translate("welcome_footer_3"); ?></a>
        <a href="<?php echo vipub_link("pages/cookies-policy"); ?>"><?php echo vipub_translate("welcome_footer_5"); ?></a>
        <a href="<?php echo vipub_link("pages/help-center"); ?>"><?php echo vipub_translate("welcome_footer_4"); ?></a>
        
        <a href="#" class="site-language-select dropdown-toggle"><?php echo vipub_translate("language_name"); ?></a>
        <a style="cursor: default; user-select:none; text-decoration: none !important;" href="#">© <strong><?php echo $settings["site_name"]; ?> · <?php echo date("Y"); ?></strong></a>
    </div>
</div>

<?php vipub_template("auth/script/vipub.master.script"); ?>
<script>
    $(document).on('click', '[data-vipub-user-url]', function() {
        var url = $(this).data('vipub-user-url');
        window.location.href = url;
    });
</script>