<div id="profile-media-timeline"></div>
<script>
    $(document).ready(function() {
        function fetchPosts() {
                $.ajax({
                    url: '/apps/ajax/profile/media-timeline.phtml?uname=<?php echo $row["id"]; ?>',
                    type: 'GET',
                    success: function(data) {
                        $('#profile-media-timeline').html(data);
                    }
                });
            }
            fetchPosts();
    });
</script>