<?php
require_once("../../../core/xclone_web_core.phtml");

if (!isset($_SESSION["user_id"]) || !is_numeric($_SESSION["user_id"])) {
  header("Location: /welcome/login");
  exit;
}

$receiver_id = $_GET['row'];
$sender_id = $_SESSION["user_id"];

if (!is_numeric($receiver_id) || $receiver_id == $sender_id) {
  header("Location: /messages");
  exit;
}

// Prepared statement kullanarak sorguyu hazırla
$updateSql = "UPDATE xclone_messages SET notifs_status = 1 WHERE receiver_id = ? AND sender_id = ?";
$stmt = mysqli_prepare($conn, $updateSql);
mysqli_stmt_bind_param($stmt, "ii", $sender_id, $receiver_id,);
mysqli_stmt_execute($stmt);

// Verileri alırken prepared statement kullan
$selectSql = "SELECT xclone_messages.*, xclone_users.* FROM xclone_messages JOIN xclone_users ON xclone_messages.sender_id = xclone_users.id WHERE (xclone_messages.receiver_id IN (?, ?) AND xclone_messages.sender_id IN (?, ?)) ORDER BY xclone_messages.created_at ASC";
$stmt = mysqli_prepare($conn, $selectSql);
mysqli_stmt_bind_param($stmt, "iiii", $receiver_id, $sender_id, $receiver_id, $sender_id);
mysqli_stmt_execute($stmt);
$result = mysqli_stmt_get_result($stmt);

// Mesajları gösteren HTML dosyasını çağırın
if (mysqli_num_rows($result) > 0) {
  require_once('../../../themes/default/apps/messages/include/chats.phtml');
} else {
  require_once('../../../themes/default/apps/messages/pages/no-message.phtml');
}
