<?php
require_once("../../../core/vipub_web_core.phtml");
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
$smtp_settings = vipub_smtp();

if (!isset($_SESSION["user_id"])) {
  header("Location: /welcome");
  exit;
}

if ($receiver_id == $_SESSION["user_id"]) {
  header("Location: /messages");
  exit;
}
$settings = vipub_site_settings();
$message = trim($_POST['message']);
$message = htmlspecialchars_decode(strip_tags(trim($_POST['message'])), ENT_QUOTES);

$sender_id = $_SESSION['user_id'];
$receiver_id = filter_input(INPUT_POST, 'receiver_id', FILTER_SANITIZE_NUMBER_INT);
if ($sender_id == $receiver_id) {
    die(header('Location: /messages'));
}

$query = "INSERT INTO vipub_messages (sender_id, receiver_id, message) VALUES (?, ?, ?)";
$stmt = $conn->prepare($query);
$stmt->bind_param('iis', $sender_id, $receiver_id, $message);
$stmt->execute();

$email_send_notifs = "SELECT * FROM vipub_users WHERE id = '$receiver_id'";
$send_user_email_notifications = mysqli_query($conn, $email_send_notifs);
$receiver_user = mysqli_fetch_assoc($send_user_email_notifications);

$email_send_notifs2 = "SELECT * FROM vipub_users WHERE id = '$sender_id'";
$send_user_email_notifications2 = mysqli_query($conn, $email_send_notifs2);
$sender_user = mysqli_fetch_assoc($send_user_email_notifications2);

if($settings["email_notifications"]=="Active"){
  if($receiver_user["dm_notification"]=="Active"){
    ob_start();
    require_once("../../../themes/default/apps/content_email/email.notifications.phtml");
    $body = ob_get_clean();
    $body = str_replace(array('<?', '?>'), array('&lt;?', '?&gt;'), $body);
    
    $mail = new PHPMailer(true);
    try {
      $mail->isSMTP();                                            
      $mail->Host       = $smtp_settings["smtp_host"];                     
      $mail->SMTPAuth   = true;                                   
      $mail->Username   = $smtp_settings["smtp_username"];                 
      $mail->Password   = $smtp_settings["smtp_password"];                        
      $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;        
      $mail->Port       = $smtp_settings["smtp_port"];                                    
      $mail->setFrom($smtp_settings["smtp_username"], $settings["site_name"]);
      $mail->addAddress($receiver_user["email"], $receiver_user["fullname"]);
      $mail->isHTML(true);
      $mail->CharSet = 'UTF-8'; 
      $mail->Subject = vipub_translate("email_message_notifications_6");
      $mail->Body = $body;
      $mail->send();
    } 
    catch (Exception $e) {
      echo "error";
    }
  }
}