<?php
require_once("../../../core/xclone_web_core.phtml");

if (!isset($_SESSION["user_id"])) {
  header("Location: /welcome"); 
  exit;
}
$reply_post_id = $_POST['post_id'];
$content = mysqli_real_escape_string($conn, $_POST['content']);
$userId = $_SESSION['user_id'];
$p_data_lang = xclone_user_acceptLanguage();
saveHashtags($conn, $content);

$query = "INSERT INTO xclone_posts (reply_post_id, user_id, content_post, content_image, post_type, post_lang) VALUES ('$reply_post_id', '$userId', '$content', NULL, 'reply', '$p_data_lang')";

if (mysqli_query($conn, $query)) {
  $reply_query = "SELECT COUNT(*) AS reply FROM xclone_posts WHERE reply_post_id = '$reply_post_id' AND post_type = 'reply'";
  $reply_result = mysqli_query($conn, $reply_query);
  $reply_row = mysqli_fetch_assoc($reply_result);
  $reply_count = $reply_row['reply'];
  

  $update_query = "UPDATE xclone_posts SET reply = '$reply_count' WHERE p_id = '$reply_post_id'";
  if (mysqli_query($conn, $update_query)) {

    // @mention
    $pattern = '/@([a-zA-Z0-9_]+)/';
    preg_match_all($pattern, $content, $matches);

    if (!empty($matches[1])) {
        foreach ($matches[1] as $mention) {
            $user_stmt = $conn->prepare("SELECT id FROM xclone_users WHERE username = ?");
            $user_stmt->bind_param("s", $mention);
            $user_stmt->execute();
            $user_result = $user_stmt->get_result();

            if ($user_result->num_rows > 0) {
                $user_row = $user_result->fetch_assoc();
                $mentioned_user_id = $user_row['id'];

                if ($mentioned_user_id != $userId) {
                    $notif_stmt = $conn->prepare("INSERT INTO xclone_notifs (user_id, sender_id, post_id, type) VALUES (?, ?, ?, 'mention_reply')");
                    $notif_stmt->bind_param("iii", $mentioned_user_id, $userId, $reply_post_id);
                    $notif_stmt->execute();
                }
            }
        }
    }

     // Yorum yapılan post'un sahibine bildirim gönderme
     $post_owner_query = "SELECT user_id FROM xclone_posts WHERE p_id = ?";
     $post_owner_stmt = $conn->prepare($post_owner_query);
     $post_owner_stmt->bind_param("i", $reply_post_id);
     $post_owner_stmt->execute();
     $post_owner_result = $post_owner_stmt->get_result();
 
     if ($post_owner_result->num_rows > 0) {
         $post_owner_row = $post_owner_result->fetch_assoc();
         $post_owner_id = $post_owner_row['user_id'];
 
         if ($post_owner_id != $userId) {
             $notif_stmt = $conn->prepare("INSERT INTO xclone_notifs (user_id, sender_id, post_id, type) VALUES (?, ?, ?, 'comment')");
             $notif_stmt->bind_param("iii", $post_owner_id, $userId, $reply_post_id);
             $notif_stmt->execute();
         }
     }
    echo "Reply added successfully";
  } else {
    echo "Error updating reply count: " . mysqli_error($conn);
  }
} else {
  echo "Error adding reply: " . mysqli_error($conn);
}

mysqli_close($conn);