<?php
require_once("../../../core/xclone_web_core.phtml");


$p_id = $_POST["p_id"];
$stmt = $conn->prepare("SELECT COUNT(*) AS post_id FROM xclone_repost WHERE repost_post_id = ?");
$stmt->bind_param("s", $p_id);
$stmt->execute();
$result = $stmt->get_result();

if ($result->num_rows > 0) {
    $row = $result->fetch_assoc();
    $like_count = $row["post_id"];
    echo $like_count;
} else {
    echo "0";
}

$stmt->close();
$conn->close();