<?php $settings = xclone_site_settings(); ?>
<div class="xclone-content-email">
    <div class="container" style="position: relative; padding: 40px; background: #F5F8FD !important;">
        <div class="email-top-logo">
            <a style="text-decoration: none !important; position: relative !important; margin-top: -25px !important; font-size: 25px; font-weight: 700; color: #1da1f2;" href="<?php echo xclone_link("welcome/login"); ?>"><?php echo $settings["site_name"]; ?></a>
            <p style="font-size: 15px;"><?php echo xclone_translate("refresh_password_user_send_email_2"); ?>
            <br><br>
            <a class="display-message-link" target="_blank" href="<?php echo xclone_link("welcome/new_password?token=".$resetToken); ?>"
            style="text-decoration: none !important; padding: 5px 15px; position: relative; font-size: 13px; font-weight: 700; line-height: 15px; color: #fff; background: #1da1f2; border: none; otuline:none; border-radius: 5px;"
            ><?php echo xclone_translate("user_new_password_page_1"); ?></a>
        </div>
    </div>
</div>