<div class="htag-list-look">
    <div class="htag-list-target">
        <a href="<?php echo xclone_link("@".$row["username"]); ?>">
            <img src="<?php echo xclone_link($row["avatar"]); ?>">
        </a>
        <a href="<?php echo xclone_link("@".$row["username"]); ?>">
            <h6><?php echo xclone_croptxt($row["username"], 0, 15); ?>
                <?php if($row["verified"]=="1"): ?>
                    <?php echo xclone_userBlue(); ?>
                <?php endif; ?>
            </h6>
            <xclone><strong><?php echo $row["followers"]; ?></strong> <?php echo xclone_translate("connect_people_for_following_info_small"); ?></xclone>
        </a>

        <button data-xclone-url="<?php echo xclone_link("@".$row["username"]); ?>">
            <?php echo xclone_translate("profile"); ?>
        </button>
    </div>
</div>