<main id="main" class="main">

    <div class="pagetitle">
      <h1>Edit page</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="<?php echo xclone_link("admin_panel/"); ?>">Home</a></li>
          <li class="breadcrumb-item">Pages</li>
          <li class="breadcrumb-item active">Edit page</li>
        </ol>
      </nav>
    </div>

    <section class="section profile">
      <div class="row">
        
        <div class="col-xl-12">

          <div class="card">
            <div class="card-body pt-3">
              <ul class="nav nav-tabs nav-tabs-bordered">

                <li class="nav-item">
                  <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#tweet-edit">Add new page</button>
                </li>
              </ul>
              <div class="tab-content pt-2">

                

                <div class="tab-pane profile-edit pt-3 active" id="tweet-edit">

                  <form action="" method="POST">
                    <div class="row mb-3">
                        <label for="page_content" class="col-md-4 col-lg-3 col-form-label">Page title</label>
                        <div class="col-md-8 col-lg-9 mb-3">
                          <input class="form-control" type="text" name="page_title" placeholder="Page title" required>
                        </div>

                        <label for="page_content" class="col-md-4 col-lg-3 col-form-label">Page SEO URL</label>
                        <div class="col-md-8 col-lg-9 mb-3">
                          <input style="background: #0f1419; color: #fff;" class="form-control" type="text" name="page_title_seo" placeholder="Page SEO URL" required>
                        </div>

                        <label for="page_content" class="col-md-4 col-lg-3 col-form-label">Page name</label>
                        <div class="col-md-8 col-lg-9 mb-3">
                          <input class="form-control" type="text" name="page_name" placeholder="Page name" required>
                        </div>

                        <label for="page_content" class="col-md-4 col-lg-3 col-form-label">Page content</label>
                        <div class="col-md-8 col-lg-9">
                          <textarea class="tinymce-editor" id="page_content" name="page_content">Hello, this is a page content.</textarea>
                        </div>
                    </div>

                  
                    <div class="text-center" style="margin-top:40px; position: relative;">
                      <?php if($xclone["admin"]["admin_status"]=="1"): ?>
                      <button type="submit" style="width: 100%;" class="btn btn-primary" name="addNewPage">Add page</button>
                      <?php else: ?>
                      <button disabled style="width: 100% !important;" class="btn btn-primary">Cannot trade because your account is demo</button>
                      <?php endif; ?>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </section>

  </main>
<?php
if(isset($_POST["addNewPage"])) {
    $id = $_GET["edit"];
    $page_title = htmlspecialchars($_POST["page_title"]);
    $page_title_seo = htmlspecialchars(xclone_seolink($_POST["page_title_seo"]));
    $page_name = htmlspecialchars($_POST["page_name"]);
    $page_content = $_POST["page_content"];
    
    $stmt = $conn->prepare("INSERT INTO xclone_pages (page_title, page_title_seo, page_name, page_content) VALUES (?, ?, ?, ?)");
    $stmt->bind_param("ssss", $page_title, $page_title_seo, $page_name, $page_content);
    $stmt->execute();
    
    if ($stmt->affected_rows > 0) {
        ?>
        <script>
        new Noty({
            type: 'success',
            text: 'The page was successfully add',
            timeout: 200,
            progressBar: true,
            callbacks: {
                afterClose: function() {
                    window.location.href = "/admin_panel/add_new_page?success=yes";
                }
            }
        }).show();
        </script>
        <?php
    } else {
        echo "Error: " . $conn->error;
    }
}
?>