<main id="main" class="main">

    <div class="pagetitle">
      <h1>Changelog</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="<?php echo vipub_link("admin_panel/"); ?>">Home</a></li>
          <li class="breadcrumb-item">Vipub Script</li>
          <li class="breadcrumb-item active">Changelog</li>
        </ol>
      </nav>
    </div>

    <section class="section">
      <div class="row">

      <div class="col-lg-12">
          <div class="card vipub-new-update">
              <div class="card-body" style="font-size: 15px !important; font-weight: 400 !important; line-height: 17px !important">
                <h5 class="card-title" style="color: #0f1419; font-size: 15px; font-weight: 800;">v1.3 (September 7, 2023)</h5>
                  <p>[New] - The design structure of Instagram and Twitter (Theme)</p>
                  <p>[New] - Welcome page with a simpler look</p>
                  <p>[New - Developed] - New post sharing design</p>
                  <p>[New - Developed] - New post listing design</p>
                  <p>[New - Developed] - New post display system</p>
                  <p>[New - Developed] - New post privacy system (Toggle commenting)</p>

                  <p>[New - Added] - System for embedding TikTok videos</p>
                  <p>[New - Added] - System for embedding YouTube videos</p>
                  <p>[New - Added] - System for embedding Instagram posts</p>
                  <p>[New - Added] - System for embedding Twitter posts</p>
                  <p>[New - Added] - User bookmarks system</p>
                  <p>[New - Added] - Customized emoji display system (Messages)</p>
                  <p>[New - Added] - Improved menu area for user profile. (Posts, Quotes, Media, Likes)</p>
                  <p>[New - Added] - 6 new languages ​​added. (Japanese, Chinese, Bengali, Hindi, French)</p>

                  <p>[New - Added] - Sign in system with Twitter</p>
                  <p>[New - Added] - Image sharing support for direct messages</p>
                  <p>[New - Added] - Emoji sharing support for direct messages</p>
                  <p>[New - Added] - System for selecting and sharing GIFs for new post creation (import via GIPHY)</p>
                  <p>[New - Addet] - Added an "Alert system" for banned users, informing them that they are banned. (Login page)</p>

                  <p>[Fixed] - Video sharing support for new post (Existing bugs fixed, unusability problem fixed)</p>
                  <p>[Fixed] - Fixed the issue where non-logged-in users could use the like post and follow user buttons</p>
                  <p>[Fixed] - Fixed the issue where non-logged-in users could not view the "Explore page, user profiles and post detail".</p>
                  <p>[Fixed] - Fixed the issue where the total notifications counter (not being reset)</p>
                  <p>And much more..</p>
              </div>
          </div>
        </div>


      <div class="col-lg-12">
          <div class="card">
              <div class="card-body" style="font-size: 15px !important; font-weight: 400 !important; line-height: 17px !important">
                <h5 class="card-title" style="color: #0f1419; font-size: 15px; font-weight: 800;">V1.0.2 (06 June 2023)</h5>
                <p>[New] - The welcome page has been reworked to make it simpler and faster response time.</p>

                <p>[Fixed] - Fixed a bug in code structure when clicking the dropdown menu in the non-login user timeline preview.</p>
                <p>[Fixed] - Fixed the "video preview showing even if the video is not shared" on the tweet content page.</p>
                <br>
                <p>[Fixed] - Fixed some minor issues in the kernel and including styling.</p>
              </div>
          </div>
        </div>

        <div class="col-lg-12">
          <div class="card">
              <div class="card-body" style="font-size: 15px !important; font-weight: 400 !important; line-height: 17px !important">
                <h5 class="card-title" style="color: #0f1419; font-size: 15px; font-weight: 800;">V1.0.1 (20 MAY 2023)</h5>
                <p>[Added - ADMIN PANEL] - Added ability to send SMTP Emails (<a style="font-size:13px;" href="<?php echo vipub_link("admin_panel/email_settings"); ?>">SMTP Settings</a>)</p>
                <p>[Added - ADMIN PANEL] - Added ability to toggle email sending (<a style="font-size:13px;" href="<?php echo vipub_link("admin_panel/general_settings"); ?>">General site settings</a>)</p>
                <p>[Added - ADMIN PANEL] - User timeline refresh interval setting added (<a style="font-size:13px;" href="<?php echo vipub_link("admin_panel/general_settings"); ?>">General site settings</a>)</p>
                <p>[Added - ADMIN PANEL] - Added user messaging page refresh time interval setting (<a style="font-size:13px;" href="<?php echo vipub_link("admin_panel/general_settings"); ?>">General site settings</a>)</p>
                <p>[Added - ADMIN PANEL] - "Number of unread messages" info counter added (<a style="font-size:13px;" href="<?php echo vipub_link("admin_panel"); ?>">Dashboard</a>)</p>
                <p>[Added - ADMIN PANEL] - Added "Password reset sent" link info counter (<a style="font-size:13px;" href="<?php echo vipub_link("admin_panel"); ?>">Dashboard</a>)</p>
                <p>[Added - ADMIN PANEL] - Ability to change your site logo and favicon was added (<a style="font-size:13px;" href="<?php echo vipub_link("admin_panel/logo_and_favicon_settings"); ?>">Change Logos and Favicon</a>)</p>
                <hr style="background: #555555; color: #555555; margin-bottom: 15px;" />
                <p>[Added] - Added forgot password page (Forgot password / reset password)</p>
                <p>[Added] - Added emoji icon support to new post creation window (icon)</p>
                <p>[Added] - Added link support for #Hashtag and #Mention in profile bio area</p>
                <p>[Added] - User video sharing support</p>
                <p>[Added] - Added user email notifications</p>
                <hr style="background: #555555; color: #555555; margin-bottom: 15px;" />
                <p>[Fixed] - Fixed the issue of not scrolling to the bottom message on the Messaging page</p>
                <p>[Fixed] - Fixed the issue where the text on the messaging page is displayed side by side</p>
                <p>[Fixed] - Fixed page corruption issue when trying to see "Media" items in user profile</p>
              </div>
          </div>
        </div>

        <div class="col-lg-12">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title" style="font-size: 15px; font-weight: 700;">V1.0.0 (10 APRIL 2023)</h5>
              <p>- Version 1.0.0, released on April 10, 2023.</p>
            </div>
          </div>
        </div>

      </div>
    </section>

  </main>