<?php $settings = xclone_site_settings(); ?>

<main id="main" class="main">
    <div class="pagetitle">
      <h1>Configure your hashtag listing settings</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="<?php echo xclone_link("admin_panel/"); ?>">Home</a></li>
          <li class="breadcrumb-item">Hashtags</li>
          <li class="breadcrumb-item active">Hashtag display settings</li>
        </ol>
      </nav>
    </div>
    <section class="section">
      <div class="row">
        <div class="col-lg-6">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title" style="color:#0f1419; font-size: 15px;">Hashtag <strong>Display Settings</strong></h5>
              On this page, you can set the rules by which users can display the <strong>"Hashtag"</strong> listing in the "<strong>Agendas that may interest you</strong>" on the right sidebar of your website.
              <br>
              <br>
              You can set your hashtag display settings within "<strong>4</strong>" different rules. 
              <br><br>
              <strong>Here are your options:</strong>
              <li style="margin-top: 10px; font-size: 15px;">The most tweeted hashtags in the last <strong>24 hours</strong>.</li>
              <li style="margin-top: 10px; font-size: 15px;">The most tweeted hashtags in the last <strong>1 week</strong>.</li>
              <li style="margin-top: 10px; font-size: 15px;">The most tweeted hashtags in the last <strong>1 month</strong>.</li>
              <li style="margin-top: 10px; font-size: 15px;">All tweeted <strong>hashtags</strong>.</li>
              <br>
              <small style="font-size: 12px;">
                <strong style="color:#1da1f2; font-size: 14px;">Rules that apply to the entire list:</strong><br>
                If the "<strong>number of tweets</strong>" updated for the hashtag list is equal to a number above the previous one, the listing area will be updated like Twitter and the most tweeted hashtag will always be displayed at the top. In addition, when a certain number of supported hashtags are reached, random "<strong>Trend</strong>"-related titles are displayed above the hashtag.
              </small>
            </div>
        </div>
    </div>

        <div class="col-lg-6">

          <div class="card">
            <div class="card-body">
                <h5 class="card-title" style="color:#0f1419; font-size: 15px;">
                Determine the structure of <strong>your hashtag list</strong>
                </h5>

                <form action="" method="POST">

                    <fieldset class="row mb-3" style="background:#F5F8FE; padding: 15px; border-radius: 5px;">
                        <div class="col-sm-10">

                            <div class="form-check mb-4">
                                <input class="form-check-input" type="radio" name="hashtag_display" id="daily" value="daily"
                                <?php if($settings["hashtag_display"]=="daily"): ?>checked<?php endif; ?>>
                                <label class="form-check-label" for="daily">
                                    The most tweeted hashtags in the last <strong>24 hours</strong>.
                                </label>
                            </div>

                            <div class="form-check mb-4">
                                <input class="form-check-input" type="radio" name="hashtag_display" id="weekly" value="weekly" <?php if($settings["hashtag_display"]=="weekly"): ?>checked<?php endif; ?>>
                                <label class="form-check-label" for="weekly">
                                    The most tweeted hashtags in the last <strong>1 week</strong>.
                                </label>
                            </div>

                            <div class="form-check mb-4">
                                <input class="form-check-input" type="radio" name="hashtag_display" id="monthly" value="monthly" <?php if($settings["hashtag_display"]=="monthly"): ?>checked<?php endif; ?>>
                                <label class="form-check-label" for="monthly">
                                    The most tweeted hashtags in the last <strong>1 month</strong>.
                                </label>
                            </div>

                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="hashtag_display" id="all" value="all" <?php if($settings["hashtag_display"]=="all"): ?>checked<?php endif; ?>>
                                <label class="form-check-label" for="all">
                                    List all tweeted hashtags.
                                </label>
                            </div>
                        </div>
                    </fieldset>

                    <style> .form-check-label { position: relative; } .form-check-label:before { content: ''; position: absolute; top: 50%; left: -26px; transform: translateY(-50%); width: 20px; height: 20px; border-radius: 50%; transition: all 0.4s ease; box-shadow: none; } .form-check-input:checked ~ .form-check-label:before { background-color: #1da1f1; } .form-check-input:checked ~ .form-check-label:after { content: '\2713'; position: absolute; top: 50%; left: -21px; transform: translateY(-50%); color: white; font-size: 14px; } </style>

                    <div class="row mt-4">
                        <div class="col-sm-50">
                            <?php if($xclone["admin"]["admin_status"]=="1"): ?>
                                <button type="submit" class="btn btn-success" name="saveHashtagList">
                                    Save
                                </button>
                                <?php else: ?>
                                <button disabled style="width: 100% !important; border-radius: 50px;" class="btn btn-primary">Cannot trade because your account is demo</button>
                            <?php endif; ?>
                        </div>
                    </div>
              </form>

            </div>
          </div>

        </div>
      </div>
    </section>
</main>
<?php
if(isset($_POST['saveHashtagList'])) {
    $hashtag_display = mysqli_real_escape_string($conn, $_POST['hashtag_display']);
    $sql = "UPDATE xclone_settings SET hashtag_display='$hashtag_display' WHERE id=1";
    if(mysqli_query($conn, $sql)) {
        ?>
        <script>
        new Noty({
            type: 'success',
            text: 'Your hashtag listing settings have been saved',
            timeout: 1500,
            progressBar: true,
            callbacks: {
                afterClose: function() {
                    window.location.href = "/admin_panel/hashtag_display_function";
                }
            }
        }).show();
        </script>
        <?php
    } else {
        echo "Error " . mysqli_error($conn);
    }
    mysqli_close($conn);
}
?>