<?php
if (isset($_GET["edit"]) && is_numeric($_GET["edit"])) {
    $ids = $_GET["edit"];

    $sql = "SELECT * FROM vipub_premium_package WHERE pack_id ='$ids'";
    $result = $conn->query($sql);


    if ($result->num_rows > 0) {
        $row = $result->fetch_assoc(); ?>

<main id="main" class="main">

    <div class="pagetitle">
      <h1>You are editing your package named <?php echo $row["package_name"]; ?></h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="<?php echo vipub_link("admin_panel/"); ?>">Home</a></li>
          <li class="breadcrumb-item">Premium package</li>
          <li class="breadcrumb-item active">Edit package</li>
        </ol>
      </nav>
    </div>

    <section class="section profile">
      <div class="row">
        <div class="col-xl-4">

          <div class="card">
            <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">
              <h2><?php echo vipub_croptxt($row["package_name"], 0, 30); ?></h2>
              <h3><?php echo $row["package_price"]; ?> $</h3>
            </div>
          </div>

        </div>

        <div class="col-xl-8">

          <div class="card">
            <div class="card-body pt-3">
              <ul class="nav nav-tabs nav-tabs-bordered">

                <li class="nav-item">
                  <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#tweet-edit">Edit package name and price</button>
                </li>
              </ul>
              <div class="tab-content pt-2">

                

                <div class="tab-pane profile-edit pt-3 active" id="tweet-edit">

                  <form action="" method="POST">
                    <div class="row mb-3">
                        <label for="inputText" style="font-size: 14px; font-weight: 700; line-height: 21px; color: #000;" class="col-sm-5 col-form-label">Package name</label>
                        <div class="col-sm-15">
                            <input type="text" class="form-control" style="width: 100% !important;" name="package_name" placeholder="Package name" value="<?php echo $row["package_name"]; ?>" required>
                        </div>
                        <small style="font-size: 12px;">Please enter your new package name that you want displayed.</small>
                    </div>

                    <div class="row mb-3">
                        <label for="inputText" style="font-size: 14px; font-weight: 700; line-height: 21px; color: #000;" class="col-sm-5 col-form-label">Package price / <small>(Month)</small></label>
                        <div class="col-sm-15">
                            <input type="number" class="form-control" style="width: 100% !important;" name="package_price" placeholder="Package price" value="<?php echo $row["package_price"]; ?>" required>
                        </div>
                        <small style="font-size: 12px;">Please enter the new price for this package.</small>
                    </div>

                    <div class="row mb-3">
                        <label for="inputText" style="font-size: 14px; font-weight: 400; line-height: 21px; color: #000;" class="col-sm-12 col-form-label">
                        <strong>Please note:</strong> <br> 
                        Package names do not support <strong>multilingual support</strong>. The package names you write here will be shown to the user as they are and will not be translated in their own language. Please remember this.
                        </label>
                    </div>

                    <div class="text-center" style="margin-top:10px; position: relative;">
                    <?php if($vipub["admin"]["admin_status"]=="1"): ?>
                      <button type="submit" style="width: 100%;" class="btn btn-success" name="savePackage">Save Changes</button>
                      <?php else: ?>
                            <button disabled style="width: 100% !important;" class="btn btn-primary">Cannot trade because your account is demo</button>
                        <?php endif; ?>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </section>

  </main>

  <?php
  } else {
    echo "package not found";
}
} else {
echo "Invalid package ID";
}
?>

<?php
if(isset($_POST["savePackage"])) {
    $id = $_GET["edit"];
    $package_name = htmlspecialchars($_POST["package_name"]);
    $package_price = htmlspecialchars($_POST["package_price"]);
    
    $stmt = $conn->prepare("UPDATE vipub_premium_package SET package_name=?, package_price=? WHERE pack_id=?");
    $stmt->bind_param("ssi", $package_name, $package_price, $id);
    $stmt->execute();
    
    if ($stmt->affected_rows > 0) {
        ?>
        <script>
        new Noty({
            type: 'success',
            text: 'Premium package details updated successfully',
            timeout: 200,
            progressBar: true,
            callbacks: {
                afterClose: function() {
                    window.location.href = "/admin_panel/premium_package_edit?edit=<?php echo $id; ?>";
                }
            }
        }).show();
        </script>
        <?php
    } else {
        echo "Error: " . $conn->error;
    }
}
?>