<main id="main" class="main">

    <div class="pagetitle">
      <h1>List of users</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="<?php echo vipub_link("admin_panel/"); ?>">Home</a></li>
          <li class="breadcrumb-item">Users</li>
          <li class="breadcrumb-item active">List of users</li>
        </ol>
      </nav>
    </div>

    <section class="section">
      <div class="row">
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title"><?php echo $settings["site_name"]; ?> <strong>user list</strong></h5>
              <p>Below is a list of all users registered on your website. When you want to edit any user, you can click on the <strong>id</strong> at the top of the table or the <strong>"edit"</strong> button at the end of the table.</p>

              <!-- Table with stripped rows -->
              <table class="table datatable">
                <thead>
                  <tr>
                    <th scope="col">id</th>
                    <th scope="col">Screen name</th>
                    <th scope="col">Username</th>
                    <th scope="col">Admin status</th>
                    <th scope="col">Account status</th>
                    <th scope="col">Joined</th>
                    <th scope="col">Edit status</th>
                  </tr>
                </thead>
                <tbody>
                <?php
                    $sql = "SELECT id, fullname, username, admin_status, account_status, joined FROM vipub_users";
                    $result = $conn->query($sql);

                    if ($result->num_rows > 0) {
                    while($row = $result->fetch_assoc()) { ?>

                    <tr>
                        <th scope="row"><a href="<?php echo vipub_link("admin_panel/edit_user?edit=".$row["id"]); ?>"><?php echo $row["id"]; ?></a></th>
                        <td><?php echo vipub_croptxt($row["fullname"], 0, 15); ?></td>
                        <td><a target="_blank" href="<?php echo vipub_link("@".$row["username"]); ?>" class="text-primary">@<?php echo $row["username"]; ?></a></td>
                        <td><?php if($row["admin_status"]=="0"): ?>
                            <span class="badge bg-warning">Not admin</span>
                        <?php else: ?>
                            <span class="badge bg-success">Admin</span>
                        <?php endif; ?>
                        </td>
                        <td>
                            <?php if($row["account_status"]=="0"): ?>
                            <span class="badge bg-success">Active</span>
                            <?php else: ?>
                            <span class="badge bg-danger">Banned</span>
                            <?php endif; ?>
                        </td>
                        <td><?php echo date("d.m.Y", strtotime($row["joined"])); ?></td>
                        <td><a href="<?php echo vipub_link("admin_panel/edit_user?edit=".$row["id"]); ?>" class="text-primary">Edit</a></td>
                    </tr>
                    
                    <?php } } ?>
                </tbody>
              </table>
              <!-- End Table with stripped rows -->

            </div>
          </div>

        </div>
      </div>
    </section>

  </main>