<?php
$conn = xcloneConnectDatabase();
$user_id = htmlspecialchars(trim($_GET["row"]));
$row = xclone_get_message_user($conn, $user_id);
$settings = xclone_site_settings();
?>

    <div class="message-chat-user-top-info-profile">
        <span data-xclone-url="<?php echo xclone_link("messages"); ?>">
            <i class="bi bi-arrow-left-square-fill"></i>
        </span>
        <a href="<?php echo xclone_link("@".$row["username"]); ?>">
            <img src="<?php echo xclone_link($row["avatar"]); ?>">
            <h5><?php echo $row["fullname"]; ?>
                <?php if($row["verified"]=="1"): ?>
                    <?php echo xclone_userBlue(); ?>
                <?php endif; ?>
            </h5>
        </a>
    </div>

<div class="message-chat-user-info-title">
    <a href="<?php echo xclone_link("@".$row["username"]); ?>">
        <img src="<?php echo xclone_link($row["avatar"]); ?>">
    </a>
    <a href="<?php echo xclone_link("@".$row["username"]); ?>">
        <h5><?php echo $row["fullname"]; ?>
        <?php if($row["verified"]=="1"): ?>
            <?php echo xclone_userBlue(); ?>
        <?php endif; ?>
    </h5>
    </a>
    <a href="<?php echo xclone_link("@".$row["username"]); ?>">
        <span>@<?php echo $row["username"]; ?> · <?php echo $settings["site_name"]; ?></span>
    </a>

    <a class="message-screen-user-view-profile-btn" href="<?php echo xclone_link("@".$row["username"]); ?>">
        <?php echo xclone_translate("view_message_page_on_user_profile"); ?>
    </a>
</div>

<?php while ($row = mysqli_fetch_assoc($result)): ?>
    
    <span class="message-send-date-funct">
        <?php echo xclone_post_new_date($row["created_at"]); ?>
        •
        <?php echo xclone_post_date($row["created_at"]); ?>
        
        <?php if($row["sender_id"]!==$_SESSION["user_id"]): ?>
            <form id="reported-for-message">
                <input type="hidden" name="m_id" value="<?php echo $row["m_id"]; ?>">
                <button type="submit" name="submit">
                • <i class="bi bi-flag"></i>
                </button>
            </form>
        <?php endif; ?>
    </span>
    
    <div class="xclone-message-container">
        <div class="message-user-info">
            

            <a href="<?php echo xclone_link("@".$row["username"]); ?>">
                <img src="<?php echo xclone_link($row["avatar"]); ?>">
            </a>
            <a href="<?php echo xclone_link("@".$row["username"]); ?>">
                <?php if($row["sender_id"]==$_SESSION["user_id"]): ?>
                <?php else: ?>
                <h5><?php echo $row["fullname"]; ?>
                <?php if($row["verified"]=="1"): ?>
                    <?php echo xclone_userBlue(); ?>
                <?php endif; ?>
                <?php endif; ?>
                </h5>
            </a>


            
            <div class="chat-info-xclone">
                <div class="send-account-info">
                <?php if($row["sender_id"]==$_SESSION["user_id"]): ?>

                    <?php if(xcloneMessageOnlyEmoji($row["message"])): ?>
                        <p id="mysend-message-only-emoji">
                            <?php echo xcloneMessageText($row["message"]); ?>
                    <?php else: ?>
                        <p id="mysend-messages">
                            <?php echo xcloneMessageText($row["message"]); ?>
                    <?php endif; ?>
                        <?php if($row["content_image"] !=NULL): ?>
                            <a href="<?php echo xclone_link($row["content_image"]); ?>" data-lightbox="<?php echo $row["m_id"]; ?>">
                                <img id="my-view-message-picture" src="<?php echo xclone_link($row["content_image"]); ?>">
                            </a>
                        <?php endif; ?>
                    </p>
                <?php else: ?>
                    <?php if(xcloneMessageOnlyEmoji($row["message"])): ?>
                        <p id="mysend-message-only-emoji-you">
                            <?php echo xcloneMessageText($row["message"]); ?>
                    <?php else: ?>
                        <p id="row-and-message-value">
                            <?php echo xcloneMessageText($row["message"]); ?>
                    <?php endif; ?>
                        <?php if($row["content_image"] !=NULL): ?>
                            <a href="<?php echo xclone_link($row["content_image"]); ?>" data-lightbox="<?php echo $row["m_id"]; ?>">
                                <img class="view-message-picture" src="<?php echo xclone_link($row["content_image"]); ?>">
                            </a>
                        <?php endif; ?>
                    </p>
                <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
<?php endwhile; ?>