<div class="no-post-yet-timeline not-yet-message-page-one">
    <div class="no-post-yet message-page-width-size">
        <h5><?php echo xclone_translate("message_page_1"); ?></h5>
        <span><?php echo xclone_translate("message_page_2"); ?></span>
        <span><?php echo xclone_translate("message_page_3"); ?></span>
        <a href="<?php echo xclone_link("connect_people"); ?>"><?php echo xclone_translate("message_page_4"); ?></a>
    </div>
</div>