<?php $settings = xclone_site_settings(); ?>
<div class="col-md-3">
    <div class="right-sidebar">
        <div class="right-sidebar-fluid">
            <div class="rsbr-card-boxing">
                <div class="rsbr-title">
                    <h5><?php echo xclone_translate("trending_hot_title"); ?></h5>
                </div>
                <div id="rsbr-htag-algoritmic"></div>
            </div>

            <div class="rsbr-card-boxing">
                <div class="rsbr-title">
                    <h5><?php echo xclone_translate("who_to_follow_title"); ?></h5>
                </div>
                <div id="rsbr-tofollow-algoritmic"></div>

                <div class="more-user-connect-people">
                    <a href="<?php echo xclone_link("connect_people"); ?>">
                    <?php echo xclone_translate("more"); ?>
                    </a>
                </div>
            </div>

            <div class="sidebar-footer-content">
                <?php xclone_rightsidebar_guest_footer(); ?>
            </div>
        </div>
    </div>
</div>