<?php if(isset($_SESSION["user_id"])): ?>
<div class="col-md-3">
    <div class="right-sidebar">
        <div class="search-container">
            <input type="text" placeholder="<?php echo vipub_translate("search_vipub"); ?>">
            <div class="search-results"></div>
        </div>
        <div class="right-sidebar-fluid">
            <div class="rsbr-card-boxing">
                <div class="rsbr-title">
                    <h5><?php echo vipub_translate("trending_hot_title"); ?></h5>
                </div>
                <div id="rsbr-htag-algoritmic"></div>
            </div>

            <div class="rsbr-card-boxing">
                <div class="rsbr-title">
                    <h5><?php echo vipub_translate("who_to_follow_title"); ?></h5>
                </div>
                <div id="rsbr-tofollow-algoritmic"></div>

                <div class="more-user-connect-people">
                    <a href="<?php echo vipub_link("connect_people"); ?>">
                    <?php echo vipub_translate("more"); ?>
                    </a>
                </div>

            </div>

            <div class="sidebar-footer-content">
                <?php vipub_rightsidebar_footer(); ?>
            </div>
        </div>
    </div>
</div>
<?php else: ?>
    <?php vipub_template("main/sidebar/right-guest"); ?>
<?php endif; ?>