<?php
$conn = xcloneConnectDatabase();
$user_id = htmlspecialchars(trim($_GET["row"]));
$row = xclone_get_message_user($conn, $user_id);
?>
<div class="no-post-yet-timeline">
    <a href="<?php echo xclone_link("@".$row["username"]); ?>">
        <img src="<?php echo xclone_link($row["avatar"]); ?>">
    </a>
    <div class="no-post-yet">
        <h5>
        <?php echo $row["fullname"]; ?> <?php echo xclone_translate("message_page_5"); ?></h5>
        <span><?php echo xclone_translate("message_page_6"); ?></span>
    </div>
</div>