<?php $page = isset($_GET['page']) ? $_GET['page'] : 'homepage';?>
<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link <?php echo ($page == 'homepage') ? '' : 'collapsed'; ?>" href="<?php echo xclone_link("admin_panel/"); ?>">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      </li>

      <li class="nav-heading">Website functions</li>

      <li class="nav-item">
        <a class="nav-link <?php echo ($page == 'general_settings') ? '' : 'collapsed'; ?>" data-bs-target="#forms-nav" href="<?php echo xclone_link("admin_panel/general_settings"); ?>">
          <i class="bi bi-gear"></i><span>Website Information</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link <?php echo ($page == 'logo_and_favicon_settings') ? '' : 'collapsed'; ?>" data-bs-target="#forms-nav" href="<?php echo xclone_link("admin_panel/logo_and_favicon_settings"); ?>">
          <i class="bi bi-image"></i><span>Logo & Favicon</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link <?php echo ($page == 'email_settings') ? '' : 'collapsed'; ?>" data-bs-target="#forms-nav" href="<?php echo xclone_link("admin_panel/email_settings"); ?>">
          <i class="bi bi-envelope"></i><span>SMTP Email Setup</span>
        </a>
      </li>

      <li class="nav-heading">Right sidebar functions</li>
      
      <li class="nav-item">
        <a class="nav-link <?php echo ($page == 'hashtag_display_function') ? '' : 'collapsed'; ?>" data-bs-target="#forms-nav" href="<?php echo xclone_link("admin_panel/hashtag_display_function"); ?>">
          <i class="bi bi-hash"></i><span>Hashtag display function</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link <?php echo ($page == 'user_display_function') ? '' : 'collapsed'; ?>" data-bs-target="#forms-nav" href="<?php echo xclone_link("admin_panel/#user_display_function"); ?>">
        <i class="bi bi-person-up"></i><span>User display function</span>
        </a>
      </li>

      <li class="nav-heading">Account and username functions</li>

      <li class="nav-item">
        <a class="nav-link <?php echo ($page == 'users') ? '' : 'collapsed'; ?>" data-bs-target="#forms-nav" href="<?php echo xclone_link("admin_panel/users"); ?>">
          <i class="bi bi-people"></i><span>Users</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#forms-nav" href="<?php echo xclone_link("admin_panel/#comingsoon"); ?>">
        <i class="bi bi-person-slash"></i><span>Username restrictions</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#forms-nav" href="<?php echo xclone_link("admin_panel/#comingsoon"); ?>">
        <i class="bi bi-patch-check"></i><span>Verification requests</span>
        </a>
      </li>

      <li class="nav-heading">Tweet functions</li>

      <li class="nav-item">
        <a class="nav-link <?php echo ($page == 'posts') ? '' : 'collapsed'; ?>" data-bs-target="#forms-nav" href="<?php echo xclone_link("admin_panel/posts"); ?>">
        <i class="bi bi-pencil-square"></i><span>Tweets</span>
        </a>
      </li>

      <li class="nav-heading">Ads functions</li>

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#forms-nav" href="<?php echo xclone_link("admin_panel/#comingsoon"); ?>">
        <i class="bi bi-table"></i><span>All ads</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#forms-nav" href="<?php echo xclone_link("admin_panel/#comingsoon"); ?>">
        <i class="bi bi-calendar2-x"></i><span>Ads that expire</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#forms-nav" href="<?php echo xclone_link("admin_panel/#comingsoon"); ?>">
        <i class="bi bi-cash-coin"></i><span>Advertising pricing</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#forms-nav" href="<?php echo xclone_link("admin_panel/#comingsoon"); ?>">
        <i class="bi bi-calendar2-plus"></i><span>Add new ad campaign</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#forms-nav" href="<?php echo xclone_link("admin_panel/#comingsoon"); ?>">
        <i class="bi bi-calendar2-check"></i><span>Ads pending approval</span>
        </a>
      </li>


      <li class="nav-heading">Page functions</li>

      <li class="nav-item">
        <a class="nav-link <?php echo ($page == 'add_new_page') ? '' : 'collapsed'; ?>" data-bs-target="#forms-nav" href="<?php echo xclone_link("admin_panel/add_new_page"); ?>">
          <i class="bi bi-book"></i><span>Add new page</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link <?php echo ($page == 'all_pages') ? '' : 'collapsed'; ?>" data-bs-target="#forms-nav" href="<?php echo xclone_link("admin_panel/all_pages"); ?>">
          <i class="bi bi-journal-richtext"></i><span>Pages</span>
        </a>
      </li>

      <li class="nav-heading">API functions</li>

      <li class="nav-item">
        <a class="nav-link <?php echo ($page == 'api_requests_used') ? '' : 'collapsed'; ?>" data-bs-target="#forms-nav" href="<?php echo xclone_link("admin_panel/api_requests_used"); ?>">
        <i class="bi bi-braces-asterisk"></i><span>API requests used</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link <?php echo ($page == 'api_users') ? '' : 'collapsed'; ?>" data-bs-target="#forms-nav" href="<?php echo xclone_link("admin_panel/api_users"); ?>">
        <i class="bi bi-braces-asterisk"></i><span>API users</span>
        </a>
      </li>


      <li class="nav-heading">OTHER</li>

      <li class="nav-item">
        <a class="nav-link <?php echo ($page == 'backup') ? '' : 'collapsed'; ?>" href="<?php echo xclone_link("admin_panel/#comingsoon"); ?>">
          <i class="bi bi-database-add"></i>
          <span>Database backup</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link <?php echo ($page == 'changelog') ? '' : 'collapsed'; ?>" href="<?php echo xclone_link("admin_panel/changelog"); ?>">
          <i class="bi bi-regex"></i>
          <span>Changelog</span>
        </a>
      </li>

    </ul>

  </aside>