<?php xclone_template("main/sidebar/left-sidebar"); ?>
<?php 
$conn = xcloneConnectDatabase(); $page_title_seo = htmlspecialchars(trim($_GET["page_title_seo"])); 
$row = xclone_get_pages($conn, $page_title_seo);
if ($row == "404") { echo "<meta http-equiv='refresh' content='0;url=/404'>"; exit(); } ?>
<div class="col-md-6">
    <div class="main-xclone-screenline">
        <div class="margin-bottom-connection-people"></div>
        <div class="connection-people-conn">
            <h6>
                <svg id="back-page" viewBox="0 0 24 24" aria-hidden="true"><g><path d="M7.414 13l5.043 5.04-1.414 1.42L3.586 12l7.457-7.46 1.414 1.42L7.414 11H21v2H7.414z"></path></g></svg>
                <?php echo $row["page_name"]; ?>
            </h6>
            
            <div class="user-not-and-banned-profile-container">
                <i style="margin-bottom: 25px;" class="bi bi-book-half"></i>
                <h5> 
                    <?php echo $row["page_name"]; ?>
                </h5>
                <p style="white-space: pre-wrap; word-wrap: break-word; text-align: left !important;"><?php echo $row["page_content"]; ?></p>
            </div>
                    
            <div class="suggested-page-bottom-footer">
                <?php echo xclone_rightsidebar_footer(); ?>
            </div>
        </div>
    </div>
</div>