<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
require_once("../../../core/vipub_web_core.phtml");

$settings = vipub_site_settings();
$smtp_settings = vipub_smtp();

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

$email = $_POST['email'];

$sql = "SELECT * FROM vipub_users WHERE email='$email'";
$result = mysqli_query($conn, $sql);

if (mysqli_num_rows($result) > 0) {
    $user = mysqli_fetch_assoc($result);
    $resetToken = bin2hex(random_bytes(32));
    $sql = "UPDATE vipub_users SET reset_token='$resetToken' WHERE id=" . $user['id'];
    $result = mysqli_query($conn, $sql);

    if ($result) {
        $mail = new PHPMailer(true);
        try {
            $smtp_settings = array(
                'smtp_host' => $smtp_settings["smtp_host"],
                'smtp_port' => $smtp_settings["smtp_port"],
                'smtp_username' => $smtp_settings["smtp_username"],
                'smtp_password' => $smtp_settings["smtp_password"]
            );

            ob_start();
            require_once("../../../themes/default/apps/content_email/reset_password.phtml");
            $body = ob_get_clean();
            $body = str_replace(array('<?', '?>'), array('&lt;?', '?&gt;'), $body);

            $mail->isSMTP();
            $mail->Host = $smtp_settings["smtp_host"];
            $mail->SMTPAuth = true;
            $mail->Username = $smtp_settings["smtp_username"];
            $mail->Password = $smtp_settings["smtp_password"];
            $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
            $mail->Port = $smtp_settings["smtp_port"];

            $mail->setFrom($smtp_settings["smtp_username"], $settings["site_name"]);
            $mail->addAddress($user['email'], $user['fullname']);
            $mail->CharSet = 'UTF-8'; 
            $mail->isHTML(true);
            $mail->Subject = vipub_translate("refresh_password_user_send_email");
            $mail->Body = $body;
            $mail->send();
            echo 'success';
        } catch (Exception $e) {
            echo 'error';
        }
    } else {
        echo 'error';
    }
} else {
    echo 'not_found';
}

mysqli_close($conn);