<link href="<?php echo vipub_template_master("style/welcome/welcome.css"); ?>?csy=<?php echo rand(5435, 12312345235); ?>" rel="stylesheet">
<?php $settings = vipub_site_settings(); ?>
<?php $conn = vipubConnectDatabase(); 
$token = $_GET["token"];

if (empty($token)) {
    header("Location: /404");
    exit;
}

$sql = "SELECT * FROM vipub_users WHERE reset_token='$token'";
$result = mysqli_query($conn, $sql);

if (mysqli_num_rows($result) == 1) {
    $row = mysqli_fetch_assoc($result) ?>

<div class="welcome-to-website-container">
    <div class="welcome-page-form-container">
        <div class="container-welcome-form-content">
            <div class="genel-page-title" data-vipub-user-url="<?php echo vipub_link("welcome/login"); ?>">
                <img src="<?php echo vipub_template_master("images/logo.png"); ?>" alt="">
            </div>
            <form id="user-new-password-save">
                <div class="form-content-for-user">
                    <small><?php echo vipub_translate("user_new_password_page_2"); ?></small>
                </div>

                <div class="form-content-for-user">
                    <input type="text" name="password" id="password" placeholder="<?php echo vipub_translate("welcome_page_text_4"); ?>">
                </div>

                <div class="form-content-for-user border-color-class">
                    <button type="submit" id="save-password-btn" class="btn">
                        <?php echo vipub_translate("account_settings_menu_27"); ?>
                    </button>
                </div>

                <select class="welcome-dropdown-menu">
                    <option select><?php echo vipub_translate("language_name"); ?></option>
                    <option value="turkish"><?php echo vipub_translate("language_name_1"); ?></option>
                    <option value="english"><?php echo vipub_translate("language_name_2"); ?></option>
                    <option value="espanol"><?php echo vipub_translate("language_name_3"); ?></option>
                    <option value="german"><?php echo vipub_translate("language_name_4"); ?></option>
                    <option value="russian"><?php echo vipub_translate("language_name_5"); ?></option>
                    <option value="portuguese"><?php echo vipub_translate("language_name_6"); ?></option>
                    <option value="french"><?php echo vipub_translate("language_name_7"); ?></option>
                    <option value="chinese"><?php echo vipub_translate("language_name_8"); ?></option>
                    <option value="hindi"><?php echo vipub_translate("language_name_9"); ?></option>
                    <option value="japanese"><?php echo vipub_translate("language_name_10"); ?></option>
                    <option value="bengali"><?php echo vipub_translate("language_name_11"); ?></option>
                </select>
            </form>
        </div>
    </div>
</div>

<div class="welcome-page-footer-bottom">
    <div class="page-footer-bottom">
        <a href="<?php echo vipub_link("pages/about"); ?>"><?php echo vipub_translate("welcome_footer_1"); ?></a>
        <a href="<?php echo vipub_link("pages/privacy-policy"); ?>"><?php echo vipub_translate("welcome_footer_2"); ?></a>
        <a href="<?php echo vipub_link("pages/terms-policy"); ?>"><?php echo vipub_translate("welcome_footer_3"); ?></a>
        <a href="<?php echo vipub_link("pages/cookies-policy"); ?>"><?php echo vipub_translate("welcome_footer_5"); ?></a>
        <a href="<?php echo vipub_link("pages/help-center"); ?>"><?php echo vipub_translate("welcome_footer_4"); ?></a>
        
        <a href="#" class="site-language-select dropdown-toggle"><?php echo vipub_translate("language_name"); ?></a>
       
        
        <a style="cursor: default; user-select:none; text-decoration: none !important;" href="#">© <strong><?php echo $settings["site_name"]; ?> · <?php echo date("Y"); ?></strong></a>
    </div>
</div>

<?php vipub_template("auth/script/vipub.master.script"); ?>
<script>
    $(document).on('click', '[data-vipub-user-url]', function() {
        var url = $(this).data('vipub-user-url');
        window.location.href = url;
    });
</script>

<script>
    $(document).ready(function() {
    $('#password').on('input', function() {
        if ($(this).val().length > 0) {
        $('#save-password-btn').prop('disabled', false);
        } else {
        $('#save-password-btn').prop('disabled', true);
        }
    });

    $('#user-new-password-save').on('submit', function(e) {
        e.preventDefault();
        $('#save-password-btn').html('<?php echo vipub_translate("welcome_page_login_6"); ?>').prop('disabled', true);

        var password = $('#password').val();

        $.ajax({
        url: '/apps/ajax/auth/new_password.phtml?user=<?php echo $row["id"]; ?>',
        type: 'post',
        data: {
            password: password
        },
        success: function(response) {
            new Noty({
                type: 'success',
                text: '<?php echo vipub_translate("settings_page_save_value_desc_16"); ?>',
                timeout: 2000,
                callbacks: {
                    afterClose: function() {
                        window.location.href = '/welcome/login';
                    }
                }
            }).show();
            },
            error: function(xhr, status, error) {
                new Noty({
                    type: 'error',
                    text: 'Bir hata oluştu!'
                }).show();
                $('#save-password-btn').html('<?php echo vipub_translate("account_settings_menu_27"); ?>').prop('disabled', false);
            }
        });
    });
    });
</script>
<?php } else { header("Location: /404"); exit(); } ?>