<link href="<?php echo xclone_template_master("style/welcome/welcome.css"); ?>?csy=<?php echo rand(5435, 12312345235); ?>" rel="stylesheet">
<?php $settings = xclone_site_settings(); ?>

<div class="welcome-to-website-container">
    <div class="welcome-page-form-container">
        <div class="container-welcome-form-content">
            <div class="genel-page-title" data-xclone-user-url="<?php echo xclone_link("welcome/login"); ?>">
                <img src="<?php echo xclone_template_master("images/logo.png"); ?>" alt="">
            </div>
            <form id="account-refresh-password">
                <div class="form-content-for-user">
                    <input type="text" name="email" id="email" placeholder="<?php echo xclone_translate("welcome_page_text_12"); ?>">
                </div>

                <div class="form-content-for-user">
                    <a href="<?php echo xclone_link("welcome/login"); ?>">
                        <?php echo xclone_translate("yes_password_refresh_not_page_to_login_page"); ?>
                    </a>
                </div>

                
                <div class="form-content-for-user border-color-class">
                    <button type="submit" id="refresh-password-btn" class="btn">
                        <?php echo xclone_translate("yes_password_refresh_not_page_to_login_page_3"); ?>
                    </button>
                </div>

                <div class="form-content-for-user-bottom-border">
                    <small><?php echo xclone_translate("welcome_page_text_7"); ?></small>
                </div>

                <select class="welcome-dropdown-menu">
                    <option select><?php echo xclone_translate("language_name"); ?></option>
                    <option value="turkish"><?php echo xclone_translate("language_name_1"); ?></option>
                    <option value="english"><?php echo xclone_translate("language_name_2"); ?></option>
                    <option value="espanol"><?php echo xclone_translate("language_name_3"); ?></option>
                    <option value="german"><?php echo xclone_translate("language_name_4"); ?></option>
                    <option value="russian"><?php echo xclone_translate("language_name_5"); ?></option>
                    <option value="portuguese"><?php echo xclone_translate("language_name_6"); ?></option>
                    <option value="french"><?php echo xclone_translate("language_name_7"); ?></option>
                    <option value="chinese"><?php echo xclone_translate("language_name_8"); ?></option>
                    <option value="hindi"><?php echo xclone_translate("language_name_9"); ?></option>
                    <option value="japanese"><?php echo xclone_translate("language_name_10"); ?></option>
                    <option value="bengali"><?php echo xclone_translate("language_name_11"); ?></option>
                </select>
            </form>
        </div>
    </div>
</div>

<div class="welcome-page-footer-bottom">
    <div class="page-footer-bottom">
        <a href="<?php echo xclone_link("pages/about"); ?>"><?php echo xclone_translate("welcome_footer_1"); ?></a>
        <a href="<?php echo xclone_link("pages/privacy-policy"); ?>"><?php echo xclone_translate("welcome_footer_2"); ?></a>
        <a href="<?php echo xclone_link("pages/terms-policy"); ?>"><?php echo xclone_translate("welcome_footer_3"); ?></a>
        <a href="<?php echo xclone_link("pages/cookies-policy"); ?>"><?php echo xclone_translate("welcome_footer_5"); ?></a>
        <a href="<?php echo xclone_link("pages/help-center"); ?>"><?php echo xclone_translate("welcome_footer_4"); ?></a>
        
        <a href="#" class="site-language-select dropdown-toggle"><?php echo xclone_translate("language_name"); ?></a>
        <a style="cursor: default; user-select:none; text-decoration: none !important;" href="#">© <strong><?php echo $settings["site_name"]; ?> · <?php echo date("Y"); ?></strong></a>
    </div>
</div>

<?php xclone_template("auth/script/xclone.master.script"); ?>
<script>
    $(document).on('click', '[data-xclone-user-url]', function() {
        var url = $(this).data('xclone-user-url');
        window.location.href = url;
    });
</script>

<script>
    $(document).ready(function() {
        $('#refresh-password-btn').attr('disabled', true);

        $('#email').on('input', function() {
            var email = $('#email').val().trim();
            if (email !== '') {
                $('#refresh-password-btn').attr('disabled', false);
            } else {
                $('#refresh-password-btn').attr('disabled', true);
            }
        });

        $('#account-refresh-password').submit(function(event) {
            event.preventDefault();
            var email = $('#email').val().trim();
            if (email !== '') {
                $('#refresh-password-btn').html('<?php echo xclone_translate("yes_password_refresh_not_page_to_login_page_4"); ?>').attr('disabled', true);

                $.ajax({
                    url: '/apps/ajax/auth/reset_password.phtml',
                    method: 'POST',
                    data: {
                        email: email
                    },
                    success: function(data) {
                        console.log(data);
                        if (data === 'success') {
                            $('#refresh-password-btn').html('<?php echo xclone_translate("yes_password_refresh_not_page_to_login_page_5"); ?>').attr('disabled', true);
                            new Noty({
                                type: 'success',
                                text: '<?php echo xclone_translate("yes_password_refresh_not_page_to_login_page_6"); ?>',
                                timeout: 2000,
                                callbacks: {
                                    afterClose: function() {
                                        $('#email').val('');
                                    }
                                }
                            }).show();
                        } else if (data === 'not_found') {
                            $('#refresh-password-btn').html('<?php echo xclone_translate("yes_password_refresh_not_page_to_login_page_3"); ?>').attr('disabled', false);
                            new Noty({
                                type: 'error',
                                text: '<?php echo xclone_translate("yes_password_refresh_not_page_to_login_page_7"); ?>',
                                timeout: 2000
                            }).show();
                        } else {
                            $('#refresh-password-btn').html('<?php echo xclone_translate("yes_password_refresh_not_page_to_login_page_3"); ?>').attr('disabled', false);
                            new Noty({
                                type: 'error',
                                text: '<?php echo xclone_translate("welcome_page_login_5"); ?>',
                                timeout: 2000
                            }).show();
                        }
                    },
                    error: function(jqXHR, textStatus, errorThrown) {
                        $('#refresh-password-btn').html('<?php echo xclone_translate("yes_password_refresh_not_page_to_login_page_3"); ?>').attr('disabled', false);
                        new Noty({
                            type: 'error',
                            text: '<?php echo xclone_translate("welcome_page_login_5"); ?>',
                            timeout: 2000
                        }).show();
                        console.log(textStatus + ': ' + errorThrown);
                    }
                    });
                    } else {
                        new Noty({
                            type: 'warning',
                            text: 'Kullanıcı adı veya e-posta adresi gerekli.',
                            timeout: 2000
                        }).show();
                    }
        });
    });
</script>