<?php $post_id = $row["p_id"]; $link = xclone_link($row["username"]."/status/".$post_id); ?>
<?php $xclone["admin"] = xclone_my_user_info(); ?>
<div class="post vipup-post-publication" id="post-<?php echo $postId; ?>" data-post-id="<?php echo $postId; ?>">
    <div class="vipup-post-userinfo">
        <a href="/@<?php echo $username; ?>">
        <img src="/<?php echo $avatar; ?>">
        </a>
        <a href="/@<?php echo $username; ?>">
        <h5><?php echo xclone_croptxt($fullname, 0, 25); ?>
        <?php if($row["verified"]=="1"): ?>
            <?php echo xclone_userBlue(); ?>
        <?php endif; ?>
        </h5>
        </a>
        <a href="/@<?php echo $username; ?>">
        <span>@<?php echo $username; ?>
        · <?php echo ltrim(date('j', strtotime($row["post_joined"])), '0'), " " . xclone_translate('month_'.strtolower(date('M', strtotime($row["post_joined"])))); ?> 
        · <?php echo date("h:i A",strtotime($row["post_joined"])); ?>
        
            <?php if($row["post_type"]=="postAds"): ?>
                · <strong style="font-weight: 400;">Sponsored</strong>
            <?php endif; ?>
        </span>
        </a>
    </div>
    
    <div class="post-content-line"><?php echo convertxcloneText($row["content_post"]); ?><?php if($row["content_image"] != "NULL"): ?><a href="<?php echo xclone_link($row["content_image"]); ?>" data-lightbox="<?php echo xclone_link($row["content_image"]); ?>"><img id="xcloneNsfw_<?php echo $row["p_id"]; ?>" src="<?php echo xclone_link($row["content_image"]); ?>"></a> <?php endif; ?><?php if($row["content_video"]= "NULL"): ?><?php else: ?><video controls><source src="<?php echo $row["content_video"]; ?>"></video><?php endif; ?></div>

    <div class="post-value-content">
        <a href="<?php echo xclone_link($row["username"]."/status/".$row["p_id"]); ?>" style="text-decoration: none;">
        <span>
            <svg viewBox="0 0 24 24" aria-hidden="true"><g><path d="M1.751 10c0-4.42 3.584-8 8.005-8h4.366c4.49 0 8.129 3.64 8.129 8.13 0 2.96-1.607 5.68-4.196 7.11l-8.054 4.46v-3.69h-.067c-4.49.1-8.183-3.51-8.183-8.01zm8.005-6c-3.317 0-6.005 2.69-6.005 6 0 3.37 2.77 6.08 6.138 6.01l.351-.01h1.761v2.3l5.087-2.81c1.951-1.08 3.163-3.13 3.163-5.36 0-3.39-2.744-6.13-6.129-6.13H9.756z"></path></g></svg>
            <span id="reply-live-count"><?php echo xclone_count($row["reply"]); ?></span>
        </span>
        </a>


        <span type="button" type="button" class="like-btn" data-post-id="<?php echo $row["p_id"]; ?>">
            <svg class="post-like-icon" data-user-id="<?php echo $row["id"]; ?>" viewBox="0 0 24 24" aria-hidden="true"><g><path d="M16.697 5.5c-1.222-.06-2.679.51-3.89 2.16l-.805 1.09-.806-1.09C9.984 6.01 8.526 5.44 7.304 5.5c-1.243.07-2.349.78-2.91 1.91-.552 1.12-.633 2.78.479 4.82 1.074 1.97 3.257 4.27 7.129 6.61 3.87-2.34 6.052-4.64 7.126-6.61 1.111-2.04 1.03-3.7.477-4.82-.561-1.13-1.666-1.84-2.908-1.91zm4.187 7.69c-1.351 2.48-4.001 5.12-8.379 7.67l-.503.3-.504-.3c-4.379-2.55-7.029-5.19-8.382-7.67-1.36-2.5-1.41-4.86-.514-6.67.887-1.79 2.647-2.91 4.601-3.01 1.651-.09 3.368.56 4.798 2.01 1.429-1.45 3.146-2.1 4.796-2.01 1.954.1 3.714 1.22 4.601 3.01.896 1.81.846 4.17-.514 6.67z"></path></g></svg>
            <span data="like-post-count"><?php echo $row["likes"]; ?></span>
        </span>

        <span type="button" type="button" class="repost-btn" data-post-repostid="<?php echo $row["p_id"]; ?>">
            <svg viewBox="0 0 24 24" aria-hidden="true"><g><path d="M4.5 3.88l4.432 4.14-1.364 1.46L5.5 7.55V16c0 1.1.896 2 2 2H13v2H7.5c-2.209 0-4-1.79-4-4V7.55L1.432 9.48.068 8.02 4.5 3.88zM16.5 6H11V4h5.5c2.209 0 4 1.79 4 4v8.45l2.068-1.93 1.364 1.46-4.432 4.14-4.432-4.14 1.364-1.46 2.068 1.93V8c0-1.1-.896-2-2-2z"></path></g></svg>
            <span data="repost-post-count"><?php echo $row["repost"]; ?></span>
        </span>

        <div class="dropdown">
            <span id="shareModal">
                <svg viewBox="0 0 24 24" aria-hidden="true">
                <g>
                    <path d="M12 2.59l5.7 5.7-1.41 1.42L13 6.41V16h-2V6.41l-3.3 3.3-1.41-1.42L12 2.59zM21 15l-.02 3.51c0 1.38-1.12 2.49-2.5 2.49H5.5C4.11 21 3 19.88 3 18.5V15h2v3.5c0 .28.22.5.5.5h12.98c.28 0 .5-.22.5-.5L19 15h2z"></path>
                </g>
                </svg>
            </span>
            <ul>
                <?php if(isset($_SESSION["user_id"])): ?>
                    <?php if($row["user_id"]==$_SESSION["user_id"]): ?>
                    <button type="button" class="delete-post" data-post-id="<?php echo $row["p_id"]; ?>">
                    <svg viewBox="0 0 24 24" aria-hidden="true"><g><path d="M16 6V4.5C16 3.12 14.88 2 13.5 2h-3C9.11 2 8 3.12 8 4.5V6H3v2h1.06l.81 11.21C4.98 20.78 6.28 22 7.86 22h8.27c1.58 0 2.88-1.22 3-2.79L19.93 8H21V6h-5zm-6-1.5c0-.28.22-.5.5-.5h3c.27 0 .5.22.5.5V6h-4V4.5zm7.13 14.57c-.04.52-.47.93-1 .93H7.86c-.53 0-.96-.41-1-.93L6.07 8h11.85l-.79 11.07zM9 17v-6h2v6H9zm4 0v-6h2v6h-2z"></path></g></svg>
                    <?php echo xclone_translate("post_select_dropdown_1"); ?></button>
                    
                    <?php elseif($xclone["admin"]["admin_status"]=="1"): ?>
                    <button type="button" class="delete-post" data-post-id="<?php echo $row["p_id"]; ?>">
                    <svg viewBox="0 0 24 24" aria-hidden="true"><g><path d="M16 6V4.5C16 3.12 14.88 2 13.5 2h-3C9.11 2 8 3.12 8 4.5V6H3v2h1.06l.81 11.21C4.98 20.78 6.28 22 7.86 22h8.27c1.58 0 2.88-1.22 3-2.79L19.93 8H21V6h-5zm-6-1.5c0-.28.22-.5.5-.5h3c.27 0 .5.22.5.5V6h-4V4.5zm7.13 14.57c-.04.52-.47.93-1 .93H7.86c-.53 0-.96-.41-1-.93L6.07 8h11.85l-.79 11.07zM9 17v-6h2v6H9zm4 0v-6h2v6h-2z"></path></g></svg>
                    <?php echo xclone_translate("post_select_dropdown_1"); ?></button>
                    <?php endif; ?>
                <?php endif; ?>

                <li>
                    <a href="/<?php echo $row["username"]; ?>/status/<?php echo $row["p_id"]; ?>">
                    <svg viewBox="0 0 24 24" aria-hidden="true"><g><path d="M5.5 4c-.28 0-.5.22-.5.5v15c0 .28.22.5.5.5H12v2H5.5C4.12 22 3 20.88 3 19.5v-15C3 3.12 4.12 2 5.5 2h13C19.88 2 21 3.12 21 4.5V13h-2V4.5c0-.28-.22-.5-.5-.5h-13zM16 10H8V8h8v2zm-8 2h8v2H8v-2zm10 7v-3h2v3h3v2h-3v3h-2v-3h-3v-2h3z"></path></g></svg>
                    <?php echo xclone_translate("post_select_dropdown_2"); ?></a>
                </li>

                <li>
                    <a href="/<?php echo $row["username"]; ?>/status/<?php echo $row["p_id"]; ?>/likes">
                    <svg viewBox="0 0 24 24" aria-hidden="true"><g><path d="M16.697 5.5c-1.222-.06-2.679.51-3.89 2.16l-.805 1.09-.806-1.09C9.984 6.01 8.526 5.44 7.304 5.5c-1.243.07-2.349.78-2.91 1.91-.552 1.12-.633 2.78.479 4.82 1.074 1.97 3.257 4.27 7.129 6.61 3.87-2.34 6.052-4.64 7.126-6.61 1.111-2.04 1.03-3.7.477-4.82-.561-1.13-1.666-1.84-2.908-1.91zm4.187 7.69c-1.351 2.48-4.001 5.12-8.379 7.67l-.503.3-.504-.3c-4.379-2.55-7.029-5.19-8.382-7.67-1.36-2.5-1.41-4.86-.514-6.67.887-1.79 2.647-2.91 4.601-3.01 1.651-.09 3.368.56 4.798 2.01 1.429-1.45 3.146-2.1 4.796-2.01 1.954.1 3.714 1.22 4.601 3.01.896 1.81.846 4.17-.514 6.67z"></path></g></svg>
                    <?php echo xclone_translate("post_in_view_like_page"); ?></a>
                </li>

                <li>
                    <a href="#">
                    <svg viewBox="0 0 24 24" aria-hidden="true"><g><path d="M15.24 4.31l-4.55 15.93-1.93-.55 4.55-15.93 1.93.55zm-8.33 3.6L3.33 12l3.58 4.09-1.5 1.32L.67 12l4.74-5.41 1.5 1.32zm11.68-1.32L23.33 12l-4.74 5.41-1.5-1.32L20.67 12l-3.58-4.09 1.5-1.32z"></path></g></svg>
                    <?php echo xclone_translate("post_select_dropdown_3"); ?></a>
                </li>

                <li>
                    <a class="copy_post" href="#" data-post-id="<?php echo $post_id; ?>">                   
                    <svg viewBox="0 0 24 24" aria-hidden="true"><g><path d="M18.36 5.64c-1.95-1.96-5.11-1.96-7.07 0L9.88 7.05 8.46 5.64l1.42-1.42c2.73-2.73 7.16-2.73 9.9 0 2.73 2.74 2.73 7.17 0 9.9l-1.42 1.42-1.41-1.42 1.41-1.41c1.96-1.96 1.96-5.12 0-7.07zm-2.12 3.53l-7.07 7.07-1.41-1.41 7.07-7.07 1.41 1.41zm-12.02.71l1.42-1.42 1.41 1.42-1.41 1.41c-1.96 1.96-1.96 5.12 0 7.07 1.95 1.96 5.11 1.96 7.07 0l1.41-1.41 1.42 1.41-1.42 1.42c-2.73 2.73-7.16 2.73-9.9 0-2.73-2.74-2.73-7.17 0-9.9z"></path></g></svg>
                    <?php echo xclone_translate("post_select_dropdown_4"); ?>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

<script>
$(document).ready(function() {
  $('.copy_post[data-post-id="<?php echo $post_id; ?>"]').click(function(event) {
    event.preventDefault();
    var copyText = "<?php echo $link; ?>";
    var textarea = document.createElement("textarea");
    textarea.value = copyText;
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand("copy");
    document.body.removeChild(textarea);
    
    new Noty({
      text: "<?php echo xclone_translate("post_select_dropdown_5"); ?>",
      timeout: 2000,
      type: "success"
    }).show();
  });
});
</script>

<script>
    $(document).ready(function() {
    $('.dropdown').on("click", function(event) {
        event.stopPropagation();
        $(this).find('ul').toggle();
    });

    $(document).on("click", function(event) {
        if (!$(event.target).closest('.dropdown').length) {
        $('.dropdown ul').hide();
        }
    });

    $('.dropdown-menu').on('mouseleave', function() {
        var $this = $(this);
        setTimeout(function() {
        if (!$this.is(':hover')) {
            $this.hide();
        }
        }, 1000);
    });
    });
</script>

<script>
    $(".delete-post").on("click", function() {
    var postId = $(this).data("post-id");

    Swal.fire({
        title: '<?php echo xclone_translate("delete_your_post"); ?>',
        text: "<?php echo xclone_translate("delete_your_post_2"); ?>",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#F4212D',
        cancelButtonColor: '#0f1419',
        confirmButtonText: '<?php echo xclone_translate("delete"); ?>',
        cancelButtonText: '<?php echo xclone_translate("cancel"); ?>'
    }).then((result) => {
        if (result.isConfirmed) {
            $.ajax({
                url: "/apps/api/delete-post/post-delete.phtml", // Silme işlemi için API endpoint'i
                type: "POST",
                data: { post_id: postId },
                success: function(response) {
                    if (response.trim() === "success") {
                        setTimeout(function() {
                            $("#post-" + postId).slideUp(2000, function() {
                                $(this).remove();
                            });
                        }, 2000);
                        toastr.success('<?php echo xclone_translate("post_success_delete"); ?>', '', {timeOut: 2000});
                    }
                },
                error: function() {
                    setTimeout(function() {
                        $("#post-" + postId).slideUp(500, function() {
                            $(this).remove();
                        });
                    }, 2000);
                }
            });
        }
    })
});
</script>

<script>
    $(document).on("click", ".like-btn, .unlike-btn", function(){
        var post_id = $(this).data("post-id");
        var post_user_id = <?php echo $row["id"]; ?>;
        var like_btn = $(this).hasClass("like-btn") ? $(this) : $(this).siblings(".like-btn");
        var unlike_btn = $(this).hasClass("unlike-btn") ? $(this) : $(this).siblings(".unlike-btn");
        
        if (like_btn.is(":visible")) {
            $.ajax({
                url: "/apps/ajax/timeline/get-like.phtml",
                type: "POST",
                data: {
                    action: "like",
                    p_id: post_id,
                    post_user_id: post_user_id
                },
                success: function(response) {
                    if (response.status == "success") {
                        like_btn.removeClass("like-btn").addClass("unlike-btn");
                        unlike_btn.show();
                        var likes = parseInt(like_btn.find("span").text());
                        like_btn.find("span").text(likes + 1);
                        like_btn.find("span").attr("id", "unlike-btn");

                        $(".like-count[data-post-id='"+post_id+"']").text(response.like_count);
                        new Noty({
                            text: "Like post.",
                            type: "success",
                            timeout: 2000
                        }).show();
                    }
                }
            }).one("click", function() {
                console.log("The tweet has already been liked.");
            });
        } else if (unlike_btn.is(":visible")) {
            $.ajax({
                url: "/apps/ajax/timeline/get-like.phtml",
                type: "POST",
                data: {
                    action: "unlike",
                    p_id: post_id,
                    post_user_id: post_user_id
                },
                success: function(response) {
                    if (response.status == "success") {
                        like_btn.removeClass("unlike-btn").addClass("like-btn");
                        unlike_btn.hide();
                        var likes = parseInt(like_btn.find("span").text());
                        like_btn.find("span").text(likes - 1);
                        like_btn.find("span").removeAttr("id");
                        
                        $(".like-count[data-post-id='"+post_id+"']").text(response.like_count);
                        
                        new Noty({
                            text: "Post like deleted.",
                            type: "success",
                            timeout: 2000
                        }).show();
                    }
                }
            }).one("click", function() {
                console.log("Like cancellation has already been done.");
            });
        }
    });
</script>