
<?php xclone_template("main/sidebar/left-sidebar"); ?>
<div class="col-md-6">
    <div class="main-xclone-screenline">
        
        <div class="site-header-box">
            <h5>
            <?php echo xclone_translate("homepage"); ?></h5>
        </div>
        
        <div class="share-to-post-homepage">
            <?php xclone_template("timeline/post/new-post"); ?>
        </div>
        <div id="feed-timeline"></div>
    </div>
    <div class="mobile-responsive-margin-bottom-design"></div>
</div>
<?php xclone_template("main/sidebar/right-sidebar"); ?>