<?php xclone_template("main/sidebar/left-sidebar"); ?>
<?php $conn = xcloneConnectDatabase(); $uname = htmlspecialchars(trim($_SESSION["user_id"])); $row = xclone_get_my_profile($conn, $uname); ?>
<div class="col-md-6">
    <div class="main-xclone-screenline">
        
        <div class="site-header-box">
            <h5>
            <svg id="back-page" viewBox="0 0 24 24" aria-hidden="true"><g><path d="M7.414 13l5.043 5.04-1.414 1.42L3.586 12l7.457-7.46 1.414 1.42L7.414 11H21v2H7.414z"></path></g></svg>
            <?php echo xclone_translate("account_settings"); ?></h5>
        </div>

        <div class="account-settings-page">
            
            <div class="settings-page-container">
                <div class="settings-page-title">
                    <h5><?php echo xclone_translate("account_settings_menu_34"); ?></h5>
                </div>

                <div class="setpage-save-info">
                <?php echo xclone_translate("account_settings_menu_35"); ?>
                </div>

                <div class="form-save-element-display">
                    <input type="radio" class="radio-btn" name="theme" value="master.white.theme" checked> <span><?php echo xclone_translate("account_settings_menu_36"); ?></span>
                    <input type="radio" class="radio-btn" name="theme" value="master.dark.theme"> <span><?php echo xclone_translate("account_settings_menu_37"); ?></span>
                </div>

            </div>
        </div>
    </div>
</div>

<script>
        $('input[name="theme"]').change(function() {
        var theme = $('input[name="theme"]:checked').val();
        var styleUrl = '<?php echo xclone_template_master("style"); ?>/' + theme + '.css';
        $('#style').attr('href', styleUrl);
        $.ajax({
            type: "POST",
            url: "/apps/ajax/settings/display-save.phtml",
            data: { theme: theme },
            success: function() {
            console.log("Changed Xclone template");
            }
        });
        });

        $(document).ready(function() {
        $.ajax({
            type: "GET",
            url: "/apps/ajax/settings/display.phtml",
            success: function(theme) {
            if (theme != null) {
                var styleUrl = '<?php echo xclone_template_master("style"); ?>/' + theme + '.css';
                $('#style').attr('href', styleUrl);
                $('input[name="theme"][value="' + theme + '"]').prop('checked', true);
            }
            }
        });
        });
</script>


<?php xclone_template("main/sidebar/right-sidebar"); ?>
<?php xclone_template("main/footer.content"); ?>