<?php xclone_template("main/sidebar/left-sidebar"); ?>
<?php $conn = xcloneConnectDatabase(); $uname = htmlspecialchars(trim($_SESSION["user_id"])); $row = xclone_get_my_profile($conn, $uname); ?>
<div class="col-md-6">
    <div class="main-xclone-screenline">
        
        <div class="site-header-box">
            <h5>
            <svg id="back-page" viewBox="0 0 24 24" aria-hidden="true"><g><path d="M7.414 13l5.043 5.04-1.414 1.42L3.586 12l7.457-7.46 1.414 1.42L7.414 11H21v2H7.414z"></path></g></svg>
            <?php echo xclone_translate("account_settings"); ?></h5>
        </div>

        <div class="account-settings-page">
            
            <div class="settings-page-container">
                <div class="settings-page-title">
                    <h5><?php echo xclone_translate("account_information"); ?></h5>
                </div>

                <div class="setpage-save-info">
                    <?php echo xclone_translate("account_settings_menu_25"); ?>
                </div>

                <div class="form-save-element-value">
                    <form id="change-fullname">
                        <div class="form-floating">
                            <input type="text" class="form-control" name="fullname" id="fullname" value="<?php echo $row["fullname"]; ?>" placeholder="<?php echo xclone_translate("account_settings_menu_26"); ?>">
                            <label for="fullname">G<?php echo xclone_translate("account_settings_menu_26"); ?></label>
                        </div>
                        <button type="submit" class="fullname-save"><?php echo xclone_translate("account_settings_menu_27"); ?></button>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
    $('#change-fullname').submit(function(event) {
        event.preventDefault();
        if ($('#fullname').val() === '') {
            new Noty({
                type: 'error',
                text: '<?php echo xclone_translate("settings_page_save_value_desc_3"); ?>',
                timeout: 1500
            }).show();
        } else {
            $.ajax({
                type: 'POST',
                url: '/apps/ajax/settings/fullname.phtml',
                data: {
                    fullname: $('#fullname').val()
                },
                success: function(response) {
                    $('#fullname').val(response);
                    new Noty({
                        type: 'success',
                        text: '<?php echo xclone_translate("settings_page_save_value_desc_4"); ?>',
                        timeout: 1500
                    }).show();
                },
                error: function(response) {
                    alert('Hata oluştu: ' + response.responseText);
                }
            });
        }
    });

    $('#fullname').attr('minlength', 1);
    $('#fullname').attr('maxlength', 50);
});
</script>


<?php xclone_template("main/sidebar/right-sidebar"); ?>
<?php xclone_template("main/footer.content"); ?>