<?php xclone_template("main/sidebar/left-sidebar"); ?>
<?php $conn = xcloneConnectDatabase(); $uname = htmlspecialchars(trim($_SESSION["user_id"])); $row = xclone_get_my_profile($conn, $uname); ?>
<div class="col-md-6">
    <div class="main-xclone-screenline">
        
        <div class="site-header-box">
            <h5>
            <svg id="back-page" viewBox="0 0 24 24" aria-hidden="true"><g><path d="M7.414 13l5.043 5.04-1.414 1.42L3.586 12l7.457-7.46 1.414 1.42L7.414 11H21v2H7.414z"></path></g></svg>
            <?php echo xclone_translate("account_settings"); ?></h5>
        </div>

        <div class="account-settings-page">
            
            <div class="settings-page-container">
                <div class="settings-page-title">
                    <h5><?php echo xclone_translate("account_information"); ?></h5>
                </div>

                <div class="setpage-save-info">
                  <?php echo xclone_translate("account_settings_menu_28"); ?>
                </div>

                <div class="form-save-element-value">
                    <form id="change-username">
                        <div class="form-floating">
                            <input type="text" class="form-control" name="username" id="username" value="<?php echo $row["username"]; ?>" placeholder="<?php echo xclone_translate("account_settings_menu_29"); ?>">
                            <label for="username"><?php echo xclone_translate("account_settings_menu_29"); ?></label>
                        </div>
                        <button type="submit" class="username-save"><?php echo xclone_translate("account_settings_menu_27"); ?></button>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>

<script>
    function isValidUsername(username) {
        var validUsernameRegex = /^[a-zA-Z0-9_]{3,15}$/;
        return validUsernameRegex.test(username);
}

$(document).ready(function() {
  $('#username').attr('minlength', 3);
  $('#username').attr('maxlength', 15);

  $('#change-username').submit(function(event) {
    event.preventDefault();
    var username = $.trim($('#username').val());
    if (username.length === 0) {
      new Noty({
        type: 'error',
        text: 'Kullanıcı adı boş bırakılamaz',
        timeout: 1500
      }).show();
      return false;
    }
    if (!isValidUsername(username)) {
      new Noty({
        type: 'error',
        text: 'Kullanıcı adı, yalnızca harfler, sayılar ve alt çizgi içerebilir. Ayrıca, 3-15 karakter uzunluğunda olmalıdır.',
        timeout: 3000
      }).show();
      return false;
    } else {
      $.ajax({
        type: 'POST',
        url: '/apps/ajax/settings/check-username.phtml',
        data: {
          username: username
        },
        success: function(response) {
          if (response === '1') {
            new Noty({
              type: 'error',
              text: '<?php echo xclone_translate("settings_page_save_value_desc_5"); ?>',
              timeout: 3000
            }).show();
          } else {
            $.ajax({
              type: 'POST',
              url: '/apps/ajax/settings/username.phtml',
              data: {
                username: username
              },
              success: function(response) {
                $('#username').val(response);
                new Noty({
                  type: 'success',
                  text: '<?php echo xclone_translate("settings_page_save_value_desc_6"); ?>',
                  timeout: 1500
                }).show();
              },
              error: function(response) {
                alert('Hata oluştu: ' + response.responseText);
              }
            });
          }
        },
        error: function(response) {
          alert('Hata oluştu: ' + response.responseText);
        }
      });
    }
  });
});
</script>


<?php xclone_template("main/sidebar/right-sidebar"); ?>
<?php xclone_template("main/footer.content"); ?>