<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
require_once("../../../core/vipub_web_core.phtml");

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!isset($_SESSION['user_id'])) {
        http_response_code(401);
    
        $response = array(
            'error_code' => 401,
            'error_data' => 'vipub_user_id_is_missing',
            'error_message' => 'User authentication failed!'
        );
        echo json_encode($response);
        exit();
    }
    
    // Gönderi kimliğini alın
    $post_id = mysqli_real_escape_string($conn, $_POST['post_id']);

    // Gönderi türünü ve diğer verileri alın
    $post_type_query = "SELECT post_type, reply_post_id, content_post FROM vipub_posts WHERE p_id = '$post_id'";
    $post_type_result = mysqli_query($conn, $post_type_query);
    $post_type_row = mysqli_fetch_assoc($post_type_result);
    $post_type = $post_type_row['post_type'];
    $reply_post_id = $post_type_row['reply_post_id'];
    $content_post = $post_type_row['content_post'];

    // Gönderiyi silme işlemini gerçekleştirin
    $sql = "DELETE FROM vipub_posts WHERE p_id = ?";
    $stmt = mysqli_prepare($conn, $sql);
    mysqli_stmt_bind_param($stmt, "i", $post_id);

    if (mysqli_stmt_execute($stmt)) {
        // Gönderi başarıyla silindi

        // Hashtag'leri kontrol edin ve güncelleyin
        preg_match_all('/#(\w+)/u', $content_post, $matches);
        $hashtags = $matches[1];

        if (!empty($hashtags)) {
            foreach ($hashtags as $hashtag) {
                $hashtag_name = $hashtag;
                if (strpos($hashtag, '#') === 0) {
                    $hashtag_name = substr($hashtag, 1);
                }

                $query = "SELECT * FROM vipub_hashtag WHERE htag = ?";
                $stmt = mysqli_prepare($conn, $query);
                mysqli_stmt_bind_param($stmt, "s", $hashtag_name);
                mysqli_stmt_execute($stmt);

                $result = mysqli_stmt_get_result($stmt);
                if (mysqli_num_rows($result) > 0) {
                    $row = mysqli_fetch_assoc($result);
                    $update_query = "UPDATE vipub_hashtag SET total_post = total_post - 1 WHERE htag = '$hashtag_name'";
                    if (!mysqli_query($conn, $update_query)) {
                        echo "total_post sayısı güncellenirken hata oluştu: " . mysqli_error($conn);
                    }
                    $total_post = $row['total_post'] - 1;
                    if ($total_post == 0) {
                    $delete_query = "DELETE FROM vipub_hashtag WHERE htag = '$hashtag_name'";
                    if (!mysqli_query($conn, $delete_query)) {
                    echo "Hashtag silinirken hata oluştu: " . mysqli_error($conn);
                    }
                }
            }
        }
    }
        // Yanıt gönderi ise ve yanıtlanan gönderi kimliği mevcutsa yanıt sayısını güncelleyin
        if ($post_type == 'reply' && !empty($reply_post_id)) {
            $update_query = "UPDATE vipub_posts SET reply = reply - 1 WHERE p_id = '$reply_post_id'";
            if (!mysqli_query($conn, $update_query)) {
                echo "Yanıt sayısı güncellenirken hata oluştu: " . mysqli_error($conn);
            }
        }
    
        echo "success";
    } else {
        echo "error";
    }
    
    mysqli_stmt_close($stmt);
} else {
    http_response_code(405);

    $response = array(
        'error_code' => 405,
        'error_data' => 'vipub_invalid_post_deletion',
        'error_message' => 'You have requested an invalid post deletion!'
    );

    echo json_encode($response);
}
    
    mysqli_close($conn);    