<?php vipub_template("main/sidebar/left-sidebar"); ?>
<div class="col-md-6">
    <div class="main-vipub-screenline">
        
        <div class="site-header-box">
            <form action="<?php echo vipub_link("explore"); ?>" method="GET">
                <i class="bi bi-search"></i>
                <input type="text" name="q" placeholder="<?php echo vipub_translate("search_vipub"); ?>" value="<?php echo $_GET["q"]; ?>">
            </form>
            <div class="search-header-menu">
                <a href="<?php echo vipub_link("explore?q=".$_GET["q"]); ?>" class="search-active">
                    <h6><?php echo vipub_translate("profile_menu_1"); ?></h6>
                </a>
                <a href="#">
                    <h6><?php echo vipub_translate("explore_page_menu_name"); ?></h6>
                </a>
            </div>
        </div>

        <div id="get-explore-page-timeline"></div>
    </div>
</div>
<?php vipub_template("search/script/vipub.master.script"); ?>
<?php vipub_template("main/sidebar/right-sidebar"); ?>