<div class="vipub-content-email">
    <div class="container">
        <div class="email-top-logo" style="position: relative; margin-bottom: 12px;">
            <a href="<?php echo vipub_link("home"); ?>">
                <img style="width: 50px; height: 50px;" src="<?php echo vipub_template_master("images/logo.png"); ?>">
            </a>
        </div>

        <div class="email-top-logo" style="position: relative; margin-bottom: 12px;">
            <?php echo $email_body; ?>
        </div>
    </div>
</div>