<?php
require_once("../../../core/xclone_web_core.phtml");

if(isset($_SESSION["user_id"])) {
    if ($_SERVER["REQUEST_METHOD"] == "POST") {
        $user_id = $_SESSION["user_id"];
        $package_id = $_POST["package_id"];
        $end_date = $_POST["end_date"];

        $user_wallet = $_POST["uwal"];
        $premium_account = "1";
        $verified_status = "1";

        $sql = "INSERT INTO xclone_premium_active_users (user_id, package_id, end_date) VALUES ('$user_id', '$package_id', '$end_date')";
        if ($conn->query($sql) === TRUE) {
            // xclone_users tablosunu güncelleme
            $sql_user = "UPDATE xclone_users SET premium_account = '$premium_account', verified = '$verified_status', user_wallet = '$user_wallet' WHERE id = '$user_id'";
            

            if ($conn->query($sql_user) === TRUE) {
                echo "success";
            } else {
                echo "error: " . $conn->error;
            }
        } else {
            echo "error: " . $conn->error;
        }

        // Bağlantıyı kapat
        $conn->close();
    }
} else {
    header("Location: /welcome/login");
}
