<?php
function xclone_site_url($path = '/') {
    $protocol = isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http';
    $base_url = rtrim(dirname($_SERVER['PHP_SELF']), '/\\');
    $url = $protocol . '://' . $_SERVER['HTTP_HOST'] . $base_url . '/';
    if ($path !== null) {
        $url .= ltrim($path, '/');
    }
    return $url;
}

function xclone_link($path) {
    $base_url = (isset($_SERVER['HTTPS']) ? "https" : "http") . "://{$_SERVER['HTTP_HOST']}/";
    $url = $base_url . ltrim($path, '/');
    return $url;
}
function not_empty($value) {
    if (isset($value) && trim($value) !== '') {
      return true;
    } else {
      return false;
    }
}  
function xclone_general_template($file_path) {
    $root_path = "/var/www/html"; // sunucu kök dizini
    $full_path = $root_path . '/' . $file_path;
    
    if (file_exists($full_path)) {
        require_once $full_path;
    } else {
        trigger_error("Hata: Dosya bulunamadı! Dosya yolunuzu kontrol edin: $full_path");
    }
}

function xclone_template($file_path) {
    $root_path = $_SERVER['DOCUMENT_ROOT'];
    $extensions = [".php", ".phtml", ".js"];
    
    foreach ($extensions as $ext) {
        $full_path = $root_path . '/themes/default/apps/' . $file_path . $ext;
        if (file_exists($full_path)) {
            include $full_path;
            return;
        }
    }
    header("Location: /404"); exit();
}

function xclone_admin_template($file_path) {
    $root_path = $_SERVER['DOCUMENT_ROOT'];
    $extensions = [".php", ".phtml", ".js"];
    
    foreach ($extensions as $ext) {
        $full_path = $root_path . '/admin_panel/' . $file_path . $ext;
        if (file_exists($full_path)) {
            include $full_path;
            return;
        }
    }
    die("Böyle bir dosya bulunmamaktadır.");
}

function xclone_apps_native($file_path) {
    $root_path = $_SERVER['DOCUMENT_ROOT'];
    $extensions = [".php", ".phtml", ".js"];
    
    foreach ($extensions as $ext) {
        $full_path = $root_path . '/apps/native/' . $file_path . $ext;
        if (file_exists($full_path)) {
            require_once $full_path;
            return;
        }
    }
    die("Böyle bir dosya bulunmamaktadır.");
}

function xclone_template_master($path = '/') {
    $protocol = isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http';
    $base_url = rtrim('/themes/default/statics/', '/\\');
    $url = $protocol . '://' . $_SERVER['HTTP_HOST'] . $base_url . '/' . ltrim($path, '/');
    return $url;
}
function xclone_translate($key) {
    global $xcloneTranslate;
    return $xcloneTranslate[$key] ?? $key;
}  
  
function xclone_siteDisplay() {
    $app = isset($_GET['app']) ? $_GET['app'] : 'home';
    switch ($app) {
        case 'login':
            if(!isset($_SESSION["user_id"])){
                xclone_template("auth/login");
            } else {
                header("Location: /404");
            }
            break;
        case 'register':
            if(!isset($_SESSION["user_id"])){
                xclone_template("auth/register");
            } else {
                header("Location: /404");
            }
            break;
        case 'refresh_password':
            if(!isset($_SESSION["user_id"])){
                xclone_template("auth/refresh_password");
            } else {
                header("Location: /404");
            }
            break;
        case 'new_password':
            if(!isset($_SESSION["user_id"])){
                xclone_template("auth/new_password");
            } else {
                header("Location: /404");
            }
            break;
        case 'home':
            if(!isset($_SESSION["user_id"])){
                header("Location: /welcome/login");
            } else {
                xclone_template("home/content");
            }
            
            $user_agent = $_SERVER['HTTP_USER_AGENT'];
            if (preg_match('/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge\s|maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i', $user_agent) || preg_match('/(tablet|ipad|playbook)|(android(?!.*mobile))/i', $user_agent)) {
                xclone_template("main/sidebar/mobile_menu");
            }
            break;
        case 'connect_people':
            if(!isset($_SESSION["user_id"])){
                header("Location: /welcome/login");
            }
            xclone_template("connect_people/content");
            $user_agent = $_SERVER['HTTP_USER_AGENT'];
            if (preg_match('/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge\s|maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i', $user_agent) || preg_match('/(tablet|ipad|playbook)|(android(?!.*mobile))/i', $user_agent)) {
                xclone_template("main/sidebar/mobile_menu");
            }
            break;
        case 'settings':
            if(!isset($_SESSION["user_id"])){
                header("Location: /welcome/login");
            }
            if (isset($_GET["sapp"])) {
                $sapp = $_GET["sapp"];
                echo '<title>'.xclone_translate("settings_title").'</title>';
                xclone_template("settings/pages/".$sapp);
                
                $user_agent = $_SERVER['HTTP_USER_AGENT'];
                if (preg_match('/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge\s|maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i', $user_agent) || preg_match('/(tablet|ipad|playbook)|(android(?!.*mobile))/i', $user_agent)) {
                    xclone_template("main/sidebar/mobile_menu");
                }
            } else {
                xclone_template("settings/content");

                $user_agent = $_SERVER['HTTP_USER_AGENT'];
                if (preg_match('/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge\s|maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i', $user_agent) || preg_match('/(tablet|ipad|playbook)|(android(?!.*mobile))/i', $user_agent)) {
                    xclone_template("main/sidebar/mobile_menu");
                }
            }
            break;

        case 'business':
            if(!isset($_SESSION["user_id"])){
                header("Location: /welcome/login");
            }
            if (isset($_GET["sapp"])) {
                $sapp = $_GET["sapp"];
                echo '<title>'.xclone_translate("settings_title").'</title>';
                xclone_template("business/pages/".$sapp);
                
                $user_agent = $_SERVER['HTTP_USER_AGENT'];
                if (preg_match('/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge\s|maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i', $user_agent) || preg_match('/(tablet|ipad|playbook)|(android(?!.*mobile))/i', $user_agent)) {
                    xclone_template("main/sidebar/mobile_menu");
                }
            } else {
                xclone_template("business/content");

                $user_agent = $_SERVER['HTTP_USER_AGENT'];
                if (preg_match('/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge\s|maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i', $user_agent) || preg_match('/(tablet|ipad|playbook)|(android(?!.*mobile))/i', $user_agent)) {
                    xclone_template("main/sidebar/mobile_menu");
                }
            }
            break;

        case 'profile':
            if (isset($_GET["uname"])) {
                $conn = xcloneConnectDatabase();
                $username = $_GET["uname"];
                $user_query = "SELECT fullname, username, account_status FROM xclone_users WHERE username = '$username'";
                $user_result = mysqli_query($conn, $user_query);
                
                if (mysqli_num_rows($user_result) > 0) {
                    $user_row = mysqli_fetch_assoc($user_result);
                    $fullname = $user_row["fullname"];
                    $username = $user_row["username"];
                    
                    if ($user_row["account_status"] == 0) {
                        xclone_template("profile/content");
                    } else if ($user_row["account_status"] == 1) {
                        xclone_template("profile/include/banned-profile");
                    }

                    $user_agent = $_SERVER['HTTP_USER_AGENT'];
                    if (preg_match('/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge\s|maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i', $user_agent) || preg_match('/(tablet|ipad|playbook)|(android(?!.*mobile))/i', $user_agent)) {
                        xclone_template("main/sidebar/mobile_menu");
                    }
                } else {
                    xclone_template("profile/include/no-profile");
                    $user_agent = $_SERVER['HTTP_USER_AGENT'];
                    if (preg_match('/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge\s|maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i', $user_agent) || preg_match('/(tablet|ipad|playbook)|(android(?!.*mobile))/i', $user_agent)) {
                        xclone_template("main/sidebar/mobile_menu");
                    }
                }
            } else {
                echo 'Profil bulunamadı.';

                $user_agent = $_SERVER['HTTP_USER_AGENT'];
                if (preg_match('/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge\s|maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i', $user_agent) || preg_match('/(tablet|ipad|playbook)|(android(?!.*mobile))/i', $user_agent)) {
                    xclone_template("main/sidebar/mobile_menu");
                }
            }
            break;
        case 'notifications':
            if(!isset($_SESSION["user_id"])){
                header("Location: /404");
            }
            echo '<title>'.xclone_translate("notifications_title").'</title>';
            xclone_template("notifications/content");
            $user_agent = $_SERVER['HTTP_USER_AGENT'];
            if (preg_match('/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge\s|maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i', $user_agent) || preg_match('/(tablet|ipad|playbook)|(android(?!.*mobile))/i', $user_agent)) {
                xclone_template("main/sidebar/mobile_menu");
            }
            break;
        case 'messages':
            if(!isset($_SESSION["user_id"])){
                header("Location: /404");
            }
            if (isset($_GET["row"])) {
                $conn = xcloneConnectDatabase();
                $user_id = htmlspecialchars(trim($_GET["row"]));
                $row = xclone_get_message_user($conn, $user_id);
                if ($row !== null && !empty($row)) {
                    echo '<title>'.$row["fullname"].' '.xclone_translate("profile_title").'</title>';
                    xclone_template("messages/include/send-chat");
                } else {
                    xclone_template("profile/include/no-profile");
                }
            }
            else {
                echo '<title>'.xclone_translate("messages_title").'</title>';
                xclone_template("messages/content");
                $user_agent = $_SERVER['HTTP_USER_AGENT'];
                if (preg_match('/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge\s|maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i', $user_agent) || preg_match('/(tablet|ipad|playbook)|(android(?!.*mobile))/i', $user_agent)) {
                    xclone_template("main/sidebar/mobile_menu");
                }
            }
            break;
        case 'status':
            xclone_template("status/content");

            $user_agent = $_SERVER['HTTP_USER_AGENT'];
            if (preg_match('/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge\s|maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i', $user_agent) || preg_match('/(tablet|ipad|playbook)|(android(?!.*mobile))/i', $user_agent)) {
                xclone_template("main/sidebar/mobile_menu");
            }
            break;
        case '404':
            xclone_template("404/content");

            $user_agent = $_SERVER['HTTP_USER_AGENT'];
            if (preg_match('/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge\s|maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i', $user_agent) || preg_match('/(tablet|ipad|playbook)|(android(?!.*mobile))/i', $user_agent)) {
                xclone_template("main/sidebar/mobile_menu");
            }
            break;
        case 'search':
            xclone_template("search/content");
            $user_agent = $_SERVER['HTTP_USER_AGENT'];
            if (preg_match('/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge\s|maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i', $user_agent) || preg_match('/(tablet|ipad|playbook)|(android(?!.*mobile))/i', $user_agent)) {
                xclone_template("main/sidebar/mobile_menu");
            }
            break;
        case 'likes':
            xclone_template("timeline/include/like-list");
            $user_agent = $_SERVER['HTTP_USER_AGENT'];
            if (preg_match('/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge\s|maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i', $user_agent) || preg_match('/(tablet|ipad|playbook)|(android(?!.*mobile))/i', $user_agent)) {
                xclone_template("main/sidebar/mobile_menu");
            }
            break;
        case 'explore':
            xclone_template("search/explore-content");
            $user_agent = $_SERVER['HTTP_USER_AGENT'];
            if (preg_match('/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge\s|maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i', $user_agent) || preg_match('/(tablet|ipad|playbook)|(android(?!.*mobile))/i', $user_agent)) {
                xclone_template("main/sidebar/mobile_menu");
            }
            break;
        case 'pages':
            xclone_template("pages/content");

            if(isset($_SESSION["user_id"])){
                $user_agent = $_SERVER['HTTP_USER_AGENT'];
                if (preg_match('/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge\s|maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i', $user_agent) || preg_match('/(tablet|ipad|playbook)|(android(?!.*mobile))/i', $user_agent)) {
                    xclone_template("main/sidebar/mobile_menu");
                }
            }
            break;
        case 'following':
            if (isset($_GET["username"])) {
                xclone_template("profile/pages/following");
            }
            $user_agent = $_SERVER['HTTP_USER_AGENT'];
            if (preg_match('/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge\s|maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i', $user_agent) || preg_match('/(tablet|ipad|playbook)|(android(?!.*mobile))/i', $user_agent)) {
                xclone_template("main/sidebar/mobile_menu");
            }
            break;
        case 'followers':
            if (isset($_GET["username"])) {
                xclone_template("profile/pages/followers");
            }

            $user_agent = $_SERVER['HTTP_USER_AGENT'];
            if (preg_match('/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge\s|maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i', $user_agent) || preg_match('/(tablet|ipad|playbook)|(android(?!.*mobile))/i', $user_agent)) {
                xclone_template("main/sidebar/mobile_menu");
            }
            break;
        case 'media':
            if (isset($_GET["username"])) {
                xclone_template("profile/pages/media");
            }

            $user_agent = $_SERVER['HTTP_USER_AGENT'];
            if (preg_match('/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge\s|maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i', $user_agent) || preg_match('/(tablet|ipad|playbook)|(android(?!.*mobile))/i', $user_agent)) {
                xclone_template("main/sidebar/mobile_menu");
            }
            break;
        default:
            xclone_template("auth/login");
            break;
    }
}

function xclone_directFiles($filepath) {
    $ext = pathinfo($filepath, PATHINFO_EXTENSION);
    if($ext !== 'php' && $ext !== 'phtml') {
        $filepath .= '.php';
    }
    require_once($_SERVER['DOCUMENT_ROOT'].'/'.$filepath);
}

function convertxcloneText($text) 
{ 
    // 1. URL'leri bağlantılara dönüştürmek için kullanılır.
    $text = preg_replace("/(^|[\n ])([\w]*?)([\w]*?:\/\/[\w]+[^ \,\"\n\r\t<]*)/is",
        "$1$2<a target=\"_blank\" href=\"$3\" >$3</a>", $text);  
    
    // 2. "www" ile başlayan URL'leri bağlantılara dönüştürmek için kullanılır.
    $text = preg_replace("/(^|[\n ])([\w]*?)((www)\.[^ \,\"\t\n\r<]*)/is",
        "$1$2<a target=\"_blank\" href=\"https://$3\" >$3</a>", $text);
    
    // 4. Hashtag'leri bağlantılara dönüştürmek için kullanılır.
    $hash_regex = "/#([a-zA-Z0-9çÇğĞıİöÖşŞüÜ]+)/s";
    $text = preg_replace($hash_regex, '<a href="/explore?q=$1">#$1</a>', $text);

    // 3. @mention'ları tespit etmek için bir regex ifadesi kullanılıyor.
    $user_profile_regex = "/\B\@([a-zA-Z0-9_]{3,15})/";
    $text = preg_replace($user_profile_regex, '<a href="/@$1">@$1</a>', $text);
    
    // 5. YouTube videolarını bir iframe içinde göstermek için kullanılır.
    $text = preg_replace('/\s*[a-zA-Z\/\/:\.]*youtu(be.com\/watch\?v=|.be\/)([a-zA-Z0-9\-_]+)([a-zA-Z0-9\/\*\-\_\?\&\;\%\=\.]*)/',
        '<iframe src=\'//www.youtube.com/embed/$2\' allowfullscreen></iframe>', $text );
    return $text;  
}


function xclone_ajax_query($url) {
    switch($url) {
      case "xclone/native_api/rsbr-search":
        return "/apps/ajax/rsbr-search.php";
        break;
    case "xclone/native_api/userlogin":
        return "/apps/ajax/login.php";
        break;
    case "xclone/native_api/usersignup":
        return "/apps/ajax/register.php";
        break;
    case "xclone/native_api/rsbr-htags":
        return "/apps/ajax/rsbr-htags.php";
        break;
      default:
        return $url;
        break;
    }
  }

function xclone_get_user_profile($conn, $uname) {
    $username = trim($uname);
    $sql = "SELECT * FROM xclone_users WHERE username='".$uname."'";
    $result = mysqli_query($conn, $sql);
    if (mysqli_num_rows($result) > 0){
        while ($profile = mysqli_fetch_assoc($result)) {
            $userId = $profile["id"];
            $fullname = $profile["fullname"];
            $username = $profile["username"];
            $joined = $profile["joined"];
            return array("id"=>$userId, "fullname"=>$fullname, "username"=>$username, "joined"=>$joined);
        }
    } else {
        return null;
    }
}

function xclone_redirect($url) {
    if (!headers_sent()) {
        header("Location: " . $url);
        exit;
    } else {
        echo "<script type='text/javascript'>";
        echo "window.location.href='" . $url . "';";
        echo "</script>";
        echo "<noscript>";
        echo "<meta http-equiv='refresh' content='0;url=" . $url . "' />";
        echo "</noscript>";
        exit;
    }
}
function xcloneConnectDatabase() {
    global $xclone, $xclone_db_host, $xclone_db_user, $xclone_db_pass, $xclone_db_name;
    $conn = new mysqli($xclone_db_host, $xclone_db_user, $xclone_db_pass, $xclone_db_name);
    if (mysqli_connect_errno()) {
        array_push($xclone["xclone_db_errors"], mysqli_connect_error());
        if (not_empty($xclone["xclone_db_errors"])) {
            echo "Error Database.";
            die();
        }
    }
    return $conn;
}

function xclone_date($date) {
    return date("M Y", strtotime($date));
}
function xclone_save_media($file) {
    $uploadDir = $_SERVER['DOCUMENT_ROOT'] . '/upload/';
    $fileName = uniqid() . '_' . $file['name'];
    $targetFile = $uploadDir . $fileName;

    if (move_uploaded_file($file['tmp_name'], $targetFile)) {
        return $uploadDir . $fileName;
    } else {
        return false;
    }
}
function xclone_back_page() {
    if (isset($_SERVER['HTTP_REFERER'])) {
        $back_page = $_SERVER['HTTP_REFERER'];
    } else {
        $back_page = '/';
    }
    return $back_page;
}
function xclone_count($count) {
    if ($count < 1000) {
        return $count;
    } else if ($count < 1000000) {
        return round($count / 1000, 1) . 'K';
    } else if ($count < 1000000000) {
        return round($count / 1000000, 1) . 'M';
    } else {
        return round($count / 1000000000, 1) . 'B';
    }
}
function xclone_site_settings() {
    global $conn;
    $site_general_settings = mysqli_query($conn, "SELECT * FROM xclone_settings");
    $settings = mysqli_fetch_array($site_general_settings);
    return $settings;
}
function xclone_smtp() {
    global $conn;
    $site_smtp_settings = mysqli_query($conn, "SELECT * FROM xclone_smtp");
    $smtp_settings = mysqli_fetch_array($site_smtp_settings);
    return $smtp_settings;
}
function xclone_dynamicTitle() {
    $app = isset($_GET['app']) ? $_GET['app'] : 'home';
    $title = '';
    switch ($app) {
        case 'home':
            $title = xclone_translate("homepage_title");
            break;
        case 'notifications':
            $title = xclone_translate("notifications_title");
            break;
        case 'messages':
            $title = xclone_translate("messages_title");
            break;
        case 'search':
            $title = xclone_translate("search_title");
            break;
        case 'likes':
            $title = xclone_translate("status_page_post_like_reply_repost_2").xclone_translate("profile_title");
            break;
        case 'explore':
            $title = "(".$_GET["q"].") ". xclone_translate("search_title");
            break;
        case 'settings':
            $title = xclone_translate("settings_title");
            break;
        case 'following':
            $title = xclone_translate("following_followers_title_1");
            break;
        case 'followers':
            $title = xclone_translate("following_followers_title_2");
            break;
        case 'pages':
            $conn = xcloneConnectDatabase();
            $page_title_seo = htmlspecialchars(trim($_GET["page_title_seo"]));
            $stmt = $conn->prepare("SELECT page_title, page_title_seo FROM xclone_pages WHERE page_title_seo = ?");
            $stmt->bind_param("s", $page_title_seo);
            $stmt->execute();
            $get_page = $stmt->get_result();
        
            if ($get_page->num_rows > 0) {
                $pages = $get_page->fetch_assoc();
                $page_title = $pages["page_title"];
            } else {
                return "404 Page";
            }
        
            $title = $page_title . xclone_translate("profile_title");
            break;
        case 'status':
            $conn = xcloneConnectDatabase();
            $stmt = $conn->prepare("SELECT id, fullname FROM xclone_users WHERE username = ?");
            $stmt->bind_param("s", $_GET["uname"]);
            $stmt->execute();
            $user_result = $stmt->get_result();
        
            if ($user_result->num_rows > 0) {
                $user_row = $user_result->fetch_assoc();
                $user_id = $user_row["id"];
                $full_name = $user_row["fullname"];
            } else {
                return "404 Page";
            }
        
            $stmt = $conn->prepare("SELECT content_post FROM xclone_posts WHERE p_id = ? AND user_id = ?");
            $stmt->bind_param("ii", $_GET["status_id"], $user_id);
            $stmt->execute();
            $status_result = $stmt->get_result();
        
            if ($status_result->num_rows > 0) {
                $status_row = $status_result->fetch_assoc();
                $content_post = $status_row["content_post"];
            } else {
                return "404 Page";
            }
        
            $title = $full_name . " " . xclone_translate("on_xclone_status_title") . ' "' . $content_post . '"';
            break;            
        case '404':
            $title = xclone_translate("404_page_title");
            break;
        case 'profile':
            if (isset($_GET["uname"])) {
                $conn = xcloneConnectDatabase();
                $username = $_GET["uname"];
                $user_query = "SELECT fullname, username FROM xclone_users WHERE username = '$username'";
                $user_result = mysqli_query($conn, $user_query);
                if (mysqli_num_rows($user_result) > 0) {
                    $user_row = mysqli_fetch_assoc($user_result);
                    $fullname = $user_row["fullname"];
                    $username = $user_row["username"];
                    $title = $fullname . (" (@".$username.")") . xclone_translate("profile_title");
                }
            }
            break;
        case 'media':
            if (isset($_GET["profuname"])) {
                $conn = xcloneConnectDatabase();
                $username = $_GET["profuname"];
                $user_query = "SELECT fullname, username FROM xclone_users WHERE username = '$username'";
                $user_result = mysqli_query($conn, $user_query);
                if (mysqli_num_rows($user_result) > 0) {
                    $user_row = mysqli_fetch_assoc($user_result);
                    $fullname = $user_row["fullname"];
                    $username = $user_row["username"];
                    $title = $fullname . (" (@".$username.")") . " " . xclone_translate("user_profile_media_timeline_title") . xclone_translate("profile_title");
                }
            }
            break;
        case 'login':
            $title = xclone_translate("welcome_page_text_1").xclone_translate("profile_title");
            break;
        case 'register':
            $title = xclone_translate("welcome_page_text_8").xclone_translate("profile_title");
            break;
        case 'refresh_password':
            $title = xclone_translate("refresh_password_title").xclone_translate("profile_title");
            break;
        case 'new_password':
            $title = xclone_translate("new_password_title").xclone_translate("profile_title");
            break;
        case 'connect_people':
            $title = xclone_translate("who_to_follow_title").xclone_translate("profile_title");
            break;
        default:
            $title = xclone_translate("404_page_title");
            break;
    }
    return "<title>$title</title>";
}
function xclone_croptxt($text, $start, $length) {
    if (strlen($text) > $length) {
        return substr($text, $start, $length) . "...";
    } else {
        return $text;
    }
}
function xclone_site_settings2($conn) {
    $sql = "SELECT * FROM xclone_settings";
    $result = mysqli_query($conn, $sql);
    $settings = array();

if (mysqli_num_rows($result) > 0) {
    while($row = mysqli_fetch_assoc($result)) {
        $settings['site_title'] = $row["site_title"];
        $settings['site_description'] = $row["site_description"];
        $settings['site_keywords'] = $row["site_keywords"];
        $settings['site_register_status'] = $row["site_register_status"];
        $settings['site_white_logo'] = $row["site_white_logo"];
        $settings['site_dark_logo'] = $row["site_dark_logo"];
        $settings['site_favicon'] = $row["site_favicon"];
        $settings['default_theme'] = $row["default_theme"];
        $settings['post_maxlength'] = $row["post_maxlength"];
    }
}
mysqli_close($conn);
return $settings;
}
function xclone_dont_profile_name() {
    $url = $_SERVER['REQUEST_URI'];
    $url = explode('/', $url);
    $nouser = array_pop($url);
    return $nouser;
}
function xclone_seolink($text){
	$find = array("/Ğ/","/Ü/","/Ş/","/İ/","/Ö/","/Ç/","/ğ/","/ü/","/ş/","/ı/","/ö/","/ç/");
	$degis = array("G","U","S","I","O","C","g","u","s","i","o","c");
	$text = preg_replace("/[^0-9a-zA-ZÄzÜŞİÖÇğüşıöç]/"," ",$text);
	$text = preg_replace($find,$degis,$text);
	$text = preg_replace("/ +/"," ",$text);
	$text = preg_replace("/ /","-",$text);
	$text = preg_replace("/\s/","",$text);
	$text = strtolower($text);
	$text = preg_replace("/^-/","",$text);
	$text = preg_replace("/-$/","",$text);
	return $text;
}
function xclone_wallet_balance($balance) {
    return number_format($balance, 2, ',', '.');
}
function xclone_user_acceptLanguage() {
    echo substr($_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 2);
}