<?php
require_once("../../../core/xclone_web_core.phtml");
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
$smtp_settings = xclone_smtp();

if (!isset($_SESSION["user_id"])) {
  header("Location: /welcome/login");
  exit;
}

if (!isset($_POST["post_id"])) {
  echo "error";
  exit();
}

$post_id = $_POST["post_id"];
$user_id = $_SESSION["user_id"];
$post_user_id = $_POST["post_user_id"];

$query = "SELECT * FROM xclone_repost WHERE repost_user_id = ? AND repost_post_id = ?";
$stmt = $conn->prepare($query);
$stmt->bind_param("ii", $user_id, $post_id);
$stmt->execute();
$result = $stmt->get_result();

if ($result->num_rows == 0) {
  $query = "INSERT INTO xclone_repost (repost_user_id, repost_post_id) VALUES (?, ?)";
  $stmt = $conn->prepare($query);
  $stmt->bind_param("ii", $user_id, $post_id);
  $stmt->execute();

  $owner_tweet_account = "SELECT * FROM xclone_posts WHERE p_id = '$post_id'";
  $owner_tweet_account2 = mysqli_query($conn, $owner_tweet_account);
  $tweet_owner = mysqli_fetch_assoc($owner_tweet_account2);  

  $email_like_notification = "SELECT * FROM xclone_users WHERE id = '".$tweet_owner["user_id"]."'";
  $send_user_email_like_notifications = mysqli_query($conn, $email_like_notification);
  $receiver_user = mysqli_fetch_assoc($send_user_email_like_notifications);

  $email_like_notification2 = "SELECT * FROM xclone_users WHERE id = '$user_id'";
  $send_user_email_like_notifications2 = mysqli_query($conn, $email_like_notification2);
  $my_user_owner = mysqli_fetch_assoc($send_user_email_like_notifications2);

  $like_post_detail_sql = "SELECT * FROM xclone_posts WHERE p_id = '$post_id'";
  $sql_conn_details = mysqli_query($conn, $like_post_detail_sql);
  $like_row = mysqli_fetch_assoc($sql_conn_details);

  $query = "UPDATE xclone_posts SET repost = repost + 1 WHERE p_id = ?";
  $stmt = $conn->prepare($query);
  $stmt->bind_param("i", $post_id);
  $stmt->execute();

  $query = "SELECT repost FROM xclone_posts WHERE p_id = ?";
  $stmt = $conn->prepare($query);
  $stmt->bind_param("i", $post_id);
  $stmt->execute();
  $result = $stmt->get_result();
  $row = $result->fetch_assoc();
  $repost = $row["repost"];

  echo json_encode(["status" => "success", "repost_count" => $repost]);
} else {
  $query = "DELETE FROM xclone_repost WHERE repost_user_id = ? AND repost_post_id = ?";
  $stmt = $conn->prepare($query);
  $stmt->bind_param("ii", $user_id, $post_id);
  $stmt->execute();

  $query = "UPDATE xclone_posts SET repost = repost - 1 WHERE p_id = ?";
  $stmt = $conn->prepare($query);
  $stmt->bind_param("i", $post_id);
  $stmt->execute();

  $query = "SELECT repost FROM xclone_posts WHERE p_id = ?";
  $stmt = $conn->prepare($query);
  $stmt->bind_param("i", $post_id);
  $stmt->execute();
  $result = $stmt->get_result();
  $row = $result->fetch_assoc();
  $repost = $row["repost"];
  
  echo json_encode(["status" => "success", "repost_count" => $repost]);
}

$stmt->close();
$conn->close();