<?php if(isset($_SESSION["user_id"])): $settings = vipub_site_settings(); ?>
<?php $app = isset($_GET['app']) ? $_GET['app'] : 'home';?>
<?php $vipub["account"] = vipub_my_user_info(); ?>
<div class="col-md-3">
    <div class="main-left-sidebar message-page-left-sidebar">
        <div class="main-site-logo">
            <a href="<?php echo vipub_link("home"); ?>">
                <img src="<?php echo vipub_link("themes/default/statics/images/pagelogo.png"); ?>">
            </a>
            </div>
            
            <div class="main-sidebar-menu">
                <a class="<?php echo ($app == 'home') ? 'page-active' : ''; ?>" href="<?php echo vipub_link("home"); ?>">
                    <i class="bi bi-house-door"></i>
                </a>

                <a class="<?php echo ($app == 'search') ? 'page-active' : ''; ?>" href="<?php echo vipub_link("search"); ?>">
                    <i class="bi bi-search"></i>
                </a>

                <a class="<?php echo ($app == 'notifications') ? 'page-active' : ''; ?>" href="<?php echo vipub_link("notifications"); ?>">
                    <span id="check-notifs"></span>
                    <i class="bi bi-bell"></i>
                </a>

                <a class="<?php echo ($app == 'messages') ? 'page-active' : ''; ?>" href="<?php echo vipub_link("messages"); ?>">
                    <span id="check-message"></span>
                    <i class="bi bi-envelope"></i>
                </a>

                <a class="<?php echo ($app == 'bookmarks') ? 'page-active' : ''; ?>" href="<?php echo vipub_link("bookmarks"); ?>">
                    <i class="bi bi-bookmark"></i>
                </a>

                <a  href="<?php echo vipub_link("home"); ?>" id="openedCreatePost">
                    <i class="bi bi-pencil-square"></i>
                </a>

                <?php if($vipub["account"]["admin_status"]=="1"): ?>
                <a href="<?php echo vipub_link("admin_panel"); ?>">
                    <i class="bi bi-sliders"></i>
                </a>
                <?php endif; ?>
            </div>

            <div class="main-sidebar-menu-fixed-bottom message-page-sidebarMore-menu">
                <a href="<?php echo vipub_link("/@".$vipub["account"]["username"]); ?>">
                    <i class="bi bi-person"></i>
                </a>
            </div>
    </div>
</div>
        

    <div id="report-a-problem">
        <div class="report-title-and-close">
            <h5>
                <?php echo vipub_translate("report_a_problem"); ?>
                <i id="close-dropdown" class="bi bi-x-circle-fill"></i>
            </h5>
        </div>
        <form id="reportProblemForm" method="post">
            <div class="report-a-content-form">
                <textarea name="report_content" id="report_content" placeholder="<?php echo vipub_translate("please_give_as_much_information_as_possible"); ?>"></textarea>
            </div>

            <div class="report-form-buttons">
                <button type="submit" name="submitProblem">
                    <?php echo vipub_translate("submit_a_complaint"); ?>
                </button>

                <span id="add_image">
                    <input type="file" name="add_image" id="add_image" style="display:none;">
                    <?php echo vipub_translate("add_file"); ?>
                </span>
            </div>

            <div class="report-a-reviwed-form-info-text">
                <span><?php echo vipub_translate("report_a_problem_bottom_info_text"); ?></span>
            </div>
        </form>
    </div>
    
<script>
    $(document).ready(function() {
        function updateNotifications() {
            $.ajax({
            type: "POST",
            url: "/apps/ajax/notifications/notifs-control.phtml",
            dataType: "json",
            success: function(data) {
                if(data.count > 0) {
                $("#check-notifs").html(data.count).show();
                } else {
                $("#check-notifs").hide();
                }
            },
            error: function() {
                $("#check-notifs").hide();
            }
            });
        }
        updateNotifications();
        setInterval(function() {
            updateNotifications();
        }, 2000);
    });
</script>
    
<script>
    $(document).ready(function() {
        function updateNotifications() {
            $.ajax({
            type: "POST",
            url: "/apps/ajax/messages/notifs-messages.phtml",
            dataType: "json",
            success: function(data) {
                if(data.count > 0) {
                $("#check-message").html(data.count).show();
                } else {
                $("#check-message").hide();
                }
            },
            error: function() {
                $("#check-message").hide();
            }
            });
        }
        updateNotifications();
        setInterval(function() {
            updateNotifications();
        }, 2000);
    });
</script>

<script>
    $(document).on('click', '[data-vipub-url]', function() {
        var url = $(this).data('vipub-url');
        window.location.href = url;
    });
</script>
<?php endif; ?>