<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
require_once("../../../core/xclone_web_core.phtml");
header('Content-type: application/json');

$sql = "SELECT p.*, u.* 
  FROM xclone_posts p 
  JOIN xclone_users u ON p.user_id = u.id 
  WHERE (p.user_id = ? OR p.user_id IN (
    SELECT user_id FROM xclone_follow WHERE follower_id = ?
  )) 
  AND p.post_type = 'post' OR p.post_type = 'postAds' OR p.post_type = 'repost'
  ORDER BY p.post_joined DESC";
$stmt = mysqli_prepare($conn, $sql);

$user_id = $_SESSION["user_id"];
mysqli_stmt_bind_param($stmt, "ii", $user_id, $user_id);
mysqli_stmt_execute($stmt);
$result = mysqli_stmt_get_result($stmt);

if ($result) {
  if (mysqli_num_rows($result) > 0) {
    $response = array();
    while ($row = mysqli_fetch_assoc($result)) {
      $postId = $row["p_id"];
      $userId = $row["user_id"];
      $username = $row["username"];
      $fullname = $row["fullname"];
      $avatar = $row["avatar"];
      $content = $row["content_post"];

      $post = array(
        "post_id" => $postId,
        "user_id" => $userId,
        "screen_name" => $fullname,
        "username" => $username,
        "avatar" => $avatar,
        "tweet" => $content
      );
      array_push($response, $post);
    }
    $json_response = json_encode($response);
    echo $json_response;
  } else {
    xclone_template("timeline/include/no-post");
}
} else {
die("Error: " . mysqli_error($conn));
}
mysqli_stmt_close($stmt);
mysqli_close($conn);