<?php
// Hata raporlaması ve hataların görüntülenmesi
error_reporting(E_ALL);
ini_set('display_errors', 1);

// Gerekli dosyaların dahil edilmesi
require_once("../../../core/vipub_web_core.phtml");

// İstek yönlendirme ve çıkış durumu
if (vipub_userLogin()) {
    header("Location: /home");
    exit;
}

// Kullanıcı adı ve şifrenin alınması
$username = isset($_POST["username"]) ? $_POST["username"] : null;
$password = isset($_POST["password"]) ? $_POST["password"] : null;

if ($username && $password) {

    // Kullanıcı adı ve şifrenin güvenli hale getirilmesi
    $username = mysqli_real_escape_string($conn, $username);
    $password_hashed = sha1(mysqli_real_escape_string($conn, $password));

    // Kullanıcı bilgilerinin veritabanında kontrol edilmesi
    $sql = "SELECT * FROM vipub_users WHERE (username='$username' OR email='$username') AND password='$password_hashed'";
    $result = mysqli_query($conn, $sql);

    if (mysqli_num_rows($result) > 0) {
        $row = mysqli_fetch_assoc($result);

        if ($row['account_status'] == '1') {
            $response = array("status" => "banned", "message" => "Hesabınız askıya alınmıştır.");
        } else {
            // Oturum bilgilerinin kaydedilmesi
            session_start();
            $_SESSION["user_id"] = $row["id"];
            $_SESSION["fullname"] = $row["fullname"];
            $_SESSION["email"] = $row["email"];
            $_SESSION["joined"] = $row["joined"];
            $_SESSION["username"] = $row["username"];
            
            $response = array("status" => "success", "message" => "Giriş başarılı.", "data" => $_SESSION);
        }
    } else {
        $sql = "SELECT * FROM vipub_users WHERE (username='$username' OR email='$username')";
        $result = mysqli_query($conn, $sql);

        if (mysqli_num_rows($result) > 0) {
            $response = array("status" => "error", "message" => "Hatalı şifre girdiniz.");
        } else {
            $response = array("status" => "username_error", "message" => "Kullanıcı adı veya e-posta bulunamadı.");
        }
    }
} else {
    $response = array("status" => "error", "message" => "Kullanıcı adı ve şifre gereklidir.");
}

// Veritabanı bağlantısının kapatılması
mysqli_close($conn);

// Yanıtın JSON formatında dönüştürülerek gönderilmesi
header("Content-Type: application/json");
echo json_encode($response);
?>
