<div class="no-post-yet-timeline">
    <div class="no-post-yet">
        <i class="bi bi-calendar2-range"></i>
        <h5><?php echo xclone_translate("no_post_yet"); ?></h5>
        <span><?php echo xclone_translate("no_post_yet_2"); ?></span>
        <a href="<?php echo xclone_link("connect_people"); ?>">
            <?php echo xclone_translate("no_post_yet_button_follow_the_people"); ?>
        </a>
    </div>
</div>