<?php if(isset($_SESSION["user_id"])): ?>
<?php $xclone["account"] = xclone_my_user_info(); $settings = xclone_site_settings(); ?>
<form id="xclone-new-post" enctype="multipart/form-data">
    <div class="homepage-new-post">
        <a href="<?php echo xclone_site_url("@".$xclone["account"]["username"]); ?>">
            <img src="<?php echo xclone_site_url($xclone["account"]["avatar"]); ?>">
        </a>
        <textarea name="content_post" id="content_post" placeholder="<?php echo xclone_translate("whats_going_on"); ?>" class="xcloneEmojiContent"></textarea>
        <span id="xclone-counter"></span>
    </div>

    <?php if($settings["upload_image"]=="Active"): ?>
    <div class="displayImage">
        <span class="removeImage">
            <svg viewBox="0 0 24 24" aria-hidden="true"><g><path d="M10.59 12L4.54 5.96l1.42-1.42L12 10.59l6.04-6.05 1.42 1.42L13.41 12l6.05 6.04-1.42 1.42L12 13.41l-6.04 6.05-1.42-1.42L10.59 12z"></path></g></svg>
        </span>
    </div>
    <?php endif; ?>

    <?php if($settings["upload_video"]=="Active"): ?>
        <div class="displayVideo">
            <span class="removeVideo" style="display:none">
                <svg viewBox="0 0 24 24" aria-hidden="true"><g><path d="M10.59 12L4.54 5.96l1.42-1.42L12 10.59l6.04-6.05 1.42 1.42L13.41 12l6.05 6.04-1.42 1.42L12 13.41l-6.04 6.05-1.42-1.42L10.59 12z"></path></g></svg>
            </span>
            <video id="video_preview" controls style="display:none;"></video>
        </div>

    
        <div id="loading-screen" style="display: none;">
            <div id="loading-bar" style="background-color: #1da1f2; height: 20px; width: 0; border-radius: 10px;">
                <span id="loading-percent" style="color: white; font-size: 15px; font-weight: 700; user-select: none;"></span>
            </div>
        </div>
    <?php endif; ?>


    <div class="share-post-selection">
        <?php if($settings["upload_image"]=="Active"): ?>
            <span id="add_image">
                <svg viewBox="0 0 24 24" aria-hidden="true"><g><path d="M3 5.5C3 4.119 4.119 3 5.5 3h13C19.881 3 21 4.119 21 5.5v13c0 1.381-1.119 2.5-2.5 2.5h-13C4.119 21 3 19.881 3 18.5v-13zM5.5 5c-.276 0-.5.224-.5.5v9.086l3-3 3 3 5-5 3 3V5.5c0-.276-.224-.5-.5-.5h-13zM19 15.414l-3-3-5 5-3-3-3 3V18.5c0 .276.224.5.5.5h13c.276 0 .5-.224.5-.5v-3.086zM9.75 7C8.784 7 8 7.784 8 8.75s.784 1.75 1.75 1.75 1.75-.784 1.75-1.75S10.716 7 9.75 7z"></path></g></svg>
            </span>
            <input type="file" name="add_image" id="media" style="display:none;">
        <?php endif; ?>
        
        <?php if($settings["upload_video"]=="Active"): ?>
            <span id="add_video" onclick="document.getElementById('add_video_input').click();">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                    <path d="M0 0h24v24H0V0z" fill="none"></path>
                    <path d="M10 8v8l5-4-5-4zm9-5H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 16H5V5h14v14z"></path>
                </svg>
            </span>
            <input type="file" name="add_video" id="add_video_input" style="display:none;">
        <?php endif; ?>

        <span class="xcloneSelect-emoji" id="xcloneSelect-emoji">
            <svg class="xcloneSelect-emoji" id="xcloneSelect-emoji" viewBox="0 0 24 24" aria-hidden="true"><g><path d="M8 9.5C8 8.119 8.672 7 9.5 7S11 8.119 11 9.5 10.328 12 9.5 12 8 10.881 8 9.5zm6.5 2.5c.828 0 1.5-1.119 1.5-2.5S15.328 7 14.5 7 13 8.119 13 9.5s.672 2.5 1.5 2.5zM12 16c-2.224 0-3.021-2.227-3.051-2.316l-1.897.633c.05.15 1.271 3.684 4.949 3.684s4.898-3.533 4.949-3.684l-1.896-.638c-.033.095-.83 2.322-3.053 2.322zm10.25-4.001c0 5.652-4.598 10.25-10.25 10.25S1.75 17.652 1.75 12 6.348 1.75 12 1.75 22.25 6.348 22.25 12zm-2 0c0-4.549-3.701-8.25-8.25-8.25S3.75 7.451 3.75 12s3.701 8.25 8.25 8.25 8.25-3.701 8.25-8.25z"></path></g></svg>
        </span>

        <span id="xcloneGetGif">
            <svg viewBox="0 0 24 24" aria-hidden="true" class="r-1cvl2hr r-4qtqp9 r-yyyyoo r-z80fyv r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-19wmn03"><g><path d="M3 5.5C3 4.119 4.12 3 5.5 3h13C19.88 3 21 4.119 21 5.5v13c0 1.381-1.12 2.5-2.5 2.5h-13C4.12 21 3 19.881 3 18.5v-13zM5.5 5c-.28 0-.5.224-.5.5v13c0 .276.22.5.5.5h13c.28 0 .5-.224.5-.5v-13c0-.276-.22-.5-.5-.5h-13zM18 10.711V9.25h-3.74v5.5h1.44v-1.719h1.7V11.57h-1.7v-.859H18zM11.79 9.25h1.44v5.5h-1.44v-5.5zm-3.07 1.375c.34 0 .77.172 1.02.43l1.03-.86c-.51-.601-1.28-.945-2.05-.945C7.19 9.25 6 10.453 6 12s1.19 2.75 2.72 2.75c.85 0 1.54-.344 2.05-.945v-2.149H8.38v1.032H9.4v.515c-.17.086-.42.172-.68.172-.76 0-1.36-.602-1.36-1.375 0-.688.6-1.375 1.36-1.375z"></path></g></svg>
        </span>
        <button type="submit" class="share-ew-post" id="share-ew-post"><?php echo xclone_translate("post_share"); ?></button>
    </div>
</form>

<script>
    document.getElementById("add_image").addEventListener("click", function() {
        document.getElementById("media").click();
    });

    const form = document.querySelector('#xclone-new-post');
    const input = document.querySelector('#media');

    input.addEventListener('change', () => {
        const file = input.files[0];

        if (file.type.startsWith('image/')) {
            const reader = new FileReader();
            reader.onload = () => {
                const display = document.querySelector('.displayImage');

                display.querySelectorAll('img').forEach(img => img.remove());

                const image = new Image();

                image.src = reader.result;
                display.appendChild(image);

                document.querySelector('.removeImage').style.display = 'block';
            }

            reader.readAsDataURL(file);
        }
    });

    document.querySelector('.removeImage').addEventListener('click', () => {
        const display = document.querySelector('.displayImage');
        display.querySelectorAll('img').forEach(img => img.remove());
        document.querySelector('.removeImage').style.display = 'none';
        input.value = null;
    });

    form.addEventListener('submit', (event) => {
        const display = document.querySelector('.displayImage');
        if (display.querySelector('img')) {
            setTimeout(() => {
                display.querySelector('img').remove();
                document.querySelector('.removeImage').style.display = 'none';
            }, 2000);
        }
        return true;
    });
</script>

<script>
     const fileInput = document.getElementById('add_video_input');
    const videoPreview = document.getElementById('video_preview');
    const removeButton = document.querySelector('.removeVideo');
    const loadingScreen = document.getElementById('loading-screen');
    const loadingBar = document.getElementById('loading-bar');
    const loadingPercent = document.getElementById('loading-percent');

    fileInput.addEventListener('change', (e) => {
      const file = e.target.files[0];
      if (!file) {
        videoPreview.style.display = 'none';
        removeButton.style.display = 'none';
        return;
      }

      if (!file.type.startsWith('video/')) {
        toastr.error('Please select a video file.', '', { timeOut: 2000 });
        return;
      }

      const videoUrl = URL.createObjectURL(file);
      videoPreview.src = videoUrl;
      videoPreview.style.display = 'block';
      removeButton.style.display = 'block';

      loadingScreen.style.display = 'flex';

      const video = document.createElement('video');
      video.src = videoUrl;
      video.addEventListener('loadedmetadata', () => {
        const duration = video.duration;
        const interval = 10;
        let percent = 0;

        const progress = setInterval(() => {
          percent += interval / duration;
          loadingBar.style.width = percent.toFixed(2) + '%';

          if (percent >= 100) {
            clearInterval(progress);
            loadingScreen.style.display = 'none';
          }

          loadingPercent.textContent = Math.round(percent) + '%';
        }, interval);
      });
    });

    removeButton.addEventListener('click', () => {
      videoPreview.src = '';
      videoPreview.style.display = 'none';
      removeButton.style.display = 'none';
      fileInput.value = '';
    });
</script>

<style> #loading-screen { position: fixed; top: 0; left: 0; right: 0; bottom: 0; background-color: rgba(0, 0, 0, 0.5); display: flex; justify-content: center; align-items: center; z-index: 9999; } #loading-bar { background-color: red; height: 20px; font-size: 25px; font-weight: 700; position: relative; } #loading-percent { position: absolute; top: 0; left: 50%; transform: translateX(-50%); line-height: 20px; color: white; } </style>
<script src="/themes/default/apps/timeline/script/xcloneEmojies.js"></script>
<?php xclone_template("timeline/script/xclone.master.script"); ?>
<?php endif; ?>