<?php $settings = vipub_site_settings(); 
error_reporting(E_ALL); ?>
<main id="main" class="main">
    <div class="pagetitle">
      <h1>Website Information</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="<?php echo vipub_link("admin_panel/"); ?>">Home</a></li>
          <li class="breadcrumb-item">Settings</li>
          <li class="breadcrumb-item active">Website Information</li>
        </ol>
      </nav>
    </div>
    <section class="section">
      <div class="row">
        <div class="col-lg-6">

        <form action="" method="post">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title" style="color:#0f1419; font-size: 15px;">Website <strong>Information</strong></h5>
                    <div class="row mb-3">
                        <label for="inputText" style="font-size: 14px; font-weight: 700; line-height: 21px; color: #000;" for="inputText" style="font-size: 14px; font-weight: 700; line-height: 21px; color: #000;">Website Name</label>
                        <div class="col-sm-20">
                            <input type="text" class="form-control" style="width: 100% !important;" name="site_name" placeholder="<?php echo $settings["site_name"]; ?>" value="<?php echo $settings["site_name"]; ?>" required>
                        </div>
                        <small style="font-size: 12px;">Your website name, it will on website's footer and E-mails.</small>
                    </div>
                    <hr style="background: #555555; color: #555555; margin-bottom: -0px;" />

                    <div class="row mt-3 mb-3">
                        <label for="inputText" style="font-size: 14px; font-weight: 700; line-height: 21px; color: #000;" for="inputText" style="font-size: 14px; font-weight: 700; line-height: 21px; color: #000;">Site title</label>
                        <div class="col-sm-20">
                            <input type="text" class="form-control" style="width: 100% !important;" name="site_title" placeholder="<?php echo $settings["site_title"]; ?>" value="<?php echo $settings["site_title"]; ?>" required>
                        </div>
                        <small style="font-size: 12px;">Your website general title, it will appear on Google and on your browser tab.</small>
                    </div>
                    <hr style="background: #555555; color: #555555; margin-bottom: -0px;" />

                    <div class="row mt-3 mb-3">
                        <label for="inputText" style="font-size: 14px; font-weight: 700; line-height: 21px; color: #000;" for="inputText" style="font-size: 14px; font-weight: 700; line-height: 21px; color: #000;">Website Description</label>
                        <div class="col-sm-20">
                            <textarea type="text" class="form-control" style="width: 100% !important; height: 100px;" name="site_description" placeholder="<?php echo $settings["site_description"]; ?>" required><?php echo $settings["site_description"]; ?></textarea>
                        </div>
                        <small style="font-size: 12px;">Your website's description, used mostly for SEO and search engines, Max of 100 characters is recommended</small>
                    </div>
                    <hr style="background: #555555; color: #555555; margin-bottom: -0px;" />
                    
                    <div class="row mt-3 mb-3">
                        <label for="inputText" style="font-size: 14px; font-weight: 700; line-height: 21px; color: #000;" for="inputText" style="font-size: 14px; font-weight: 700; line-height: 21px; color: #000;">Website Keywords</label>
                        <div class="col-sm-20">
                            <input type="text" class="form-control" style="width: 100% !important;" name="site_keywords" placeholder="<?php echo $settings["site_keywords"]; ?>" value="<?php echo $settings["site_keywords"]; ?>" required>
                        </div>
                        <small style="font-size: 12px;">Your website's keyword, used mostly for SEO and search engines.</small>
                    </div>
                    <hr style="background: #555555; color: #555555; margin-bottom: -0px;" />
                    
                    <div class="row mt-3 mb-3">
                        <label for="inputText" for="inputText" style="font-size: 14px; font-weight: 700; line-height: 21px; color: #000;">
                        Website <strong>Logo & Favicon</strong></label>
                        <small style="font-size: 12px;">
                        You can easily change your site's Logo and Favicon from this area. <a style="text-decoration:underline;" href="<?php echo vipub_link("admin_panel/logo_and_favicon_settings"); ?>">Edit now</a>
                    </small>
                    </div>

                    <div class="row mt-4">
                        <div class="col-sm-50">
                            <button type="submit" class="btn btn-success" name="saveSettings">
                                Save Website Information
                            </button>
                        </div>
                    </div>
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                    <h5 class="card-title" style="color:#0f1419; font-size: 15px;"><strong>Other</strong></h5>
                    <div class="row">
                        <label for="inputText" style="font-size: 14px; font-weight: 700; line-height: 21px; color: #000;">Default site <strong>theme</strong></label>
                        <div class="col-sm-20">
                            <select class="form-select" name="default_theme">
                                <option value="master.white.theme" <?php if($settings["default_theme"]=="master.white.theme"): ?>selected<?php endif; ?>>
                                    <?php if($settings["default_theme"]=="master.white.theme"): ?>Valid:<?php endif; ?>
                                        Default (White)
                                </option>
                                <option value="master.dark.theme" <?php if($settings["default_theme"]=="master.dark.theme"): ?>selected<?php endif; ?>>
                                    <?php if($settings["default_theme"]=="master.dark.theme"): ?>Valid:<?php endif; ?>
                                    Dark Theme
                                </option>
                            </select>
                        </div>
                        <small style="font-size: 12px;">Choose in which theme your site will be displayed for users who are not logged in.</small>
                    </div>
                    <hr style="background: #555555; color: #555555; margin-bottom: -0px;" />

                    <div class="row mt-3 mb-3">
                        <label for="inputText" style="font-size: 14px; font-weight: 700; line-height: 21px; color: #000;">
                            User profile validation <strong>requests</strong>
                        </label>
                        <div class="col-sm-20">
                            <select class="form-select" name="user_sent_verified">
                                <option value="Active" <?php if($settings["user_sent_verified"]=="Active"): ?>selected<?php endif; ?>>
                                    <?php if($settings["user_sent_verified"]=="Active"): ?>Valid:<?php endif; ?>
                                        Profile verification requests can be sent
                                </option>
                                <option value="No" <?php if($settings["user_sent_verified"]=="No"): ?>selected<?php endif; ?>>
                                    <?php if($settings["user_sent_verified"]=="No"): ?>Valid:<?php endif; ?>
                                        Cannot send verification request
                                </option>
                            </select>
                        </div>
                        <small style="font-size: 12px;">
                        Set whether users can apply for a new verified profile icon 
                        (<?php echo vipub_adminUserVerifiedBlueIcon(); ?>) from their account settings page.
                        </small>
                    </div>
                    <hr style="background: #555555; color: #555555; margin-bottom: -0px;" />

                    <div class="row mt-3 mb-3">
                        <label for="inputText" style="font-size: 14px; font-weight: 700; line-height: 21px; color: #000;">
                        User Registration
                        </label>
                        <div class="col-sm-20">
                            <select class="form-select" name="site_register_status">
                                <option value="1" <?php if($settings["site_register_status"]=="1"): ?>selected<?php endif; ?>>
                                    <?php if($settings["site_register_status"]=="1"): ?>Valid:<?php endif; ?>
                                        New users cannot register
                                </option>
                                <option value="0" <?php if($settings["site_register_status"]=="0"): ?>selected<?php endif; ?>>
                                    <?php if($settings["site_register_status"]=="0"): ?>Valid:<?php endif; ?>
                                        New users can register
                                </option>
                            </select>
                        </div>
                        <small style="font-size: 12px;">
                        Allow users to create accounts in your site.
                        </small>
                    </div>


                    <div class="row mt-4">
                        <div class="col-sm-50">
                            <button type="submit" class="btn btn-success" name="saveSettings">
                                Save Changes
                            </button>
                        </div>
                    </div>
            </div>
        </div>
        </form>
    </div>







        <div class="col-lg-6">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title" style="color:#0f1419; font-size: 15px;">Some site <strong>settings</strong></h5>

                <form action="" method="POST">
                    <div class="row mb-3">
                        <label for="inputText" style="font-size: 14px; font-weight: 700; line-height: 21px; color: #000;" class="col-sm-5 col-form-label">Post length</label>
                        <div class="col-sm-15">
                            <input type="number" class="form-control" style="width: 100% !important;" name="post_maxlength" placeholder="Maximum post length" value="<?php echo $settings["post_maxlength"]; ?>" required>
                        </div>
                        <small style="font-size: 12px;">Set the maximum number of characters in the tweet content that the user will write when sending a new tweet or reply.</small>
                    </div>
                    <hr style="background: #555555; color: #555555; margin-bottom: -0px;" />

                    <div class="row mt-2 mb-3">
                        <label for="inputText" style="font-size: 14px; font-weight: 700; line-height: 21px; color: #000;" class="col-sm-5 col-form-label">Message length</label>
                        <div class="col-sm-15">
                            <input readonly type="number" class="form-control" style="width: 100% !important;" name="message_maxlength" placeholder="Maximum message length" value="<?php echo $settings["message_maxlength"]; ?>" required>
                        </div>
                        <small style="font-size: 12px;">Set the maximum number of characters in the message content that the user will write when sending a new message. <small style="color:#1da1f2;">(This feature is currently disabled)</small></small>
                    </div>
                    <hr style="background: #555555; color: #555555; margin-bottom: -0px;" />

                    <div class="row mt-2 mb-3">
                        <div class="col-lg-16">
                            <label for="inputText" style="font-size: 14px; font-weight: 700; line-height: 21px; color: #000;" class="col-sm-16 col-form-label">Upload image support for tweet or reply</label>
                            <select class="form-select" name="upload_image">
                                <option value="Active" <?php if($settings["upload_image"]=="Active"): ?>selected<?php endif; ?>>
                                    <?php if($settings["upload_image"]=="Active"): ?>Active:<?php endif; ?>
                                        Image upload is active.
                                </option>
                                <option value="No" <?php if($settings["upload_image"]=="No"): ?>selected<?php endif; ?>>
                                    <?php if($settings["upload_image"]=="No"): ?>Disabled:<?php endif; ?>
                                        Image upload is disabled.
                                </option>
                            </select>
                        </div>
                        <small style="font-size: 12px;">Should users be able to upload an image file while composing or replying to a tweet?</small>
                    </div>
                    <hr style="background: #555555; color: #555555; margin-bottom: -0px;" />

                    <div class="row mb-2">
                        <div class="col-sm-12">
                            <label for="inputText" style="font-size: 14px; font-weight: 700; line-height: 21px; color: #000;" class="col-sm-16 col-form-label">Upload video support for tweet or reply</label>
                            <select class="form-select" name="upload_video">
                                <option value="Active" <?php if($settings["upload_video"]=="Active"): ?>selected<?php endif; ?>>
                                    <?php if($settings["upload_video"]=="Active"): ?>Active:<?php endif; ?>
                                        Video upload is active.
                                </option>
                                <option value="No" <?php if($settings["upload_video"]=="No"): ?>selected<?php endif; ?>>
                                    <?php if($settings["upload_video"]=="No"): ?>Disabled:<?php endif; ?>
                                        Video upload is disabled.
                                </option>
                            </select>
                        </div>
                        <small style="font-size: 12px;">Should users be able to upload an video file while composing or replying to a tweet?</small>
                    </div>
                    <hr style="background: #555555; color: #555555; margin-bottom: -0px;" />

                    <div class="row mt-2 mb-3">
                        <div class="col-sm-12">
                        <label for="inputText" style="font-size: 14px; font-weight: 700; line-height: 21px; color: #000;" class="col-sm-16 col-form-label">Translate Tweet content with Google</label>
                            <select class="form-select" name="translate_tweet">
                                <option value="Active" <?php if($settings["translate_tweet"]=="Active"): ?>selected<?php endif; ?>>
                                    <?php if($settings["translate_tweet"]=="Active"): ?>Active:<?php endif; ?>
                                        Tweet content can be translated by Google.
                                </option>
                                <option value="No" <?php if($settings["translate_tweet"]=="No"): ?>selected<?php endif; ?>>
                                    <?php if($settings["translate_tweet"]=="No"): ?>Disabled:<?php endif; ?>
                                        The translation feature is disabled.
                                </option>
                            </select>
                            <?php if($settings["translate_tweet"]=="Active"): ?>
                            <div class="alert alert-success" style="font-size:13px; position:relative; margin-top: 10px; margin-bottom: 5px;">
                                The ability to translate tweets by the <strong>user is active</strong>.<br><br>
                                Vipub uses Google's free Translate API and has a daily limit of 5000 words. The plan should be updated for more translation limits.
                            </div>
                            <?php elseif($settings["translate_tweet"]=="No"): ?>
                                <div class="alert alert-danger" style="font-size:13px; position:relative; margin-top: 10px; margin-bottom: -0px;">
                                The ability to translate tweets <strong>has been disabled</storng>.
                            </div>
                            <?php endif; ?>
                        </div>
                        <small style="font-size: 12px;">Can users translate shared tweets in their browser language using automatic "Google Translate" without leaving the page?</small>
                    </div>
                    <hr style="background: #555555; color: #555555; margin-bottom: -0px;" />

                    <h5 class="card-title" style="color:#0f1419; font-size: 15px; margin-bottom: -15px;">Configure e-mail notification <strong>sending setting</strong></h5>
                    <div class="alert alert-secondary" style="font-size:13px; position:relative; margin-top: 10px; margin-bottom: -0px;">
                        Enabling <strong>e-mail notifications</strong> for users will be very useful for your users. Your <strong>SMTP E-mail settings</strong> must be configured correctly for your <strong>e-mail notifications</strong> to be sent correctly.
                    </div>
                    <div class="row mb-2 mt-3">
                        <div class="col-sm-12">
                            <select class="form-select" name="email_notifications">
                                <option value="Active" <?php if($settings["email_notifications"]=="Active"): ?>selected<?php endif; ?>>
                                    <?php if($settings["email_notifications"]=="Active"): ?>
                                        Email notifications are active for users.
                                    <?php else: ?>
                                        Enable email notifications for users.
                                    <?php endif; ?>
                                </option>
                                <option value="Disabled" <?php if($settings["email_notifications"]=="Disabled"): ?>selected<?php endif; ?>>
                                    <?php if($settings["email_notifications"]=="Disabled"): ?>
                                        Users cannot receive email notifications.
                                    <?php else: ?>
                                        Disable email notifications for users.
                                    <?php endif; ?>
                                </option>
                            </select>
                        </div>
                    </div>

                    <h5 class="card-title" style="color:#0f1419; font-size: 15px; margin-bottom: -15px;">Set your chat <strong>update interval</strong></h5>
                    <div class="alert alert-secondary" style="font-size:13px; position:relative; margin-top: 10px; margin-bottom: -0px;">
                        <strong>Important note:</strong> The lower the chat content update time interval, the higher the load on your server will be. This, in turn, <strong>can lead to existing contractions in your current system.</strong>
                    </div>
                    <div class="row mb-2 mt-3">
                        <div class="col-sm-12">
                            <select class="form-select" name="chat_time_interval">
                                <option hidden value="<?php echo $settings["chat_time_interval"]; ?>" selected>Valid: <?php echo $settings["chat_time_interval"]; ?></option>
                                <option value="1000">1 second</option>
                                <option value="2000">2 second</option>
                                <option value="3000">3 second</option>
                                <option value="4000">4 second</option>
                                <option value="5000">5 second</option>
                                <option value="6000">6 second</option>
                                <option value="7000">7 second</option>
                                <option value="8000">8 second</option>
                                <option value="9000">9 second</option>
                                <option value="10000">10 second</option>
                                <option value="11000">11 second</option>
                                <option value="12000">12 second</option>
                                <option value="13000">13 second</option>
                                <option value="14000">14 second</option>
                                <option value="15000">15 second</option>
                                <option value="16000">16 second</option>
                                <option value="17000">17 second</option>
                                <option value="18000">18 second</option>
                                <option value="19000">19 second</option>
                                <option value="20000">20 second</option>
                            </select>
                        </div>
                    </div>

                    <h5 class="card-title" style="color:#0f1419; font-size: 15px; margin-bottom: -15px;">Set your user timeline <strong>update interval</strong></h5>
                    <div class="alert alert-secondary" style="font-size:13px; position:relative; margin-top: 10px; margin-bottom: -0px;">
                        <strong>Important note:</strong> The lower the user timeline content update time interval, the higher the load on your server will be. This, in turn, <strong>can lead to existing contractions in your current system.</strong>
                    </div>
                    <div class="row mb-2 mt-3">
                        <div class="col-sm-12">
                            <select class="form-select" name="timeline_time_interval">
                                <option hidden value="<?php echo $settings["timeline_time_interval"]; ?>" selected>Valid: <?php echo $settings["timeline_time_interval"]; ?></option>
                                <option value="1000">1 second</option>
                                <option value="2000">2 second</option>
                                <option value="3000">3 second</option>
                                <option value="4000">4 second</option>
                                <option value="5000">5 second</option>
                                <option value="6000">6 second</option>
                                <option value="7000">7 second</option>
                                <option value="8000">8 second</option>
                                <option value="9000">9 second</option>
                                <option value="10000">10 second</option>
                                <option value="11000">11 second</option>
                                <option value="12000">12 second</option>
                                <option value="13000">13 second</option>
                                <option value="14000">14 second</option>
                                <option value="15000">15 second</option>
                                <option value="16000">16 second</option>
                                <option value="17000">17 second</option>
                                <option value="18000">18 second</option>
                                <option value="19000">19 second</option>
                                <option value="20000">20 second</option>
                            </select>
                        </div>
                    </div>

                    <div class="row mt-4">
                        <div class="col-sm-50">
                        <?php if($vipub["admin"]["admin_status"]=="1"): ?>
                            <button type="submit" class="btn btn-success" name="saveSettings2">Save</button>
                        <?php else: ?>
                            <button disabled style="width: 100% !important;" class="btn btn-primary">Cannot trade because your account is demo</button>
                        <?php endif; ?>
                        </div>
                    </div>
              </form>

            </div>
          </div>
        </div>
      </div>
    </section>
</main>
<script>
    $(document).ready(function() {
        if (!$('#site_white_logo').val() && !$('#site_dark_logo').val() && !$('#site_favicon').val()) {
            $('button[name="saveLogoFavicon"]').attr('disabled', true);
        }
    });
    $('input[type="file"]').on('change', function() {
        if ($('#site_white_logo').val() || $('#site_dark_logo').val() || $('#site_favicon').val()) {
            $('button[name="saveLogoFavicon"]').removeAttr('disabled');
        } else {
            $('button[name="saveLogoFavicon"]').attr('disabled', true);
        }
    });
</script>
<?php
if(isset($_POST['saveSettings'])) {
    $site_name = mysqli_real_escape_string($conn, $_POST['site_name']);
    $site_title = mysqli_real_escape_string($conn, $_POST['site_title']);
    $site_description = mysqli_real_escape_string($conn, $_POST['site_description']);
    $site_keywords = mysqli_real_escape_string($conn, $_POST['site_keywords']);
    $default_theme = mysqli_real_escape_string($conn, $_POST['default_theme']);
    $user_sent_verified = mysqli_real_escape_string($conn, $_POST['user_sent_verified']);
    $site_register_status = mysqli_real_escape_string($conn, $_POST['site_register_status']);

    $sql = "UPDATE vipub_settings SET site_name='$site_name', site_title='$site_title', site_description='$site_description', site_keywords='$site_keywords', site_register_status='$site_register_status', user_sent_verified='$user_sent_verified', default_theme='$default_theme' WHERE id=1";

    if(mysqli_query($conn, $sql)) {
        ?>
        <script>
        new Noty({
            type: 'success',
            text: 'Settings updated successfully',
            timeout: 1500,
            progressBar: true,
            callbacks: {
                afterClose: function() {
                    window.location.href = "/admin_panel/general_settings";
                }
            }
        }).show();
        </script>
        <?php
    } else {
        echo "Error " . mysqli_error($conn);
    }
    mysqli_close($conn);
}

if(isset($_POST['saveSettings2'])) {

    $post_maxlength = mysqli_real_escape_string($conn, $_POST['post_maxlength']);
    $message_maxlength = mysqli_real_escape_string($conn, $_POST['message_maxlength']);
    $upload_image = mysqli_real_escape_string($conn, $_POST['upload_image']);
    $upload_video = mysqli_real_escape_string($conn, $_POST['upload_video']);
    $translate_tweet = mysqli_real_escape_string($conn, $_POST['translate_tweet']);
    $chat_time_interval = mysqli_real_escape_string($conn, $_POST['chat_time_interval']);
    $timeline_time_interval = mysqli_real_escape_string($conn, $_POST['timeline_time_interval']);
    $email_notifications = mysqli_real_escape_string($conn, $_POST['email_notifications']);

    $sql = "UPDATE vipub_settings SET post_maxlength='$post_maxlength', message_maxlength='$message_maxlength', upload_image='$upload_image', upload_video='$upload_video', translate_tweet='$translate_tweet', chat_time_interval='$chat_time_interval', email_notifications='$email_notifications', timeline_time_interval='$timeline_time_interval' WHERE id=1";

    if(mysqli_query($conn, $sql)) {
        ?>
        <script>
        new Noty({
            type: 'success',
            text: 'Settings updated successfully',
            timeout: 1500,
            progressBar: true,
            callbacks: {
                afterClose: function() {
                    window.location.href = "/admin_panel/general_settings";
                }
            }
        }).show();
        </script>
        <?php
    } else {
        echo "Error " . mysqli_error($conn);
    }
    mysqli_close($conn);
}
?>