<div class="post vipup-post-publication">
    <div class="vipup-post-userinfo">
        <a href="/@<?php echo $following["username"]; ?>">
        <img src="/<?php echo $following["avatar"]; ?>">
        </a>
        <a href="/@<?php echo $following["username"]; ?>">
        <h5><?php echo vipub_croptxt($following["fullname"], 0, 25); ?>
        <?php if($following["verified"]=="1"): ?>
            <?php echo vipub_userBlue(); ?>
        <?php endif; ?></h5>
        </a>
        <a href="/@<?php echo $following["username"]; ?>">
        <span>@<?php echo $following["username"]; ?></span>
        </a>
    </div>
    <?php if(isset($following["user_bio"])): ?>
    <div class="post-content-line"><?php echo convertVipubText($following["user_bio"]); ?></div>
    <?php else: ?>
    <div class="post-content-line">Bu kullanı henüz biyografi eklememiş.</div>
    <?php endif; ?>
</div>
