<?php
require_once("../../../core/xclone_web_core.phtml");
if (!isset($_SESSION["user_id"])) {
    xclone_redirect("/welcome/login");
    exit;
  }
 
  $email = mysqli_real_escape_string($conn, $_POST['email']);
  $user_id = mysqli_real_escape_string($conn, $_SESSION['user_id']);
  
  $query = "SELECT id FROM xclone_users WHERE email=? AND id != ?";
  $stmt = mysqli_prepare($conn, $query);
  
  mysqli_stmt_bind_param($stmt, 'si', $email, $user_id);
  mysqli_stmt_execute($stmt);
  
  $result = mysqli_stmt_get_result($stmt);
  
  if (mysqli_num_rows($result) > 0) {
      echo '1';
  } else {
      echo '0';
  }
  
  mysqli_stmt_close($stmt);
  mysqli_close($conn);
  