<?php
require_once("../../../core/xclone_web_core.phtml");

if (!isset($_SESSION["user_id"])) {
  xclone_redirect("/welcome/login");
  exit;
}


$username = mysqli_real_escape_string($conn, htmlspecialchars($_POST["username"], ENT_QUOTES, 'UTF-8'));
$user_id = mysqli_real_escape_string($conn, htmlspecialchars($_SESSION["user_id"], ENT_QUOTES, 'UTF-8'));

$sql = "SELECT id FROM xclone_users WHERE username='$username' AND id != $user_id";
$result = mysqli_query($conn, $sql);

if (mysqli_num_rows($result) > 0) {
    echo '1';
} else {
    echo '0';
}

mysqli_close($conn);