<?php
require_once("../../../core/vipub_web_core.phtml");

if (!isset($_SESSION["user_id"])) {
  vipub_redirect("/welcome/login");
  exit;
}
$user_id = mysqli_real_escape_string($conn, htmlspecialchars($_SESSION["user_id"]));
$password = mysqli_real_escape_string($conn, sha1($_POST["password"]));
$sql = "UPDATE vipub_users SET password='$password' WHERE id=$user_id";
if (mysqli_query($conn, $sql)) {
    echo $password;
} else {
    echo "Hata: " . mysqli_error($conn);
}

mysqli_close($conn);