<?php
require_once("../../../core/xclone_web_core.phtml");

if (!isset($_SESSION["user_id"])) {
  xclone_redirect("/welcome/login");
  exit;
}
$user_id = mysqli_real_escape_string($conn, htmlspecialchars($_SESSION["user_id"]));
$website = mysqli_real_escape_string($conn, strip_tags($_POST['website']));
$sql = "UPDATE xclone_users SET user_website='$website' WHERE id=$user_id";
if (mysqli_query($conn, $sql)) {
    echo $website;
} else {
    echo "Hata: " . mysqli_error($conn);
}

mysqli_close($conn);