<?php xclone_template("main/sidebar/left-sidebar"); ?>
<div class="col-md-6">
    <div class="main-xclone-screenline">
        <div class="site-header-box">
            <h5><svg id="back-page" viewBox="0 0 24 24" aria-hidden="true"><g><path d="M7.414 13l5.043 5.04-1.414 1.42L3.586 12l7.457-7.46 1.414 1.42L7.414 11H21v2H7.414z"></path></g></svg>
            <?php echo xclone_translate("bookmarks"); ?></h5>
        </div>
        <div id="bookmarks-lives-user-feed"></div>
    </div>
</div>
<?php xclone_template("bookmarks/script/app.master.script"); ?>
<?php xclone_template("main/sidebar/right-sidebar"); ?>