<?php vipub_template("main/sidebar/left-sidebar"); $settings = vipub_site_settings(); ?>
<?php $conn = vipubConnectDatabase(); $uname = htmlspecialchars(trim($_SESSION["user_id"])); $row = vipub_get_my_profile($conn, $uname); ?>
<div class="col-md-6">
    <div class="main-vipub-screenline">
    
        <div class="account-settings-page-for-users-page">
            <div class="settings-page-top-title">
                <h5><svg id="back-page" viewBox="0 0 24 24" aria-hidden="true"><g><path d="M7.414 13l5.043 5.04-1.414 1.42L3.586 12l7.457-7.46 1.414 1.42L7.414 11H21v2H7.414z"></path></g></svg><?php echo vipub_translate("account_settings"); ?></h5>
            </div>

            <div class="settings-page-content-full next-settings-page-container-none-border">
                <div class="settings-edit-profile-right-zone next-settings-page-container">
                    <div class="edit-profile-right-zone-title">
                        <h5><?php echo vipub_translate("account_settings_menu_39"); ?></h5>
                        <small><?php echo vipub_translate("account_settings_menu_38"); ?></small>
                    </div>
                    <div class="user-profile-edit-form-content-full">
                        <form id="change-email">
                            <div class="edit-input-profile">
                                <label for="email"><?php echo vipub_translate("account_settings_menu_39"); ?></label>
                                <input type="text" name="email" id="email" value="<?php echo $row["email"]; ?>" placeholder="<?php echo vipub_translate("account_settings_menu_39"); ?>">
                            </div>
                            <div class="edit-input-profile">
                                <button type="submit" class="email-save"><?php echo vipub_translate("account_settings_menu_27"); ?></button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
    $('#change-email').submit(function(event) {
        event.preventDefault();
        var email = $.trim($('#email').val());
        if (email === '') {
            var vipubSM_msgIcon = '<i class="bi bi-x-circle"></i>';
            var vipubSM_msgText = '<?php echo vipub_translate("settings_page_save_value_desc_10"); ?>';
            var vipubSM_alertTimeout = 5000;

            vipubSM.showAlert(vipubSM_msgIcon, vipubSM_msgText, vipubSM_alertTimeout);
        } else if (!isValidEmail(email)) {
            var vipubSM_msgIcon = '<i class="bi bi-x-circle"></i>';
            var vipubSM_msgText = '<?php echo vipub_translate("settings_page_save_value_desc_11"); ?>';
            var vipubSM_alertTimeout = 5000;

            vipubSM.showAlert(vipubSM_msgIcon, vipubSM_msgText, vipubSM_alertTimeout);
        } else {
            $.ajax({
                type: 'POST',
                url: '/apps/ajax/settings/check-email.phtml',
                data: {
                    email: email
                },
                success: function(response) {
                    if (response === '1') {
                        var vipubSM_msgIcon = '<i class="bi bi-x-circle"></i>';
                        var vipubSM_msgText = '<?php echo vipub_translate("settings_page_save_value_desc_12"); ?>';
                        var vipubSM_alertTimeout = 5000;

                        vipubSM.showAlert(vipubSM_msgIcon, vipubSM_msgText, vipubSM_alertTimeout);
                    } else {
                        $.ajax({
                            type: 'POST',
                            url: '/apps/ajax/settings/email.phtml',
                            data: {
                                email: email
                            },
                            success: function(response) {
                                $('#email').val(response);

                                var vipubSM_msgIcon = '<i class="bi bi-check-circle"></i>';
                                var vipubSM_msgText = '<?php echo vipub_translate("settings_page_save_value_desc_13"); ?>';
                                var vipubSM_alertTimeout = 5000;

                                vipubSM.showAlert(vipubSM_msgIcon, vipubSM_msgText, vipubSM_alertTimeout);
                            },
                            error: function(response) {
                                var vipubSM_msgIcon = '<i class="bi bi-x-circle"></i>';
                                var vipubSM_msgText = 'Hata oluştu: ' + response.responseText;
                                var vipubSM_alertTimeout = 5000;

                                vipubSM.showAlert(vipubSM_msgIcon, vipubSM_msgText, vipubSM_alertTimeout);
                            }
                        });
                    }
                },
                error: function(response) {
                    var vipubSM_msgIcon = '<i class="bi bi-x-circle"></i>';
                    var vipubSM_msgText = 'Hata oluştu: ' + response.responseText;
                    var vipubSM_alertTimeout = 5000;

                    vipubSM.showAlert(vipubSM_msgIcon, vipubSM_msgText, vipubSM_alertTimeout);
                }
            });
        }
    });

    $('#email').attr('maxlength', 150);

    function isValidEmail(email) {
        var emailRegExp = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i;
        return emailRegExp.test(email);
    }
});
</script>