<?php
require_once("../../../core/vipub_web_core.phtml");

if (!isset($_SESSION["user_id"])) {
  vipub_redirect("/welcome/login");
  exit;
}
$user_id = mysqli_real_escape_string($conn, htmlspecialchars($_SESSION["user_id"]));
$email = mysqli_real_escape_string($conn, htmlspecialchars($_POST['email']));
$sql = "UPDATE vipub_users SET email='$email' WHERE id=$user_id";
if (mysqli_query($conn, $sql)) {
    echo $email;
} else {
    echo "Hata: " . mysqli_error($conn);
}

mysqli_close($conn);