<?php xclone_template("main/sidebar/left-sidebar"); ?>
<div class="col-md-6">
    <div class="main-xclone-screenline">
        <div class="margin-bottom-connection-people"></div>
            <div class="connection-people-conn">
                <h6>
                    <svg id="back-page" viewBox="0 0 24 24" aria-hidden="true"><g><path d="M7.414 13l5.043 5.04-1.414 1.42L3.586 12l7.457-7.46 1.414 1.42L7.414 11H21v2H7.414z"></path></g></svg>
                    <?php echo xclone_translate("connect_people_for_following_info_suggested"); ?>
                </h6>
                <div id="suggestion-connect-people"></div>
                <div class="suggested-page-bottom-footer">
                    <?php echo xclone_rightsidebar_footer(); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php xclone_template("connect_people/script/app.master.script"); ?>