<?php
require_once("../../../core/vipub_web_core.phtml");
if (isset($_GET['uname'])) {
    $username = $_GET['uname'];
    $sql = "SELECT p.*, u.* FROM vipub_posts p LEFT JOIN vipub_users u ON p.user_id = u.id WHERE u.username = ? AND post_type = 'post' ORDER BY p.post_joined DESC";
    $stmt = mysqli_prepare($conn, $sql);
    mysqli_stmt_bind_param($stmt, "s", $username);
  
    if (mysqli_stmt_execute($stmt)) {
      $result = mysqli_stmt_get_result($stmt);
  
      if (mysqli_num_rows($result) > 0) {
        while ($row = mysqli_fetch_assoc($result)) {
          $postId = $row["p_id"];
          $userId = $row["user_id"];
          $username = $row["username"];
          $fullname = $row["fullname"];
          $avatar = $row["avatar"];
          $content = $row["content_post"];
          require("../../../themes/default/apps/timeline/content.phtml");
        }
      } else {
        vipub_template("profile/include/no-post");
      }
    } else {
      die("Hata: " . mysqli_error($conn));
    }
  
    mysqli_stmt_close($stmt);
  } else {
    die("Don't username");
  }
  
  mysqli_close($conn);