<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
require_once("../../../core/xclone_web_core.phtml");

if(!isset($_SESSION["user_id"])){
    header("Location: /welcome/login");
}

$uname = htmlspecialchars(trim($_GET["username"]));
$sql = "SELECT u.fullname, u.username, u.avatar, u.user_bio, f.user_id, u.verified FROM xclone_users u JOIN xclone_follow f ON u.id = f.follower_id WHERE f.user_id = '$uname'";

$result = mysqli_query($conn, $sql);
if (mysqli_num_rows($result) > 0) {
    while ($following = mysqli_fetch_assoc($result)) {
        require("../../../themes/default/apps/profile/pages/include/followers-list.phtml");
    }
} else {
    require("../../../themes/default/apps/profile/pages/include/no-following.phtml");
}

mysqli_close($conn);