<?php
require_once("../../../core/xclone_web_core.phtml");

if (!isset($_SESSION["user_id"])) {
  header("Location: /welcome");
  exit;
}

if(isset($_GET["user_id"])){
  $user_id = mysqli_real_escape_string($conn, $_GET["user_id"]);
  $follower_id = mysqli_real_escape_string($conn, $_SESSION["user_id"]);
  
  if (!is_numeric($user_id) || !is_numeric($follower_id)) {
    $response = array('xclone_error_message' => xclone_translate("invalid_input_error_text"));
    echo json_encode($response);
    exit();
  }
  $query = "SELECT * FROM xclone_follow WHERE user_id = ? AND follower_id = ?";
  $stmt = mysqli_prepare($conn, $query);
  mysqli_stmt_bind_param($stmt, 'ii', $follower_id, $user_id);
  mysqli_stmt_execute($stmt);
  $result = mysqli_stmt_get_result($stmt);
  if (mysqli_num_rows($result) > 0) {
    $response = [
      'xclone_success_code' => 200,
      'xclone_success_command' => "valid_user_id",
      'xclone_success_message' => xclone_translate("user_your_follow_check_text")
  ];
  } else {
    $response = array();
  }
  echo json_encode($response);
  mysqli_stmt_close($stmt);
} else {
  $response = [
      'xclone_error_code' => 400,
      'xclone_error_command' => "invalid_user_id",
      'xclone_error_message' => "No user id specified"
  ];
  echo json_encode($response);
}
