<?php
require_once("../../../core/xclone_web_core.phtml");
if (isset($_GET['uname'])) {
    $username = $_GET['uname'];
    
    // SQL sorgusu
   $sql = "SELECT p.*, u.*, l.* FROM xclone_posts p 
            LEFT JOIN xclone_users u ON p.user_id = u.id 
            LEFT JOIN xclone_likes l ON p.p_id = l.post_id 
            WHERE l.user_id = ? 
            AND (p.post_type = 'post' OR p.post_type = 'post_video') 
            AND l.user_id = (SELECT id FROM xclone_users WHERE id = ?)
            ORDER BY l.l_id DESC";
    
    $stmt = $conn->prepare($sql);
    $stmt->bind_param("ii", $username, $username);
    
    if ($stmt->execute()) {
        $result = $stmt->get_result();
    
        if ($result->num_rows > 0) {
            while ($row = $result->fetch_assoc()) {
                $postId = htmlspecialchars($row["p_id"], ENT_QUOTES, "UTF-8");
                $userId = htmlspecialchars($row["user_id"], ENT_QUOTES, "UTF-8");
                $username = htmlspecialchars($row["username"], ENT_QUOTES, "UTF-8");
                $fullname = htmlspecialchars($row["fullname"], ENT_QUOTES, "UTF-8");
                $avatar = htmlspecialchars($row["avatar"], ENT_QUOTES, "UTF-8");
                $content = htmlspecialchars($row["content_post"], ENT_QUOTES, "UTF-8");
                require("../../../themes/default/apps/timeline/content.phtml");
            }
        } else {
            xclone_template("profile/include/no-post");
        }
    } else {
        echo "SQL Conn OR (Database Table) error: " . $stmt->error;
    }
    $stmt->close();
    $conn->close();
}