<?php
require_once("../../../core/vipub_web_core.phtml");
if (isset($_GET['uname'])) {
    $username = $_GET['uname'];
    $sql = "SELECT p.*, u.* FROM vipub_repost r
            LEFT JOIN vipub_posts p ON r.repost_post_id = p.p_id
            LEFT JOIN vipub_users u ON p.user_id = u.id
            WHERE r.repost_user_id = ? 
            AND (p.post_type = 'post' OR p.post_type = 'post_image' OR p.post_type = 'post_video' OR content_gif IS NOT NULL) 
            ORDER BY r.reposted_at DESC";
    
    $stmt = mysqli_prepare($conn, $sql);
    mysqli_stmt_bind_param($stmt, "s", $username);
  
    if (mysqli_stmt_execute($stmt)) {
      $result = mysqli_stmt_get_result($stmt);
  
      if (mysqli_num_rows($result) > 0) {
        while ($row = mysqli_fetch_assoc($result)) {
          $postId = htmlspecialchars($row["p_id"], ENT_QUOTES, "UTF-8");
          $userId = htmlspecialchars($row["user_id"], ENT_QUOTES, "UTF-8");
          $username = htmlspecialchars($row["username"], ENT_QUOTES, "UTF-8");
          $fullname = htmlspecialchars($row["fullname"], ENT_QUOTES, "UTF-8");
          $avatar = htmlspecialchars($row["avatar"], ENT_QUOTES, "UTF-8");
          $content = htmlspecialchars($row["content_post"], ENT_QUOTES, "UTF-8");
          echo '
              <div class="this-post-user-retweeted user-profile-quote-title">
                <span>
                    <i class="bi bi-repeat-1"></i>
                    '.vipub_translate("this_is_a_post_retweet_1").'
                </span>
              </div>
            ';
          require("../../../themes/default/apps/timeline/content.phtml");
        }
      } else {
        vipub_template("profile/include/no-post");
      }
    } else {
      die("Hata: " . mysqli_error($conn));
    }
  
    mysqli_stmt_close($stmt);
  } else {
    die("Don't username");
  }
  
  mysqli_close($conn);