<?php
require_once("../../../core/xclone_web_core.phtml");

$user_id_post = mysqli_real_escape_string($conn, $_POST['user_id']);

$sql = "SELECT COUNT(*) as total_post_count FROM xclone_posts WHERE user_id = '$user_id_post' AND (post_type = 'post' OR post_type = 'post_video') ";
$result = $conn->query($sql);

$response = array();

if ($result) {
    $row = $result->fetch_assoc();
    $response['total_post_count'] = $row['total_post_count'];
} else {
    $response['total_post_count'] = "0";
}

$conn->close();

echo json_encode($response);