<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
require_once("../../../core/vipub_web_core.phtml");

if(isset($_SESSION["user_id"])){
    $sql = "SELECT *
    FROM vipub_users 
    WHERE id NOT IN (SELECT user_id FROM vipub_follow WHERE follower_id = ?)
    AND id != ?
    AND account_status = 0 
    ORDER BY RAND() DESC LIMIT 10";
    $stmt = mysqli_prepare($conn, $sql);
    mysqli_stmt_bind_param($stmt, "ii", $_SESSION["user_id"], $_SESSION["user_id"]);
    mysqli_stmt_execute($stmt);
    $result = mysqli_stmt_get_result($stmt);
} else {
    $stmt = mysqli_prepare($conn, "SELECT fullname, username, avatar, user_bio, id, verified FROM vipub_users");
    mysqli_stmt_execute($stmt);
    $result = mysqli_stmt_get_result($stmt);
}
if (mysqli_num_rows($result) > 0) {
    while ($connect_people = mysqli_fetch_assoc($result)) {
        require("../../../themes/default/apps/connect_people/include/connect-list.phtml");
    }
} else {
    require("../../../themes/default/apps/connect_people/include/not-connect-list.phtml");
}
mysqli_close($conn);