<?php
require_once("../../../core/xclone_web_core.phtml");

if (!isset($_SESSION["user_id"])) {
  xclone_redirect("/welcome/login");
  exit;
}
$user_id = mysqli_real_escape_string($conn, htmlspecialchars($_SESSION["user_id"]));
$location = mysqli_real_escape_string($conn, strip_tags($_POST['location']));
$sql = "UPDATE xclone_users SET user_location='$location' WHERE id=$user_id";
if (mysqli_query($conn, $sql)) {
    echo $location;
} else {
    echo "Hata: " . mysqli_error($conn);
}

mysqli_close($conn);