<?php
require_once("../../../core/vipub_web_core.phtml");

if (!isset($_SESSION["user_id"])) {
  header("Location: /welcome/login");
  exit;
}

$user_id = mysqli_real_escape_string($conn, $_POST['user_id']);
$follower_id = mysqli_real_escape_string($conn, $_SESSION['user_id']);

if (is_numeric($user_id) && is_numeric($follower_id)) {
    $sql = "SELECT COUNT(*) AS count FROM vipub_follow WHERE user_id = ? AND follower_id = ?";
    $stmt = mysqli_prepare($conn, $sql);
    mysqli_stmt_bind_param($stmt, "ii", $user_id, $follower_id);
    mysqli_stmt_execute($stmt);
    $result = mysqli_stmt_get_result($stmt);
    $row = mysqli_fetch_assoc($result);
    if ($row['count'] > 0) {
        echo 'true';
    } else {
        echo 'false';
    }
    mysqli_stmt_close($stmt);
}
mysqli_close($conn);
