<?php
require_once("../../../core/xclone_web_core.phtml");
if (isset($_GET['uname'])) {
  $username = $_GET['uname'];
  $sql = "SELECT p.*, u.* FROM xclone_posts p 
          LEFT JOIN xclone_users u ON p.user_id = u.id 
          WHERE u.username = ? 
          AND (p.post_type = 'post' OR p.post_type = 'post_video') 
          ORDER BY p.post_joined DESC";
  $stmt = mysqli_prepare($conn, $sql);
  mysqli_stmt_bind_param($stmt, "s", $username);
  
    if (mysqli_stmt_execute($stmt)) {
      $result = mysqli_stmt_get_result($stmt);
  
      if (mysqli_num_rows($result) > 0) {
        while ($row = mysqli_fetch_assoc($result)) {
          $postId = htmlspecialchars($row["p_id"], ENT_QUOTES, "UTF-8");
          $userId = htmlspecialchars($row["user_id"], ENT_QUOTES, "UTF-8");
          $username = htmlspecialchars($row["username"], ENT_QUOTES, "UTF-8");
          $fullname = htmlspecialchars($row["fullname"], ENT_QUOTES, "UTF-8");
          $avatar = htmlspecialchars($row["avatar"], ENT_QUOTES, "UTF-8");
          $content = htmlspecialchars($row["content_post"], ENT_QUOTES, "UTF-8");
          require("../../../themes/default/apps/timeline/content.phtml");
        }
      } else {
        xclone_template("profile/include/no-post");
      }
    } else {
      die("Hata: " . mysqli_error($conn));
    }
  
    mysqli_stmt_close($stmt);
  } else {
    die("Don't username");
  }
  
  mysqli_close($conn);