<?php xclone_template("main/sidebar/left-sidebar"); ?>
<div class="col-md-6">
    <div class="main-xclone-screenline">
        <div class="site-header-box">
            <h5><svg id="back-page" viewBox="0 0 24 24" aria-hidden="true"><g><path d="M7.414 13l5.043 5.04-1.414 1.42L3.586 12l7.457-7.46 1.414 1.42L7.414 11H21v2H7.414z"></path></g></svg>
            <?php echo xclone_translate("notifications"); ?></h5>
        </div>
        <div class="notifications-page-maxheight">
            <div id="notifications-feed"></div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        var userId = <?php echo $_SESSION["user_id"]; ?>;
        $.ajax({
            url: "/apps/ajax/notifications/get-notifications.phtml",
            method: "POST",
            data: {userId: userId},
            dataType: "html",
            success: function(response) {
            $("#notifications-feed").html(response);
            }
        });

        setInterval(function() {
            $.ajax({
            url: "/apps/ajax/notifications/get-notifications.phtml",
            method: "POST",
            data: {userId: userId},
            dataType: "html",
            success: function(response) {
                $("#notifications-feed").html(response);
            }
            });
        }, 5000);
    });
</script>
<?php xclone_template("main/sidebar/right-sidebar"); ?>