<?php
require_once("../../../core/xclone_web_core.phtml");

if (!isset($_SESSION["user_id"])) {
    header("Location: /welcome");
  exit;
}

if(isset($_POST['userId'])) {
  $userId = mysqli_real_escape_string($conn, $_POST['userId']);
  $myUser = mysqli_real_escape_string($conn, $_SESSION['user_id']);
  
  // Bildirimleri okundu olarak işaretle
  $updateSql = "UPDATE xclone_notifs SET is_read = 1 WHERE user_id = '$userId'";
  mysqli_query($conn, $updateSql);
  
  $sql = "SELECT n.sender_id, n.type, n.post_id, n.post_id, u.verified, u.fullname, u.avatar, u.username FROM xclone_notifs AS n 
          INNER JOIN xclone_users AS u ON n.sender_id = u.id
          WHERE n.user_id = '" . mysqli_real_escape_string($conn, $userId) . "'
          ORDER BY n.n_id DESC";
  $result = mysqli_query($conn, $sql);

  $mySql = "SELECT username FROM xclone_users WHERE id = '" . mysqli_real_escape_string($conn, $myUser) . "'";
  $userResult = mysqli_query($conn, $mySql);
  
  if(mysqli_num_rows($result) > 0) {
    while($row = mysqli_fetch_assoc($result)) {
      $senderId = $row['sender_id'];
      $type = $row['type'];
      $post_id = $row['post_id'];
      $fullname = htmlspecialchars($row['fullname']); 
      $avatar = $row['avatar'];
      $username = htmlspecialchars($row['username']);
      $verified = $row['verified'];

      while($xclone_user = mysqli_fetch_assoc($userResult)) {
        require("../../../themes/default/apps/notifications/include/notifs.phtml");
      }
      mysqli_data_seek($userResult, 0);
    }
  } else {
    require("../../../themes/default/apps/notifications/include/no-notifs-list.phtml");
  }
}