<?php
require_once("../../../core/vipub_web_core.phtml");
if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    $password = sha1($_POST["password"]);
    $query = "UPDATE vipub_users SET password='$password', reset_token=NULL WHERE id = '".$_GET["user"]."'";
    if ($conn->query($query) === TRUE) {
      echo "".vipub_translate("settings_page_save_value_desc_16")."";
    } else {
      echo "Error: " . $conn->error;
    }
  
    $conn->close();
} else {
    echo "Not db.";
}

