<div class="no-post-yet-timeline">
    <div class="no-post-yet">
        <h5><?php echo vipub_translate("message_page_1"); ?></h5>
        <span><?php echo vipub_translate("message_page_2"); ?></span>
        <span><?php echo vipub_translate("message_page_3"); ?></span>
        <a href="<?php echo vipub_link("connect_people"); ?>"><?php echo vipub_translate("message_page_4"); ?></a>
    </div>
</div>