<div class="notifications-container-sm">
    <div class="user-notifications">
    <?php if($type=="follow"): ?>
        <a href="/@<?php echo $username; ?>">
            <div class="notifs-display-container">
                <span>
                    <svg xmlns="http://www.w3.org/2000/svg" class="bi bi-person-plus-fill" viewBox="0 0 16 16">
                    <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                    <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/></svg>
                    <img src="/<?php echo $avatar; ?>">
                </span>

                <h5><?php echo $fullname; ?> 
                <?php if($verified=="1"): ?>
                    <?php echo vipub_userBlue(); ?>
                <?php endif; ?>
                <span><?php echo vipub_translate("notification_notif_name_1"); ?></span> </h5>
            </div>
        </a>
    <?php elseif($type=="like"): ?>
        <a href="<?php echo vipub_link($vipub_user["username"]."/status/".$post_id); ?>">
            <div class="notifs-display-container">
                <span>
                    <svg xmlns="http://www.w3.org/2000/svg" class="bi bi-heart-fill" viewBox="0 0 16 16"> <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/> </svg>
                    <img src="/<?php echo $row["avatar"]; ?>">
                </span>

                <h5><?php echo $fullname; ?> 
                <?php if($verified=="1"): ?>
                    <?php echo vipub_userBlue(); ?>
                <?php endif; ?>
                <span><?php echo vipub_translate("notification_notif_name_2"); ?></span> </h5>
            </div>
        </a>
        <?php elseif($type=="mention"): ?>
        <a href="<?php echo vipub_link($username."/status/".$post_id); ?>">
            <div class="notifs-display-container">
                <span>
                <svg xmlns="http://www.w3.org/2000/svg" class="bi bi-at" viewBox="0 0 16 16"> <path d="M13.106 7.222c0-2.967-2.249-5.032-5.482-5.032-3.35 0-5.646 2.318-5.646 5.702 0 3.493 2.235 5.708 5.762 5.708.862 0 1.689-.123 2.304-.335v-.862c-.43.199-1.354.328-2.29.328-2.926 0-4.813-1.88-4.813-4.798 0-2.844 1.921-4.881 4.594-4.881 2.735 0 4.608 1.688 4.608 4.156 0 1.682-.554 2.769-1.416 2.769-.492 0-.772-.28-.772-.76V5.206H8.923v.834h-.11c-.266-.595-.881-.964-1.6-.964-1.4 0-2.378 1.162-2.378 2.823 0 1.737.957 2.906 2.379 2.906.8 0 1.415-.39 1.709-1.087h.11c.081.67.703 1.148 1.503 1.148 1.572 0 2.57-1.415 2.57-3.643zm-7.177.704c0-1.197.54-1.907 1.456-1.907.93 0 1.524.738 1.524 1.907S8.308 9.84 7.371 9.84c-.895 0-1.442-.725-1.442-1.914z"/> </svg>
                <img src="/<?php echo $row["avatar"]; ?>">
                </span>

                <h5><?php echo $fullname; ?> 
                <?php if($verified=="1"): ?>
                    <?php echo vipub_userBlue(); ?>
                <?php endif; ?>
                <span><?php echo vipub_translate("user_notifications_page_1"); ?></span> </h5>
            </div>
        </a>
        <?php elseif($type=="mention_reply"): ?>
        <a href="<?php echo vipub_link($vipub_user["username"]."/status/".$post_id); ?>">
            <div class="notifs-display-container">
                <span>
                    <svg xmlns="http://www.w3.org/2000/svg" class="bi bi-at" viewBox="0 0 16 16"> <path d="M13.106 7.222c0-2.967-2.249-5.032-5.482-5.032-3.35 0-5.646 2.318-5.646 5.702 0 3.493 2.235 5.708 5.762 5.708.862 0 1.689-.123 2.304-.335v-.862c-.43.199-1.354.328-2.29.328-2.926 0-4.813-1.88-4.813-4.798 0-2.844 1.921-4.881 4.594-4.881 2.735 0 4.608 1.688 4.608 4.156 0 1.682-.554 2.769-1.416 2.769-.492 0-.772-.28-.772-.76V5.206H8.923v.834h-.11c-.266-.595-.881-.964-1.6-.964-1.4 0-2.378 1.162-2.378 2.823 0 1.737.957 2.906 2.379 2.906.8 0 1.415-.39 1.709-1.087h.11c.081.67.703 1.148 1.503 1.148 1.572 0 2.57-1.415 2.57-3.643zm-7.177.704c0-1.197.54-1.907 1.456-1.907.93 0 1.524.738 1.524 1.907S8.308 9.84 7.371 9.84c-.895 0-1.442-.725-1.442-1.914z"/> </svg>
                    <img src="/<?php echo $row["avatar"]; ?>">
                </span>

                <h5><?php echo $fullname; ?> 
                <?php if($verified=="1"): ?>
                    <?php echo vipub_userBlue(); ?>
                <?php endif; ?>
                <span><?php echo vipub_translate("user_notifications_page_2"); ?></span> </h5>
            </div>
        </a>
        <?php elseif($type=="comment"): ?>
        <a href="<?php echo vipub_link($vipub_user["username"]."/status/".$post_id); ?>">
            <div class="notifs-display-container">
                <span>
                    <svg xmlns="http://www.w3.org/2000/svg"class="bi bi-reply-all-fill" viewBox="0 0 16 16"> <path d="M8.021 11.9 3.453 8.62a.719.719 0 0 1 0-1.238L8.021 4.1a.716.716 0 0 1 1.079.619V6c1.5 0 6 0 7 8-2.5-4.5-7-4-7-4v1.281c0 .56-.606.898-1.079.62z"/> <path d="M5.232 4.293a.5.5 0 0 1-.106.7L1.114 7.945a.5.5 0 0 1-.042.028.147.147 0 0 0 0 .252.503.503 0 0 1 .042.028l4.012 2.954a.5.5 0 1 1-.593.805L.539 9.073a1.147 1.147 0 0 1 0-1.946l3.994-2.94a.5.5 0 0 1 .699.106z"/> </svg>
                    <img src="/<?php echo $row["avatar"]; ?>">
                </span>

                <h5><?php echo $fullname; ?> 
                <?php if($verified=="1"): ?>
                    <?php echo vipub_userBlue(); ?>
                <?php endif; ?>
                <span><?php echo vipub_translate("notification_notif_name_comment"); ?></h5>
            </div>
        </a>
        <?php elseif($type=="verified"): ?>
        <a>
            <div class="notifs-display-container">
                <span>
                    <?php echo vipub_userBlue(); ?>
                    <img src="<?php echo vipub_template_master("images/logo.png"); ?>">
                </span>

                <h5>
                <?php echo vipub_translate("user_verified_one_notifs"); ?>
                </h5>
            </div>
        </a>
    <?php endif; ?>
    </div>
</div>