<?php 
$row["account"] = xclone_my_user_info();
xclone_template("main/sidebar/messages/left-sidebar");?>
<div class="col-md-6">
    <div class="main-xclone-screenline">
        <div class="site-header-box first-message-title">
            <h5>
              <svg id="back-page" viewBox="0 0 24 24" aria-hidden="true"><g><path d="M7.414 13l5.043 5.04-1.414 1.42L3.586 12l7.457-7.46 1.414 1.42L7.414 11H21v2H7.414z"></path></g></svg>
              <?php echo $row["account"]["username"]; ?>
                <?php if($row["account"]["verified"]=="1"): ?>
                    <small><?php echo xclone_userBlue(); ?></small>
                <?php endif; ?>
              <span><i class="bi bi-pencil-square"></i></span>
            </h5>
        </div>
        <div class="get-message-my-list">
          <div id="myuser-only-chatlist"></div>
        </div>
    </div>
</div>

<div class="only-right-page-not-message-container">
  <div class="only-not-message-info-center">
      <small>
        <i class="bi bi-messenger"></i>
      </small>
      <h5><?php echo xclone_translate("messages"); ?><br>
      <span><?php echo xclone_translate("message_page_3"); ?></span>
  </div>
</div>

<script>
  $(document).ready(function() {
  $.ajax({
    url: '/apps/ajax/messages/get-my-chatlist.phtml',
    type: 'GET',
    dataType: 'html',
    success: function(response) {
      $('#myuser-only-chatlist').html(response);
    },
    error: function() {
      alert('Error Message');
    }
  });
});
</script>
<style>body{overflow:hidden;}</style>