<?php xclone_template("main/sidebar/left-sidebar"); 
if (!isset($_GET["tweet_id"])) {
    header("Location: /home");
    exit();
}
?>
<div class="col-md-6">
    <div class="main-xclone-screenline">
         <div class="margin-bottom-connection-people"></div>
            <div class="connection-people-conn">
                <h6>
                    <svg id="back-page" viewBox="0 0 24 24" aria-hidden="true"><g><path d="M7.414 13l5.043 5.04-1.414 1.42L3.586 12l7.457-7.46 1.414 1.42L7.414 11H21v2H7.414z"></path></g></svg>
                    <?php echo xclone_translate("status_page_post_like_reply_repost_3"); ?>
                </h6>
                <div id="status-tweet-page-repost"></div>
                <div class="suggested-page-bottom-footer">
                    <?php echo xclone_rightsidebar_footer(); ?>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function fetchPosts() {
        $.ajax({
            url: '/apps/ajax/timeline/repost-view.phtml?tweet_id=<?php echo $_GET["tweet_id"]; ?>',
            type: 'GET',
            success: function(data) {
                $('#status-tweet-page-repost').html(data);
            }
        });
    }
    setInterval(fetchPosts, 7000);
    fetchPosts();
</script>
