<?php vipub_template("main/sidebar/left-sidebar"); $settings = vipub_site_settings(); ?>
<?php $conn = vipubConnectDatabase(); $uname = htmlspecialchars(trim($_SESSION["user_id"])); $row = vipub_get_my_profile($conn, $uname); ?>
<div class="col-md-6">
    <div class="main-vipub-screenline">
    
        <div class="account-settings-page-for-users-page">
            <div class="settings-page-top-title">
                <h5>
                    <svg viewBox="0 0 24 24" aria-hidden="true"><g><path d="M7.414 13l5.043 5.04-1.414 1.42L3.586 12l7.457-7.46 1.414 1.42L7.414 11H21v2H7.414z"></path></g></svg>
                    <?php echo vipub_translate("account_settings"); ?>
                </h5>
            </div>

            <div class="settings-page-content-full next-settings-page-container-none-border">
                <div class="settings-edit-profile-right-zone next-settings-page-container">
                    <div class="edit-profile-right-zone-title">
                    <?php if (isset($_GET["oauth"]) && $_GET["oauth"] === "twitter"): ?>
                        <h5><?php echo vipub_translate("vipub_twitter_for_oauth_login_settings_password_page_info_title"); ?></h5>
                        <small><?php echo vipub_translate("vipub_twitter_for_oauth_login_settings_password_page_info_small"); ?></small>
                    <?php else: ?>
                        <h5><?php echo vipub_translate("account_settings_menu_43"); ?></h5>
                        <small><?php echo vipub_translate("account_settings_menu_42"); ?></small>
                    <?php endif; ?>
                    </div>
                    <div class="user-profile-edit-form-content-full">
                        <form id="change-password">
                            <div class="edit-input-profile">
                                <label for="password"><?php echo vipub_translate("account_settings_menu_43"); ?></label>
                                <input type="password" name="password" id="password" placeholder="<?php echo vipub_translate("account_settings_menu_43"); ?>">
                            </div>
                            <div class="edit-input-profile">
                                <button type="submit" class="password-save"><?php echo vipub_translate("account_settings_menu_27"); ?></button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
   $(document).ready(function() {
    $('#change-password').submit(function(event) {
        event.preventDefault();
        if ($('#password').val() === '') {
            var vipubSM_msgIcon = '<i class="bi bi-x-circle"></i>';
            var vipubSM_msgText = '<?php echo vipub_translate("settings_page_save_value_desc_15"); ?>';
            var vipubSM_alertTimeout = 5000;

            vipubSM.showAlert(vipubSM_msgIcon, vipubSM_msgText, vipubSM_alertTimeout);
        } else {
            $.ajax({
                type: 'POST',
                url: '/apps/ajax/settings/password.phtml',
                data: {
                    password: $('#password').val()
                },
                success: function(response) {
                    $('#password').val(response);

                    var vipubSM_msgIcon = '<i class="bi bi-check-circle"></i>';
                    var vipubSM_msgText = '<?php echo vipub_translate("settings_page_save_value_desc_16"); ?>';
                    var vipubSM_alertTimeout = 5000;

                    vipubSM.showAlert(vipubSM_msgIcon, vipubSM_msgText, vipubSM_alertTimeout);
                },
                error: function(response) {
                    var vipubSM_msgIcon = '<i class="bi bi-x-circle"></i>';
                    var vipubSM_msgText = 'Hata oluştu: ' + response.responseText;
                    var vipubSM_alertTimeout = 5000;

                    vipubSM.showAlert(vipubSM_msgIcon, vipubSM_msgText, vipubSM_alertTimeout);
                }
            });
        }
    });

    $('#password').attr('maxlength', 200);
});
</script>